### ISSUE TITLE
define and support json format

### ISSUE THREAD

**Issue by dkoes** [3dmol/3Dmol.js#10]
this should be trivial.. basically just documentation and not dumping unnecessary stuff

**Comment by jus1in** [comment]
What else needs to be done to ChemDoodle JSON support? What do you mean by not dumping unnecessary stuff?

**Comment by dkoes** [comment]
I think I was talking about producing json from a model - should only output the relevant information.

**Comment by jus1in** [comment]
What would that JSON be used for? Would it just be fed back into 3Dmol.js, in which it could be whatever format is most convenient for us, or should it be known format (ChemDoodle?) that other people can use?

What information should it store?
 * Atoms, Bonds?
 * Rotations?
 * Camera position?
 * Other things?

**Comment by dkoes** [comment]
Is it possible to make it compatible with chemdoodle while still storing any additional state information (e.g. styles, camera position) to fully restore the 3Dmol.js scene?

**Comment by jus1in** [comment]
I think so. It's JSON, so I should be able to add extra data and other parsers will just ignore it. Where can I find style and camera position? So far I've worked almost exclusively with file formats and don't know much about the rest of the code.

**Comment by dkoes** [comment]
Each atom has a style field.  You can get the view from the viewer (getView).

**Comment by dkoes** [comment]
Chemdoodle json is now supported.
