### ISSUE TITLE
more robust colorschemes 

### ISSUE THREAD

**Issue by dkoes** [3dmol/3Dmol.js#112]
should support user defined functions and have built in color by residue, structure, etc

**Comment by dkoes** [comment]
We have colorfun now, but it isn't documented (also an issue raised in #194)
Should have builtin color by chain.
The easiest way to do this is to define property maps that can then be provided to colorscheme

**Comment by dkoes** [comment]
Here's one possibly mapping for chains:
https://gist.github.com/carlosmr12/dca1caa6973b9e1e784cca9507a23017

**Comment by helblazer811** [comment]
So you want people to be able to pass a dictionary with all of the colors for each chain. That does not sound incredibly difficult.
