### ISSUE TITLE
CIF parser doesn't store cell info

### ISSUE THREAD

**Issue by sbliven** [3dmol/3Dmol.js#130]
The cif parser parses the unit cell parameters, but doesn't store them in the model.cryst variable as the PDB parser does.

**Comment by sbliven** [comment]
I implemented a quick fix for the cell parameters (all I cared about was getting addUnitCell working), but I didn't do anything with the symmetry operators or space group fields.

**Comment by dkoes** [comment]
Let's make sure we store the same info as we do with pdb files.
