### ISSUE TITLE
Add curved arrows

### ISSUE THREAD

**Issue by sbliven** [3dmol/3Dmol.js#137]
Support curved arrows using an optional parameter with the third point.

Curved arrows are formed by a torus section with an arrowhead, so this could also include a torus shape.

**Comment by sbliven** [comment]
I'm soliciting advice about the ShapeSpecs.

To specify the arrow curvature, one could either give a vector with the desired height and orientation of the curve relative to the straight line. Alternately, one can specify 3 points on the curve. For instance, for a semicircular arc in the XY plane I suggest one of these:
```
{
    start:new $3Dmol.Vector3(0,0,0),
    end:new $3Dmol.Vector3(10,0,0),
    apogee:new $3Dmol.Vector3(0,5,0),
    radius:.5
    // arrow params...
}
{
    start:new $3Dmol.Vector3(0,0,0),
    end:new $3Dmol.Vector3(10,0,0),
    through:new $3Dmol.Vector3(0,0,0)
}
```

For the TorusSpec, I'm not sure how to fix the orientation. Internally a quaternion or Matrix4 would be easiest, although maybe a centerpoint and normal would be more user friendly? I am currently considering (same semicircle):
```
{
    majorradius:5,
    minorradius:0.5,
    startangle:0,
    endangle:Math.PI,
    orientation:new $3Dmol.Matrix4().setPosition({x:5,y:0,z:0})
}
```

**Comment by dkoes** [comment]
I like through (I'm assuming it is suppose to be 0,5,0).  If you are feeling ambitious you could support specifying a list of points and draw a spline through all the points.

A centerpoint and a normal seems like the most user friendly combination for specifying a torus to me.

**Comment by helblazer811** [comment]
The through attribute could accept both a single vector and an array of vectors as well.

**Comment by sbliven** [comment]
I saw this was reopened. I made some commits towards the TorusSpec on my master branch back in 2015, but I probably won't have time to finish this project. Anyone should feel free to rebase my work if it's helpful.

**Comment by dkoes** [comment]
http://3dmol.csb.pitt.edu/tests/auto/generate_test.cgi?test=glviewer_js_addCurve
