### ISSUE TITLE
support reverse gradients

### ISSUE THREAD

**Issue by dkoes** [3dmol/3Dmol.js#140]
if min > max, should show colors in opposite order

**Comment by helblazer811** [comment]
I think that i resolved this with my pull request. Also the sinebow gradient was already equipped to do this.

**Comment by dkoes** [comment]
As always, make sure you add to the documentation..

**Comment by helblazer811** [comment]
No parameters were changed i just added functionality. Where should i document this?

**Comment by helblazer811** [comment]
Should i just modify this?
/**
 * Color scheme red to white to blue, for charges
 * @constructor
 * @implements {$3Dmol.Gradient}
 */

**Comment by dkoes** [comment]
Whereever min and max are documented.. use your best judgement.
