### ISSUE TITLE
PDBs do not show

### ISSUE THREAD

**Issue by lfrohman** [3dmol/3Dmol.js#147]
On the main web page

http://3dmol.csb.pitt.edu/doc/index.html

I tried 1D3E and 1D3L in the text box and hit the Download button (under the
"Using the source code title"), and nothing was shown.

**Comment by dkoes** [comment]
These PDB files contain only backbone atoms so any visual style that involve bonds will not display.  Spheres or cartoon traces will work:
http://3dmol.csb.pitt.edu/viewer.html?pdb=1d3l&style=sphere
http://3dmol.csb.pitt.edu/viewer.html?pdb=1d3l&style=cartoon:style~trace
http://3dmol.csb.pitt.edu/viewer.html?pdb=1d3e&style=sphere
http://3dmol.csb.pitt.edu/viewer.html?pdb=1d3e&style=cartoon:style~trace

**Comment by lfrohman** [comment]
got it, thanks
