### ISSUE TITLE
atom.resn is 3 characters long even for shorter residue names

### ISSUE THREAD

**Issue by ppillot** [3dmol/3Dmol.js#148]
For example in a DNA strand, an atom in a DA residue has its resn property set to " DA" (note the space).
If this is a feature, it looks error prone to me as it may result in problem when a user writes a selection by hand (e.g. model.setStyle({resn:"DA"},{stick:{color:"red"}}) instead of model.setStyle({resn:" DA"},{stick:{color:"red"}}) )

**Comment by dkoes** [comment]
Fixed. 36b01ea39a45327d6b69e1d9f4855b22962ce25c
