### ISSUE TITLE
add support for hover callback

### ISSUE THREAD

**Issue by dkoes** [3dmol/3Dmol.js#149]
in addition to click

**Comment by dkoes** [comment]
The first step is properly catch a mouse hovering (meaning that it hasn't moved for some period of time).  See glviewer.js and handleClickSelection

**Comment by helblazer811** [comment]
Ok. Should I fork the repository.

**Comment by helblazer811** [comment]
The intersect function in core.js may need to be edited because when i use it with the hoverable events nothing is returned.

**Comment by dkoes** [comment]
I responded to this on slack - I don't think so, you are putting exactly the same kinds of objects into the hoverables list as the clickables list.  It should return nothing if you aren't hovering over a hoverable object or aren't providing the right mouse coordinates.

**Comment by dkoes** [comment]
#178
