### ISSUE TITLE
drawCylinder doesn't support different caps

### ISSUE THREAD

**Issue by dkoes** [3dmol/3Dmol.js#150]
They end up either both spherical or both flat.

**Comment by helblazer811** [comment]
Could you give me an example call of this function so i have something to work with. I am not sure how to fill up thisdraw.drawCylinder = function(geo, from, to, radius, color, fromCap, toCap) .

**Comment by dkoes** [comment]
look through the test cases?

**Comment by helblazer811** [comment]
I did there are absolutely none. 😱

On Wed, Jul 6, 2016 at 11:18 AM, David Koes <notifications@github.com>
wrote:

> look through the test cases?
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/3dmol/3Dmol.js/issues/150#issuecomment-230805038>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ANhlxj182sPN6ljcBw4lEpKZOJY6Xu_6ks5qS8dhgaJpZM4G_4Vj>
> .
>



-- 


                                                               Sincerely,

                                                         Alec Helbling

**Comment by dkoes** [comment]
Not test13?

-Dave

On Jul 6, 2016, at 11:22 AM, Alec Helbling <notifications@github.com<mailto:notifications@github.com>> wrote:

I did there are absolutely none. ?

On Wed, Jul 6, 2016 at 11:18 AM, David Koes <notifications@github.com<mailto:notifications@github.com>>
wrote:

> look through the test cases?
>
> -
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/3dmol/3Dmol.js/issues/150#issuecomment-230805038>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ANhlxj182sPN6ljcBw4lEpKZOJY6Xu_6ks5qS8dhgaJpZM4G_4Vj>
> .
>



--


Sincerely,

Alec Helbling

-

**Comment by helblazer811** [comment]
Yes that has addCylinder , i was only looking for drawCylinder.

On Wed, Jul 6, 2016 at 12:16 PM, David Koes <notifications@github.com>
wrote:

> Not test13?
>
> -Dave
>
> On Jul 6, 2016, at 11:22 AM, Alec Helbling <notifications@github.com
> <mailto:notifications@github.com>> wrote:
>
> I did there are absolutely none. ?
>
> On Wed, Jul 6, 2016 at 11:18 AM, David Koes <notifications@github.com
> <mailto:notifications@github.com>>
> wrote:
>
> > look through the test cases?
> >
> > -
> > You are receiving this because you were assigned.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/3dmol/3Dmol.js/issues/150#issuecomment-230805038>,
> or mute
> > the thread
> > <
> https://github.com/notifications/unsubscribe/ANhlxj182sPN6ljcBw4lEpKZOJY6Xu_6ks5qS8dhgaJpZM4G_4Vj
> >
> > .
> >
>
>
>
> --
>
>
> Sincerely,
>
> Alec Helbling
>
> -
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub<
> https://na01.safelinks.protection.outlook.com/?url=https%3a%2f%2fgithub.com%2f3dmol%2f3Dmol.js%2fissues%2f150%23issuecomment-230806063&data=01%7c01%7cdkoes%40pitt.edu%7c0cfc751c0f2b488689c508d3a5b15fb1%7c9ef9f489e0a04eeb87cc3a526112fd0d%7c1&sdata=84QZcveeR%2bFqGphrliYQUKROWWSvu0%2bNkt6w8jOekHo%3d>,
> or mute the thread<
> https://na01.safelinks.protection.outlook.com/?url=https%3a%2f%2fgithub.com%2fnotifications%2funsubscribe%2fACO8_r838ifobFEfZOLIu_7EX-13GV74ks5qS8gtgaJpZM4G_4Vj&data=01%7c01%7cdkoes%40pitt.edu%7c0cfc751c0f2b488689c508d3a5b15fb1%7c9ef9f489e0a04eeb87cc3a526112fd0d%7c1&sdata=B2UstgAzfmaLzOXVDKvsY7%2fPfsarzz25VyA%2flxFqTg0%3d
> >.
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/3dmol/3Dmol.js/issues/150#issuecomment-230823752>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ANhlxmFxSdKhcvbbu5-Tw_6FM__MPpMAks5qS9TYgaJpZM4G_4Vj>
> .
>



-- 


                                                               Sincerely,

                                                         Alec Helbling

**Comment by helblazer811** [comment]
This works now.
