### ISSUE TITLE
report.cgi is loaded over http

### ISSUE THREAD

**Issue by RitwikGupta** [3dmol/3Dmol.js#152]
Most modern browsers block active mixed content by default now, so loading `http://3dmol.csb.pitt.edu/track/report.cgi` from a website that has HTTPS enabled results in the report script to be blocked.

**Comment by dkoes** [comment]
Does this is present an alert to the user? Or is it just a silent message in the console?

**Comment by RitwikGupta** [comment]
Currently it is presented as a silent log print. However, Firefox and Chrome plan to show an error in the address bar in coming releases. The latest Firefox Dev version is already marking mixed origin websites as insecure.

On Feb 9, 2016, at 6:22 AM, David Koes <notifications@github.com<mailto:notifications@github.com>> wrote:


Does this is present an alert to the user? Or is it just a silent message in the console?

-

**Comment by dkoes** [comment]
Okay, fixed.
8b9ce844a2fa8088d3e7c3147848dd1937e10c64

**Comment by RitwikGupta** [comment]
What about getting a free SSL cert from Let's Encrypt? `https://letsencrypt.org`

On Feb 9, 2016, at 8:40 AM, David Koes <notifications@github.com<mailto:notifications@github.com>> wrote:


Okay, fixed.
8b9ce84<https://github.com/3dmol/3Dmol.js/commit/8b9ce844a2fa8088d3e7c3147848dd1937e10c64>

-
