### ISSUE TITLE
regex fails for cid strings containing zeros

### ISSUE THREAD

**Issue by slamborne** [3dmol/3Dmol.js#153]
Heyo,

Was playing around with 3dmol and I couldn't load a compound, eventually cracked open the source and found this issue.
Thought I'd share to spare the next person some time.

In `$3Dmol.download` the query match doesn't acknowledge the existence of 0s.
https://github.com/3dmol/3Dmol.js/blob/master/3Dmol/3dmol.js#L114

`if (!query.match(/^[1-9]+$/)) {`

The query string "cid: 6089" fails.

`if (!query.match(/^[0-9]+$/)) {`

Tada! Now we can see our compound.

Awesome work, btw!

**Comment by dkoes** [comment]
Whoops.  Fixed.
2229dc08b193a21dbeb741b42785f34f7f43220c
