### ISSUE TITLE
Update registration to SSL

### ISSUE THREAD

**Issue by ajfarkas** [3dmol/3Dmol.js#155]
You can use [Let's Encrypt](https://letsencrypt.org/) to get a SSL cert for free, and it's relatively painless. You're going to miss out on a lot of regs otherwise.

**Comment by dkoes** [comment]
It's less painless when you need to deal with virtual hosts.
https://www.digitalocean.com/community/tutorials/how-to-set-up-let-s-encrypt-certificates-for-multiple-apache-virtual-hosts-on-ubuntu-14-04

(I'm putting this link here so I don't have to look for it again when I have time to work on this)

**Comment by dkoes** [comment]
the website now supports https
