### ISSUE TITLE
Create API Documentation

### ISSUE THREAD

**Issue by ajfarkas** [3dmol/3Dmol.js#156]
This is huge to get people using your library. One example of heavily used, robust documentation is [D3.js](https://github.com/mbostock/d3/wiki).

I'm happy to help with this once I'm more familiar with 3Dmol.

**Comment by helblazer811** [comment]
There is currently documentation at this link http://3dmol.csb.pitt.edu/doc/index.html. We could add more information to the wiki though.

**Comment by helblazer811** [comment]
I was thinking that it may be appropriate to employ some sort of search bar in order to make the documentation more accessible.

**Comment by helblazer811** [comment]
We definitely need to document more about Surfaces and how they can be easily implemented.
