### ISSUE TITLE
Push the latest 3DMol build to JSDeliver

### ISSUE THREAD

**Issue by RitwikGupta** [3dmol/3Dmol.js#163]
The CDN build is several commits behind, and these commits have brought huge improvements to performance to 3DMol

**Comment by dkoes** [comment]
Patience, once jsdelivr releases there's a new release it will automatically update to it (or at least that's what is suppose to happen...).

**Comment by dkoes** [comment]
Huh. It eventually updated - to version 1.0.2 instead of 1.0.5.  Trying a manual update now.

**Comment by ghutchis** [comment]
No, it's claiming "1.02" not "1.0.2" which it realizes it also has.

**Comment by dkoes** [comment]
Okay, I think things are straightened out now. I had missed that period.
