### ISSUE TITLE
add programmatic control of region to display isosurface

### ISSUE THREAD

**Issue by dkoes** [3dmol/3Dmol.js#172]
basically, let the user "cut" a density map down to a desired region (either using a box or sphere)

**Comment by publcif** [comment]
It would also be nice to show the map within a certain distance of selected atoms - e.g. only that part of the surface within x Ang of a ligand

**Comment by JimSEOW** [comment]
Features to display the region of protein molecular surface that is around the pocket given constraints information e.g. xx distance from the pocket center

**Comment by dkoes** [comment]
Can you make sure this is document and the documentation includes a code example?

**Comment by helblazer811** [comment]
For sure

On Wed, Jul 6, 2016 at 9:02 AM, David Koes <notifications@github.com> wrote:

> Can you make sure this is document and the documentation includes a code
> example?
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/3dmol/3Dmol.js/issues/172#issuecomment-230764406>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ANhlxk16mt6Fe3Mz0GW-2LdGRjgtDZnVks5qS6dhgaJpZM4IISDt>
> .
>



-- 


                                                               Sincerely,

                                                         Alec Helbling

**Comment by helblazer811** [comment]
Documentation should be there.

**Comment by publcif** [comment]
This functionality does not seem to be available. The addIsosurface function seems to have code to handle a volSpec.selectedRegion but I cant see how to define the selectedRegion using the API.

**Comment by publcif** [comment]
For what it's worth, for my purposes the answer was simply to add the selectedRegion and radius to the IsoSurfaceSpec because the documented .sel, .seldist, and .coords properties seem to have no effect, e.g.


glviewer.addIsosurface(voldata, {
            isoval: 0.1,
            color: "blue",
            opacity: 0.8,
            wireframe: true,
            smoothness:1,
            selectedRegion: [
            {x:this.x-1,y:this.y-1,z:this.z-1},
            {x:this.x-1,y:this.y+1,z:this.z-1},
            {x:this.x+1,y:this.y-1,z:this.z-1},
            {x:this.x+1,y:this.y+1,z:this.z-1},
            {x:this.x-1,y:this.y-1,z:this.z+1},
            {x:this.x-1,y:this.y+1,z:this.z+1},
            {x:this.x+1,y:this.y+1,z:this.z+1},
            {x:this.x+1,y:this.y-1,z:this.z+1}
            ],
            radius: 2.5
        });

**Comment by dkoes** [comment]
Here's an example of it working:
http://3dmol.csb.pitt.edu/tests/auto/generate_test.cgi?test=testAddModelPDB

Can you provide an example where it doesn't work for you?

**Comment by publcif** [comment]
My problem (misunderstanding?) was that the .sel, .seldist, and .coords properties of the isosurfacespec seem to have no effect, and the selectedRegion property is not documented...?

That is I was under the impression from the docs that setting .sel would define the selected region

Please forgive me if I've missed something obvious...

Cheers

Simon

**Comment by publcif** [comment]
PS: in the example at

http://3dmol.csb.pitt.edu/tests/auto/generate_test.cgi?test=testAddModelPDB

what does .selectedOffset do in the isosurfacespec:

viewer.addIsosurface(voldata, {isoval: 0.25,
                                       color: "blue",
                                       wireframe: true,
                                       selectedRegion: viewer.selectedAtoms({}),
                                       selectedOffset: 3,
                                       radius: 3.0                                   
                                    });

**Comment by dkoes** [comment]
You are right, the documentation is inconsistent with the code.  I've fixed it while retaining backwards compatibility for all the variations.  The correct properties to use are "coords" and "seldist".
2b1426e67248397041204fa953615f247824f64b
