### ISSUE TITLE
Orthoscopic projection or no perspective.

### ISSUE THREAD

**Issue by esguerra** [3dmol/3Dmol.js#174]
Hi,
Great work and thanks for sharing it with the community at large.
I am wondering if there is any setting to turn-off the perspective, or to get an orthoscopic projection.
This is important when displaying regular polymers, such as fiber models of nucleic acids, when their helical axis is orthogonal to the viewer.
Such as in:
https://en.wikipedia.org/wiki/A-DNA#/media/File:Dnaconformations.png
Thanks and once again, great work!

**Comment by dkoes** [comment]
I've added a setProjection method to the viewer class which takes a string (either "orthographic" or "perspective").  You can also initialize the viewer with a config option containing orthographic: true to get an orthographic projection.

An example is here:
http://3dmol.csb.pitt.edu/tests/testgl.html
There are buttons for switching between the projections.
