### ISSUE TITLE
Load benzene-homo.cube from TextArea

### ISSUE THREAD

**Issue by JimSEOW** [3dmol/3Dmol.js#175]
For the website 3dmol.csb.pitt.edu, 
I am learning by playing with the code.
Is it possible to load "benzene-homo.cube" from textarea defined below. If yes, please suggest some code. I know the file is relatively huge. I have tried different means and I just simply could not feed the file data to the javascript. Appreciate any suggestion

I have tried created a 
<textarea style="display: none;" id="moldata_sdf">
content of benzene-homo.cube
</textarea>

**Comment by dkoes** [comment]
Use jquery to get the contents.
```
    data = $('#idofdata').text()
    var voldata = new $3Dmol.VolumeData(data, "cube");
```
Unfortunately we do not yet have an embedded api for dealing with volume data.

**Comment by JimSEOW** [comment]
unfortunately, I tried, and it does not work :-(

**Comment by dkoes** [comment]
If you post your code or, better, point me to the website I can take a look.
