### ISSUE TITLE
Surface control

### ISSUE THREAD

**Issue by drc007** [3dmol/3Dmol.js#176]
It would be nice to have a method like getSurfaces() on the GLViewer class, so it would
    be possible to get an existing surface and change some of its styles/properties or remove it.
    At the moment it only seems you can addSurface() and removeAllSurfaces()

**Comment by dkoes** [comment]
Gah, the @function decorator was missing, so setSurfaceMaterialStyle wasn't showing up in the documentation, but you can do this.  See the implementation of toggleSurfTrans on this page:
http://3dmol.csb.pitt.edu/tests/testsel.html

51602ef

**Comment by drc007** [comment]
Brilliant
