### ISSUE TITLE
Some questions about version and license 

### ISSUE THREAD

**Issue by kennynaoh** [3dmol/3Dmol.js#177]
Hello @dkoes ,
I am the member of [cdnjs](https://github.com/cdnjs/cdnjs) project.
We want to host this library.
But there are some questions I want to ask.

First,
I saw the version in [package.json](https://github.com/3dmol/3Dmol.js/blob/1.0.5/package.json) is 1.0.2 in git tag 1.0.5.
Please help me confirm the version problem and fix it.

Second,
There are many licenses you use in [LICENSE](https://github.com/3dmol/3Dmol.js/blob/1.0.5/LICENSE) you mention.
The licenses you use are MIT, BSD, LGPL-3.0, right?
And what is the detail about BSD?
Maybe you could reference [this](https://github.com/cdnjs/cdnjs/blob/master/tools/license-list.json).

Thanks very much!

https://github.com/cdnjs/cdnjs/issues/7940

**Comment by dkoes** [comment]
I've updated the version and clarified the license (BSD-3-Clause)

e980bc1

**Comment by kennynaoh** [comment]
Hello @dkoes ,
You also need to update the version in release 1.0.5, not just in master branch.
Please help me confirm that.
Thanks for your help!

**Comment by dkoes** [comment]
How about I just publish a new 1.0.6 release with the right package.json?

**Comment by kennynaoh** [comment]
Looks good, thanks!
