### ISSUE TITLE
add way to display popup boxes after certain events

### ISSUE THREAD

**Issue by helblazer811** [3dmol/3Dmol.js#179]
This can be used to show the name of a shape when you hover over it or click on it for example.

**Comment by helblazer811** [comment]
Already able to do with labels.

**Comment by helblazer811** [comment]
Add a way to display labels where a mouse event occurs.

**Comment by dkoes** [comment]
I think this is probably something we would leave to the user to implement.. but we should create a test case with labels appearing and disappearing as an example for the documentation

**Comment by helblazer811** [comment]
Do you want the test case to be entirely implemented in the html document, or can i create a function in glviewer that displays a label at the position of the mouse automatically?

**Comment by dkoes** [comment]
We don't know a priori what people want to be in the label, so I would add a test case to the check directory that shows the residue and atom name of an atom when you mouse over it and then put the necessary code snippet into the documentation as an @example

**Comment by helblazer811** [comment]
test49 shows an example of the hover event. Their is probably a much more user friendly way to do it though.

**Comment by dkoes** [comment]
If you hover over an atom, the click handler will be give the atom object from which it can get the atom name.

**Comment by helblazer811** [comment]
In glviewer selected is passed to the hover_callback, but in the test the hover_callback does not have any parameters. Do i need to add selected as a parameter in order to get the name of the selected item.

**Comment by dkoes** [comment]
When you call the callbacks you should pass the exactly the same arguments as the click callback, which passes the intersected objects as the first element.

**Comment by helblazer811** [comment]
How would i add a single atom for the example?

**Comment by dkoes** [comment]
I've pushed an updated test49 with atom hoverables.  I don't like how I had to set the hoverable properties.  We need to make the equivalent of setClickables (in both the viewer and model) for hoverables (but it should take two callbacks).

**Comment by helblazer811** [comment]
I did this, but am unsure of how you wish for them to be used.
