### ISSUE TITLE
Which files need to be hosted?

### ISSUE THREAD

**Issue by kennynaoh** [3dmol/3Dmol.js#181]
Hello @dkoes ,
I am the member of [cdnjs](https://github.com/cdnjs/cdnjs) project.
I want to ask what is the main file you want to be hosted.
like `release/` or in `3Dmol/`?
Thanks for your help!

https://github.com/cdnjs/cdnjs/issues/7940
https://github.com/cdnjs/cdnjs/pull/8000

**Comment by dkoes** [comment]
We only need the contents of the release directory hosted.
