### ISSUE TITLE
allow model specific outline style

### ISSUE THREAD

**Issue by dkoes** [3dmol/3Dmol.js#185]
Like with transparency, this will be per-style per-model since it is a material property.  I've implemented the groundwork so we just need to set outline to true in the material, but have only implemented it with cartoons for now.  Also, I haven't yet added support for custom outline styles (uses whatever the last set viewer style is).

Arguably, we should switch from this being a viewer style to a model style sort of thing.

**Comment by dllahr** [comment]
Excellent!  Thank you.

**Comment by dkoes** [comment]
https://3dmol.org/tests/auto/generate_test.cgi?test=test28
