### ISSUE TITLE
3D viewer fails when website runs as  HTTPS

### ISSUE THREAD

**Issue by pieterlukasse** [3dmol/3Dmol.js#188]
Current browsers block the content when this library is embedded in a website that runs as HTTPS. Errors:

Mixed Content: The page at 'https://mysite....' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint '**http**://3dmol.csb.pitt.edu/track/report.cgi'. This request has been blocked; **the content must be served over HTTPS**.

Mixed Content: The page at 'https://mysite...' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint '**http**://www.rcsb.org/pdb/files/3AVS.pdb'. This request has been blocked; **the content must be served over HTTPS**.

The last one is one that rcsb.org needs to solve, but I added it here for completeness.

**Comment by dkoes** [comment]
Huh, the first one should have been fixed (8b9ce844a2fa8088d3e7c3147848dd1937e10c64)

The second one.. there doesn't seem to be a secure way to get pdb files.  The workaround would be to get SSL working on 3dmol.csb.pitt.edu and run requests through it as a proxy server, so I'll leave this issue open until that happens.

**Comment by pieterlukasse** [comment]
@dkoes thanks for the reply. I am probably using an outdated version of the library, which would explain the first error. 

Would be great if pitt.edu could server as a proxy for https indeed. I also reported the issue at rcsb.org....perhaps they also can fix it on their side. Let's see who gets a certificate first ;)

**Comment by dkoes** [comment]
HTTPS is now enabled on 3dmol.csb.pitt.edu.  You can workaround the problem with mixing secure/insecure transfers by using something like:
`$.get('https://3dmol.csb.pitt.edu/echo.cgi?url=http://files.rcsb.org/view/1ycr.pdb').done(function(pdb) { glviewer.addModel(pdb); glviewer.zoomTo(); glviewer.render();})`
to fetch the data.

**Comment by pieterlukasse** [comment]
Hi @dkoes , I get the following error:

```
XMLHttpRequest cannot load https://3dmol.csb.pitt.edu/echo.cgi?url=http://files.rcsb.org/view/4DNK.pdb. 
No 'Access-Control-Allow-Origin' header is present on the requested resource. 
Origin 'http://localhost:8080' is therefore not allowed access.
```

I haven't tested from our https server yet, but maybe you need to configure `Access-Control-Allow-Origin` header on your web-server? 

Anyway, I think using your proxy will be a temporary solution only. It will probably be better to have one on our own server such that we only need rely on PDB being up and running.

**Comment by pieterlukasse** [comment]
I now also tested from our https site and get the same problem there:

```
XMLHttpRequest cannot load https://3dmol.csb.pitt.edu/echo.cgi?url=http://files.rcsb.org/view/3AVS.pdb. 
No 'Access-Control-Allow-Origin' header is present on the requested resource. 
Origin 'https://g....io' is therefore not allowed access.
```

**Comment by dkoes** [comment]
Hmm.. I thought I'd tested this, but apparently the header wasn't being set.  Try again.

**Comment by pieterlukasse** [comment]
Tested. Works now. Thanks.
