### ISSUE TITLE
npm package

### ISSUE THREAD

**Issue by andreassteffen** [3dmol/3Dmol.js#189]
hi,
really awesome library!
Are you considering deploying it as a npm module?
Many thanks, Andreas

**Comment by dkoes** [comment]
What are the benefits of using npm as opposed to just checking the code out of git or copying the pre-built release?

**Comment by andreassteffen** [comment]
Just the convenience of a package manager.
it would be eg. easily addable to projects realized in frameworks build on
node.js/meteor.js just via npm install 3dmol

**Comment by helblazer811** [comment]
I think that it is fairly simple to add the project to npm. You just need to create a package.json file with certain information and add the built version I believe. It can all be done with the command line.

**Comment by dkoes** [comment]
I assume you add only the built version of the library (minified and unminified)?

**Comment by helblazer811** [comment]
yes 
i believe
