### ISSUE TITLE
setting surface colors by residue

### ISSUE THREAD

**Issue by andreassteffen** [3dmol/3Dmol.js#194]
Hi,
I want to color the surface according to some properties of the single amino acid residues.
I was trying via
viewer.setStyle({resi:cur_chain, chain:cur_chain, surfaceColor: cur_color})
viewer.addSurface(2, {opacity: 0.5})
with cur_color being a hexcode like '0xfee6da'.
but this did not affect the surface coloring. What am I doing wrong?
Many thanks!

**Comment by dkoes** [comment]
There isn't a surfaceColor property.  You should be able to specify the color mapping within the style specification of the surface using a colorscheme.  A colorscheme can be a string, in which case it maps to one of the element-based default color schemes, it can be a dictionary mapping from elements to colors, it can be an object with a prop field and gradient field that gets the numerical prop from the atom and converts it to a color using the gradient, or it can be an object with a prop field and a map field and get the color by indexing the map with the specified property.

Also, for maximum flexibility, you can specify a colorfunc as part of the style object which is a function that takes an atom object and returns a color.

All of this needs to be better documented.  The colorscheme documentation in particular.  Alec - can you create documentation with examples please?

**Comment by andreassteffen** [comment]
that'd be great!
however, in the atomspec it says there is a surfaceColor property:
http://3dmol.csb.pitt.edu/doc/types.html#AtomStyleSpec

**Comment by dkoes** [comment]
And that is wrong and should be updated..
