### ISSUE TITLE
Improved Test Architecture

### ISSUE THREAD

**Issue by helblazer811** [3dmol/3Dmol.js#196]
Create a single page that displays all of the tests. Make something that dynamically loads in all of the examples into the documentation with a display of how it looks. The test page should have a fixed canvas on one side of the screen and images of the different tests on the right side. The tests on the right  side can be clicked and that displays them in the canvas on the left side.

**Comment by helblazer811** [comment]
I have created a page that loads all of the reference images from the tests,then loads all of the javascript from those pages then takes a picture of the canvas and displays that. So you have two columns of images. It works for the most part except for surfaces which load after the model is rendered.

**Comment by dkoes** [comment]
Should prioritize the test for non-local variable declarations

**Comment by helblazer811** [comment]
Could you elaborate?

**Comment by dkoes** [comment]
Every test case should be wrapped with code that makes sure no variables (other than $3Dmol) should be added to the global namespace.  You can check this by recording all the variables in window before calling the code and making sure there's nothing new after calling the code.

See saveGlobal and checkPollution in tests/qunit.js

**Comment by helblazer811** [comment]
Yeah the viewer variable is not necessary I decided to do thst half way in.
I have just yet to fix some of the test cases.

**Comment by dkoes** [comment]
There's still more to be done here, yes?
 * autogeneration of examples from documentation
 * auto comparison of images
 * accurate timing of surfaces
 * automated running of tests and recording of trends, associate any regressions with code
 * global value pollution checking? error checking?

**Comment by helblazer811** [comment]
Ok. I guess this issue is very broad. I was thinking about the image generation.
