### ISSUE TITLE
error calling report.cgi

### ISSUE THREAD

**Issue by lfrohman** [3dmol/3Dmol.js#200]
I am using an older version of 3Dmol (I could not find the version number).
I started seeing the error below a while ago. We were ignoring it, but I realized
that this might prevent "if you would like to increase the likelihood of 3Dmol.js
remaining supported".

XMLHttpRequest cannot load http://3dmol.csb.pitt.edu/track/report.cgi. The 'Access-Control-Allow-Origin' header contains multiple values '*, *', but only one is allowed. Origin 'http://mydomain.com' is therefore not allowed access.

**Comment by lfrohman** [comment]
The cgi program is returning two origins:

curl -v http://3dmol.csb.pitt.edu/track/report.cgi
* About to connect() to 3dmol.csb.pitt.edu port 80 (#0)
*   Trying 130.49.226.162... connected
* Connected to 3dmol.csb.pitt.edu (130.49.226.162) port 80 (#0)
> GET /track/report.cgi HTTP/1.1
> User-Agent: curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.16.2.3 Basic ECC zlib/1.2.3 libidn/1.18 libssh2/1.4.2
> Host: 3dmol.csb.pitt.edu
> Accept: */*
>
< HTTP/1.1 200 OK
< Date: Mon, 25 Jul 2016 16:59:34 GMT
< Server: Apache/2.4.7 (Ubuntu)
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Origin: *
< Content-Length: 0
< Content-Type: text/html
< Connection: Keep-Alive
< Age: 0
<
* Connection #0 to host 3dmol.csb.pitt.edu left intact
* Closing connection #0

**Comment by dkoes** [comment]
Ah, I had hardcoded this response header into report.cgi, so when I enabled it globally on the server for other reasons it apparently ends up concatenating the two headers in an invalid manner.

It's fixed now.
