### ISSUE TITLE
Commonjs Support

### ISSUE THREAD

**Issue by justinmc** [3dmol/3Dmol.js#202]
This project should be useable as a module instead of having to add script tags to an HTML file.

```
var 3Dmol = require('3Dmol');
```

It's dependencies should also be required as modules (jQuery), to make managing dependencies easier and more modern for users.  And if all that can be done, it should definitely be published as an npm module too :)

**Comment by helblazer811** [comment]
#189

**Comment by helblazer811** [comment]
I added the package to npm.

**Comment by justinmc** [comment]
Thanks so much!  I'll try to remember to try it out later.

Here it is for posterity: https://www.npmjs.com/package/3dmol

**Comment by justinmc** [comment]
@helblazer811 As is, I was still not able to require the npm module and use it as shown in this issue due to a few npm quirks.  I've opened a PR to address these and it seems to work for me with those changes.  Let me know what you think, and then I think I'd consider this issue closed.  Thanks again and sorry for the slow response!

PR: https://github.com/3dmol/3Dmol.js/pull/257

**Comment by justinmc** [comment]
@helblazer811 Thanks for merging that!  I'll go ahead and close this issue.

Keep in mind that you'll need to publish a new release to npm for this to take effect (whenever the project is ready, no rush from my end).

**Comment by helblazer811** [comment]
No problem. Let us know if you want anything else completed or have any features that you want to push.
