### ISSUE TITLE
center( sel, animationDuration ) ?

### ISSUE THREAD

**Issue by sillitoe** [3dmol/3Dmol.js#204]
Thanks for all the work on this - looks great.

It would be really useful to zoom in to a particular residue (or set of residues) - something along the lines of: http://chemapps.stolaf.edu/jmol/docs/#center

Is this already possible? (couldn't see anything obvious in the docs)

**Comment by dkoes** [comment]
sel is an AtomSelectionSpec which can be used select specific residues.
http://3dmol.csb.pitt.edu/doc/types.html#AtomSelectionSpec

For example, to center on residues 1-5:
viewer.center({resi: [1,2,3,4,5]})

**Comment by sillitoe** [comment]
Thanks.

In that case the problem was that I couldn't see any documentation for:

viewer.center()

http://3dmol.csb.pitt.edu/doc/$3Dmol.GLViewer.html

Happy to make a PR for doc change when I'm next in front of a PC

**Comment by sillitoe** [comment]
I've just looked through the code and I can't see a method for:

viewer.center()

It's possible I haven't fully understood your reply, or I want clear with my original description - but it seems this issue is still valid (and should be open)?

**Comment by sillitoe** [comment]
I think my use of 'zoom' in the description was probably misleading.

The request was to have a function that sets the center of rotation at the center of mass for a set of residues.

Then you can rotate around the specific atom selection. This is useful when you have zoomed into a small set of residues away from the current center of mass.

**Comment by dkoes** [comment]
My bad, I assumed center already existed.  zoomTo will do this, but with the additional zoom, which you don't want.

Alec - please prioritize implementing this. I recommend factoring out the animation code from zoomTo to be reusable by anything that wants to animate a viewport transformation (e.g., translate as well).

**Comment by sillitoe** [comment]
No problem, many thanks

**Comment by helblazer811** [comment]
Try using test62.html and tell me if that is what you wished for. It is essentially zoomTo without the zoom in behavior.

**Comment by sillitoe** [comment]
looks good to me, many thanks
