### ISSUE TITLE
Input Format Documentation Out of Date

### ISSUE THREAD

**Issue by justinmc** [3dmol/3Dmol.js#216]
In the documentation for [addModel](http://3dmol.csb.pitt.edu/doc/$3Dmol.GLViewer.html#addModel) and [addModels](http://3dmol.csb.pitt.edu/doc/$3Dmol.GLViewer.html#addModels), an input format is missing.  It says the input formats are "'pdb', 'sdf', 'xyz', or 'mol2'", but "json" and "cdjson" are also valid options for ChemDoodle json.  You can see that these are supported in the [sourcecode](https://github.com/3dmol/3Dmol.js/blob/35efcce42ce8f993296e8147a3ed59364c010a97/3Dmol/parsers.js#L659).

**Comment by dkoes** [comment]
Actually, we support even more file formats than that.  I've updated the documentation (0d73177) and consolidated the file format support to one place (http://3dmol.csb.pitt.edu/doc/types.html#FileFormats)

**Comment by justinmc** [comment]
Thanks for updating that!  I didn't realize you guys supported all of those.
