### ISSUE TITLE
Chain/Residue Support via JSON

### ISSUE THREAD

**Issue by justinmc** [3dmol/3Dmol.js#219]
I'm using the [ChemDoodle JSON format](https://web.chemdoodle.com/docs/chemdoodle-json-format/) to load my model data into 3Dmol via `addModel`.  However, it seems like it's not possible to pass chain or residue information into 3Dmol via json.  Is there any other way to make 3Dmol aware of chain/residue data?  I'm trying to avoid having to generate a pdb or something.

**Comment by helblazer811** [comment]
Currently I believe that the ChemDoodle JSON parser only generates an array of atoms from the json string and does not provide any modelData, only atoms.

**Comment by justinmc** [comment]
Yeah I figured I couldn't do it via the cdjson parser.  My solution was to hack in the extra info after running `addModel` like this:

```javascript
    // Iterate over atoms that have been added
    viewer.getModel().selectedAtoms().forEach((atom) => {
      // Add missing data to each atom
      atom.atom = myData.atoms[atom.serial].atom;
      atom.chain = myData.atoms[atom.serial].chain;
      atom.resi = myData.atoms[atom.serial].resi;
      atom.resn = myData.atoms[atom.serial].resn;
    });
```

It would be nice to have an API for adding fully featured model data that doesn't require the use of an ugly plain text file format.  In my case, my application stores molecular data in its own json object, so it's easier for me to convert to cdjson and do the above hack than it is to write a .pdb generator.  Maybe if you added 3Dmol's own internal representation as another json format that would be best?

Anyway I got it working so I'm closing this issue, but if there's a better way to do this, please let me know!

**Comment by dkoes** [comment]
I think converting to the 3Dmol.js internal format and using addAtoms (in the model object) would probably be easiest and most efficient approach.
