### ISSUE TITLE
remove style function?

### ISSUE THREAD

**Issue by rkiminsilico** [3dmol/3Dmol.js#225]
For example, protein is shown in cartoon, and some residues have sphere sytle also on top of cartoon. Then, we want to change the protein's style to line, while keeping the additional sphere style for those some residues. As we look at the API, it seems that the way to achieve this is to use setStyle for all the atoms of the protein to line only and then add sphere style to those some residues. But, is it possible to do something like remove cartoon style from all atoms and add line style to all atoms, so that those some residues keep the additional sphere style?

**Comment by dkoes** [comment]
setStyle overrides the current style, addStyle adds.  Using addStyle with a hidden specifier should have the effect of "removing" the style. For example, addStyle({cartoon: {hidden:true}})

Let me know if that doesn't work (or if it does, and I'll close the issue).
