### ISSUE TITLE
let addSurface take string for surface type and generate log messages if an invalid type is passed

### ISSUE THREAD

**Issue by dkoes** [3dmol/3Dmol.js#229]
In the viewer object, let's let people pass "VDW" instead of $3Dmol.SurfaceType.VDW.  Also, if an invalid type is passed, we should print out a log message (and the default should probably be VDW, not SAS).

**Comment by helblazer811** [comment]
Should i do something similar to what i did with colorschemes and create a map?

**Comment by helblazer811** [comment]
It should work now. I created a pull request.
