### ISSUE TITLE
spectrum coloring in 3dmol is reversed and misleading

### ISSUE THREAD

**Issue by kad-ecoli** [3dmol/3Dmol.js#233]
I have tried to implement 3dmol on our webserver,. In the following webpage:
http://zhanglab.ccmb.med.umich.edu/NNB-QUARK/example/index2.html
you can find two protein structure widgets at the bottom. On the left is a protein visualize by JSmol. On the right is the same protein visualized by 3Dmol. I used ".setStyle({cartoon: {color:"spectrum"}})" to color the 3Dmol protein in spectrum. 

However, I notice that the "spectrum" coloring scheme is opposite to the usual spectrum scheme used by other program such as Jmol, Rasmol and PyMOL. In Jmol, Rasmol and PyMOL, spectrum coloring from N-terminal to C-terminal is from blue to red. On the other hand, in 3Dmol, the default spectrum coloring from N to C-terminal is from red to blue

**Comment by dkoes** [comment]
I agree that we should match the defaults of other tools and have updated the code accordingly (09682dee0a7b6e310621e020193aade993daf32d)

Note that in addition to the spectrum convenience style, you can precisely specify what sort of gradient you want (but have to provide the start and end residue numbers for the gradient):
```
viewer.setStyle( {
     "cartoon": {
             'colorscheme':{prop:'resi',gradient: new $3Dmol.Gradient.Sinebow(931,500)} 
     }
 });
```

Also, big fan of all the tools the zhanglab makes available (especially I-TASSER) and am glad to see 3Dmol.js being used.  Be aware that browsers limit the number of WebGL contexts allowed in a web page and the limit varies depending on the browser (this is relevant for when you are showing multiple models at a time).

**Comment by kad-ecoli** [comment]
Also, 3Dmol does not indicate directionality of beta strand when shown as cartoon. Is there a way to make 3Dmol show an arrow for each beta strand to indicate which end is N terminal and which end is C-terminal? something like this attachment is highly appreciated:
![1mq8a](https://cloud.githubusercontent.com/assets/7478069/18140435/83b44eb2-6f83-11e6-83fb-2f9d16fdd289.png)
