### ISSUE TITLE
beta strand directionality

### ISSUE THREAD

**Issue by kad-ecoli** [3dmol/3Dmol.js#234]
It seems 3Dmol does not indicate directionality of beta strand when shown as cartoon. Is there a way to make 3Dmol show an arrow for each beta strand to indicate which end is N terminal and which end is C-terminal? something like this attachment is highly appreciated:
![1mq8a](https://cloud.githubusercontent.com/assets/7478069/18140490/c681cb5c-6f83-11e6-904a-4b487f4499ce.png)

**Comment by dkoes** [comment]
Set arrows to true in the cartoon style spec:
http://3dmol.csb.pitt.edu/doc/types.html#CartoonStyleSpec
