### ISSUE TITLE
Chrome 53 breaks WebGL?

### ISSUE THREAD

**Issue by ddoherty** [3dmol/3Dmol.js#237]
Just upgraded to Chrome 53 (53.0.2785.89) on my Mac and went to:

http://3dmol.csb.pitt.edu/

which redirects to:

http://get.webgl.org/

In the console, it's throwing: "Error creating WebGL context." at 3Dmol-min.js:384 

Poked around a little and saw that there are reports of problems with Unity 3D on Chrome 53 -- WebGL broken.

Thought you'd want to know.  

Thanks for your efforts.

**Comment by ddoherty** [comment]
fwiw, it looks like WebGL is broken all over the place. For instance, go to Chrome's WebGL experiments:

https://www.chromeexperiments.com/webgl

and click one.

Same thing as described above.

**Comment by helblazer811** [comment]
Thanks for letting us know. I will look into it.

**Comment by dkoes** [comment]
It's working on my mac with Chrome (53.0.2785.89).  Your graphics card may have been blacklisted.  You can try rebooting your computer (this has worked for me in the past).  Also check that hardware acceleration is still enabled:
http://superuser.com/questions/836832/how-can-i-enable-webgl-in-my-browser
also
http://ccm.net/faq/40585-how-to-enable-webgl-on-google-chrome

**Comment by ddoherty** [comment]
Indeed, they have now blacklisted the Intel HD 3000 driver.  Boy, they sure are aggressive. I've never had WebGL problems with the card.

In case anyone has a circa 2011 MBP, you can work around with with --ignore-gpu-blacklist:

/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --ignore-gpu-blacklist

Working fine so far.  Thanks for the heads up.

**Comment by ddoherty** [comment]
Indeed, they have now blacklisted the Intel HD 3000 driver. Boy, they sure are aggressive. I've never had WebGL problems with the card.

In case anyone has a circa 2011 MBP, you can work around with with --ignore-gpu-blacklist:

/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --ignore-gpu-blacklist

Working fine so far. Thanks for the heads up.
