### ISSUE TITLE
mmtf returns different symmetry information than pdb

### ISSUE THREAD

**Issue by jlc206** [3dmol/3Dmol.js#238]
causing issues with calls to getSymmetries/setSymmetries

**Comment by jlc206** [comment]
var viewer = $3Dmol.createViewer("gldiv", {defaultcolors: $3Dmol.rasmolElementColors});
viewer.setBackgroundColor(0xffffffff);
$3Dmol.download('pdb:4UDV', viewer, {doAssembly:true}, function(){
            var m = viewer.getModel(0);
            var symm = m.getSymmetries();
                var i;
                for (i = 0; i < symm.length; i++) {
                        symm.splice(i, 1);
                }
                m.setSymmetries(symm);
                m.setStyle({},{cartoon:{color: 'red'}});
                viewer.render();
           }); 



for example the above code should remove every other asymmetric unit of 4UDV

**Comment by arose** [comment]
It seems the difference is between PDB and mmCIF files (the MMTF files we provide at the RCSB PDB are derived from the mmCIF files).

https://files.rcsb.org/view/4UDV.pdb
```
REMARK 350 BIOMOLECULE: 1                                                       
REMARK 350 APPLY THE FOLLOWING TO CHAINS: A, R                                  
REMARK 350   BIOMT1   1  1.000000  0.000000  0.000000        0.00000            
REMARK 350   BIOMT2   1  0.000000  1.000000 -0.000000        0.00000            
REMARK 350   BIOMT3   1  0.000000 -0.000000  1.000000        0.00000            
REMARK 350   BIOMT1   2  0.923478 -0.383651  0.000000       -0.00000            
REMARK 350   BIOMT2   2  0.383651  0.923478 -0.000000        0.00000            
REMARK 350   BIOMT3   2  0.000000 -0.000000  1.000000      -67.58400            
...
```

https://files.rcsb.org/view/4UDV.cif
```
H  'transform to helical frame' 1.00000000  0.00000000  0.00000000 0.00000 0.00000000  1.00000000  0.00000000 0.00000 0.00000000 
0.00000000 1.00000000 0.00000   
1  'helical symmetry operation' -0.98068300 0.19560383  0.00000000 0.00000 -0.19560383 -0.98068300 0.00000000 0.00000 0.00000000 
0.00000000 1.00000000 -33.79200 
...
```

Below is a rendering (by [NGL](https://github.com/arose/ngl)) with the PDB file in grey and the mmCIF (MMTF looks identical) in red. About half of the assemblies overlap, so it seems that just the helical frame is shifted.

![screenshot 9](https://cloud.githubusercontent.com/assets/272250/18824865/1ca67708-837a-11e6-9742-8f3a7579796f.png)

**Comment by dkoes** [comment]
So basically there isn't a fix.. :-(
