### ISSUE TITLE
Goggle Canary 57 demo crash

### ISSUE THREAD

**Issue by jlkjr** [3dmol/3Dmol.js#248]
In $3Dmol.VolumeData.prototype.cube, the call to splice with a single argument (aren't 2 arguments required?) causes a subsequent crash.
var raw = lines.splice(natoms + headerlines).join(" ");
raw = raw.replace(/^\s+/,'');
raw = raw.split(/[\s\r]+/);
causes a crash on the last line.  The correction
var raw = lines.splice(0, natoms + headerlines).join(" ");
fixes that, but the field doesn't get displayed in the benzene cube demo.

**Comment by dkoes** [comment]
Alex - please look into this and add a regression test when you fix it.
