### ISSUE TITLE
temperature factor coloring of protein surface

### ISSUE THREAD

**Issue by eguarnera** [3dmol/3Dmol.js#250]
Hi there,

With py3Dmol is there a command to show the protein surface colored according to the pdb temperature factors?

Thanks for the feedback.

Best,
EG

**Comment by dkoes** [comment]
You just set the colorscheme.  The only caveat is you have to manually specify the range (the default range is -1 to 1 and is inappropriate for b-factors).

```
view = py3Dmol.view(query='pdb:1ycr')
view.setStyle({'cartoon': {'color':'white'}})
view.addSurface(py3Dmol.VDW,{'opacity':0.7,'colorscheme':{'prop':'b','gradient':'sinebow','min':0,'max':70}})

```

I updated the example.ipynb, but nbviewer appears to be down so I can't give you a link :-(

**Comment by eguarnera** [comment]
Thank so so much!
