### ISSUE TITLE
pdb local file and py3Dmol

### ISSUE THREAD

**Issue by eguarnera** [3dmol/3Dmol.js#255]
Hi,

What am I doing wrong with this code? 

import py3Dmol

pdbfile='./file.pdb'
view=py3Dmol.view(width=400,height=400)
view.addModel(pdbfile,'pdb')
view.setStyle({'cartoon': {'color':'white'}})
view

It doesn't work to me, whereas all the other examples shown here work just fine. 

http://nbviewer.jupyter.org/github/3dmol/3Dmol.js/blob/d4cf7a1246ad37ad6e257ac5a48825a7707d3b5c/py3Dmol/examples.ipynb

Suggestions?

Best,
EG

**Comment by dkoes** [comment]
pdffile needs to be the actual contents of the pdb file as a string.  If you have a file, you should provide the URL to download.
