### ISSUE TITLE
Cartoon Arrows distort clicking on ribbons; resulting atom selection is not near the click

### ISSUE THREAD

**Issue by dbryanbio** [3dmol/3Dmol.js#261]
If Cartoon Arrows are enabled, clicking on a protein ribbon has unexpected results.  The selected atom is often quite far from the click.

It seems to be ok at the beginning of the chain and get worse as you pass through arrows.
I believe that it is a problem with the intersection detection, because in the attached demo, the position of selected regions doesn't change very much when you enable or disable arrows, but the click results do change quite a bit.

Steps to reproduce: 
1) Save attached file [arrow-selection-repro.txt](https://github.com/3dmol/3Dmol.js/files/688565/arrow-selection-repro.txt) as arrow-selection-repro.txt.  Save [3Dmol.txt](https://github.com/3dmol/3Dmol.js/files/688573/3Dmol.txt) as 3dmol.js in the same directory.
2) Load arrow-selection-repro.html into a browser.
3) Click on different sections of the ribbon.  You will see that the pink highlighted sections do not always correspond to what was clicked on.  Near the beginning of the chain (right edge, 1/3 of the way down), the behavior is correct, but as you move down the chain and pass arrows, it gets worse. Clicking on the left side of the protein should manifest the problem.
4) Deselect the Use Arrows checkbox at the top left.
5) Click around the ribbon again.  The behavior should be correct now.  Whatever you click on should be the region that is selected or unselected.
6) With the arrows still disabled, select a number of ribbon regions.
7) Select the Use Arrows checkbox at the top left.
8) You will see that the regions you just selected are still highlighted.  The atoms are being displayed in the right places.  This is why I think the problem is in the intersection detection.

**Comment by dkoes** [comment]
Thank you for the comprehensive bug report.  This is now fixed. The different number of points generated with arrows was throwing things off (also the coloring, which is also fixed).
4b037ecf35e2064a856750542a7ae74c5181aa18

@helblazer811 - add a regression for the color issue - load a multi-chain pdb and style each chain with a different kind of cartoon styling.  Color a couple residues in the middle of the protein differently - the color patches should be in the same place.

One the test is added, close the issue.

**Comment by dbryanbio** [comment]
Thank you so much for the quick turnaround. Go team!  Huzzah!

**Comment by helblazer811** [comment]
I added several tests that use various cartoon styles and zoom into them.
