### ISSUE TITLE
Cranky animation

### ISSUE THREAD

**Issue by guillefix** [3dmol/3Dmol.js#263]
After commit aecbfda85bf0ff9d75468ac25dadb0dd6167629c , whenever, I make two simultaneous animations, like a zoom, and a rotation, the molecule animates flashing between the two animations, instead of doing both at the same time, as if they forget to play out in sync!

**Comment by dkoes** [comment]
That was actually my intent - the animation overrides any other transformations so the end point is guaranteed to end up where requested.  I've made this optional with 2686ff5 (fixedPath argument).  Now by default the updates during the animation are relative so multiple transformations can be composed (e.g., if you rotate 180 degrees and the user rotates 90 degrees, the final rotation will be 270).
