### ISSUE TITLE
Can't get published NPM version to work

### ISSUE THREAD

**Issue by danielholmes** [3dmol/3Dmol.js#265]
I tried using the published NPM module and ran into an issue. My app couldn't find the 3dmol module. To replicate:

1. package.json
```
{
  "dependencies": {
    "3dmol": "1.0.7"
  }
}
```
2. `npm install`
3. run.js
```
var threeDMol = require('3dmol');
console.log(threeDMol);
```
4. `node run.js`

Error:

> module.js:474
>     throw err;
>     ^
> 
> Error: Cannot find module '3dmol'
>     at Function.Module._resolveFilename (module.js:472:15)
>     at Function.Module._load (module.js:420:25)
>     at Module.require (module.js:500:17)
>     at require (internal/module.js:20:19)
>     at Object.<anonymous> (/Volumes/data/projects/3dmol-test/run.js:1:79)
>     at Module._compile (module.js:573:32)
>     at Object.Module._extensions..js (module.js:582:10)
>     at Module.load (module.js:490:32)
>     at tryModuleLoad (module.js:449:12)
>     at Function.Module._load (module.js:441:3)

Using a clone of the latest repo works fine though (i.e. same example just using the following `package.json` where `../3Dmol.js` is a fresh cloned version of the repo

```
{
  "dependencies": {
    "3dmol": "../3Dmol.js"
  }
}
```

Could you please publish the latest version to NPM? By the looks of it I think you're the only person with the right permissions @helblazer811

**Comment by danielholmes** [comment]
[Made another issue](https://github.com/3dmol/3Dmol.js/issues/266) related to the published NPM module, should probably check that one before this

**Comment by danielholmes** [comment]
I see you've published a new version - thanks for that. The version on npm is missing one of the patches I needed though (https://github.com/3dmol/3Dmol.js/commit/4d66b564f073c56d8be48544e4b52fc0fde5b231). Is it possible to get another publish with this patch included?

**Comment by helblazer811** [comment]
I just pushed a new version ,which should be updated. Let me know if it is not working correctly.

**Comment by helblazer811** [comment]
I just tested it you should be good!

**Comment by danielholmes** [comment]
Thank you so much for the quick response @helblazer811 , I really appreciate it! All working well now here too

**Comment by helblazer811** [comment]
No problem.
