### ISSUE TITLE
Casing inconsistencies with the published NPM module

### ISSUE THREAD

**Issue by danielholmes** [3dmol/3Dmol.js#266]
In package.json (and everywhere I can see in the source) the library is referred to as 3Dmol (uppercase D), but its been [published under `3dmol` on npm](https://www.npmjs.com/package/3dmol). This mostly works alright for me since I'm on Mac OS X which doesn't care about casing, but I got an error from my [webpack](https://github.com/webpack/webpack) build process saying this will cause issues on other systems. Is it possible to change the published NPM package to the upper casing or publish a new package with the correct casing?

**Comment by helblazer811** [comment]
npm does not allow for package names to contain upper case letters. Could you give me more information on the error you are getting. Is the error because the package.json file has different casing?

**Comment by danielholmes** [comment]
Thanks, I didn't realise that about the package names.

Yes that's correct - the error is because the name in package.json is different to the published name
