### ISSUE TITLE
bug rendering long protein.

### ISSUE THREAD

**Issue by kad-ecoli** [3dmol/3Dmol.js#271]
I am trying to implement 3Dmol in COFACTOR server. However, there are two problems:
[1] For large protein, such as the one in http://zhanglab.ccmb.med.umich.edu/COFACTOR2/bug/input.pdb which is 1463 amino acid long, 3Dmol cannot render the structure at all. See
http://zhanglab.ccmb.med.umich.edu/COFACTOR2/bug/
Is there a way to overwrite the default behaviour and allow rendering of protein structures for up to 1500 amino acids?

[2] I want the output looks like this:
http://zhanglab.ccmb.med.umich.edu/COFACTOR2/example/
The "Proteins with similar structure" shows multiple entries in a table on the right. By clicking on the radio button of each entry, the corresponding structure will show on the left JSmol applet. Currently, the radio button is implemented by "jmolRadio". 
If I want to replace JSmol with 3Dmol, is there something in 3Dmol that resembles "jmolRadio", which allow the user to show/hide different structures in the same 3Dmol window by clicking on radio button?

[3] I have implemented 3Dmol in the new QUARK server. An example is available at:
http://zhanglab.ccmb.med.umich.edu/NNB-QUARK/example/
and it works great (in most of the time). I also make a fallback feature, so that if the web browser does not support webGL, it will use JSmol. However, I recently found that some browser only supports 8 WebGL window. This means if I have more than 8 models, sometimes it will only show the last 8. Is there any java script function that can automatically detect the maximum number of WebGL window?

**Comment by dkoes** [comment]
Hi Chengxin,

1) I've committed a fix for long chains in cartoon mode.  It should work 
now.

2) You have to implement your own javascript controls (e.g. with jQuery 
or equivalent).

3) The limit on WebGL canvases is really annoying and you can't get 
around it.  You could change your interface so each model is represented 
by a image snapshot and clicking on the snapshot will load the model 
into a single large viewer.  I don't know anyway to query the browser 
for this limit, but there is both a per-window limit and a per-browser 
limit.

-Dave

**Comment by kad-ecoli** [comment]
I guess the change is at glcartoon.js
I cannot install grunt (no root privilege) and I am not good at compiling javascript library. Is it possible for you to build a release for that? Or could you show me how can I modify 3Dmol.js  3Dmol-min.js to fix the problem?

**Comment by dkoes** [comment]
I thought I had re-built the hosted versions. I've re-built again just to be sure:
http://3dmol.csb.pitt.edu/build/3Dmol-min.js

**Comment by kad-ecoli** [comment]
This has changed the default background color from black to white. How could I change the background of viewer? In the above example, I have:

<script type="text/javascript" src="/3Dmol/3Dmol-min.js"></script>
<div id='input' style="height: 500px; width: 500px; position: relative;"></div> 
<script type="text/javascript">
viewer1 = $3Dmol.createViewer("input"); 
$.get('input.pdb', function(data) {
    struct1 = viewer1.addModel(data);
    struct1.setStyle({cartoon: {color:"spectrum",arrows:true}});
    viewer1.zoomTo();
    viewer1.render();
});
</script>

**Comment by dkoes** [comment]
You can call setBackgroundColor on the viewer or set it a ViewerSpec object passed as the second argument to createViewer. For example:
```$3Dmol.createViewer("input",{backgroundColor:'white'})```
