### ISSUE TITLE
Allow adding models to existing viewer in py3Dmol

### ISSUE THREAD

**Issue by greglandrum** [3dmol/3Dmol.js#275]
In the notebook I'd like to be able to do something like
```
p = py3Dmol.view(width=400,height=400)
p.removeAllModels()
mb = Chem.MolToMolBlock(m,confId=cid)
p.addModel(mb,'sdf')
p.setStyle({'stick':{}})
p.setBackgroundColor('0xeeeeee')
p.zoomTo()
p.show()
```
to create and display an instance of the viewer and then, later, do `p.addModel(mb2,'sdf')` (or whatever other add command) and have the existing view update. It'd be fine if I need to call some hypothetical `p.update()` or `p.refresh()` method afterwards.

**Comment by dkoes** [comment]
I've pushed a fix for this and updated the pip package.  See
http://nbviewer.jupyter.org/github/3dmol/3Dmol.js/blob/bc2afd053f2576c8837033328fa23bea644f365f/py3Dmol/updating.ipynb

8df5702342364fd8af657c9fb5c7d71252dc78d5

**Comment by greglandrum** [comment]
Thanks! That's exactly what I was looking for.

**Comment by TermeHansen** [comment]
I can't get the updating to work. It doesn't give a new viewer (as expected), but it also doesn't update the first viewer...

tried with [http://nbviewer.jupyter.org/github/3dmol/3Dmol.js/blob/bc2afd053f2576c8837033328fa23bea644f365f/py3Dmol/updating.ipynb](http://nbviewer.jupyter.org/github/3dmol/3Dmol.js/blob/bc2afd053f2576c8837033328fa23bea644f365f/py3Dmol/updating.ipynb)

on 
```
jupyter                   1.0.0                    py37_7  
py3dmol                   0.8.0                      py_0    conda-forge
```

Any idea of why?

**Comment by dkoes** [comment]
It's still working for me, including in an exported html file.  Can you reproduce it in a shareable colab notebook?  Any relevant messages appearing in the console?
