### ISSUE TITLE
'clearColor' of null

### ISSUE THREAD

**Issue by thomashrabe** [3dmol/3Dmol.js#277]
I am trying to run the tutorial page with the below code.

```
<html>

<head>
	<script src="http://3Dmol.csb.pitt.edu/build/3Dmol-min.js""></script>
</head>

<style>
.mol-container {
  width: 60%;
  height: 400px;
  position: relative;
}
</style>

<body>
	<div id="container-01" class="mol-container"></div>
</body>
<script>
$(function() {
	  let element = $('#container-01');
	  let config = { backgroundColor: 'white' };
	  let viewer = $3Dmol.createViewer( element, config );
	  viewer.addSphere({ radius: 10, color: 'green' });
	  viewer.zoomTo();
	  viewer.render();
	  viewer.zoom(0.8, 2000);
	});
</script>
</html>
```

but keep getting 

```
Error creating WebGL context.
Uncaught error creating viewer: TypeError: Cannot read property 'clearColor' of null
```

Not sure what's wrong here... 
Triead loading a PDB file, but same error. Seems `config` is not complete? Just guessing...

**Comment by helblazer811** [comment]
Hmmm. It works just fine for me. Can you try removing config. White is the default background color so the behavior should be the same.

**Comment by thomashrabe** [comment]
Works now in Safari, still fails in Chrome

```
// let config = { backgroundColor: 'white' };
let viewer = $3Dmol.createViewer( element);
```

By the way, is this Typescript or Javascript you are using?

**Comment by helblazer811** [comment]
This is JavaScript. The "let" statements are somewhat obscure, but they are still valid.

**Comment by hkirat** [comment]
Works fine for me.. 
Could you point out at which particular line the error occurs?

**Comment by GeekyShiva** [comment]
can you specify the device you are getting this error in ...... i got something [http://stackoverflow.com/questions/28466387/error-creating-webgl-context-in-chrome-but-not-in-android-browser](here)

This still can be an issue with chrome

**Comment by dkoes** [comment]
clearColor is a function of the WebGLRenderingContext.  If it doesn't exist, then your browser probably doesn't have webgl enabled.  You can check here:
https://get.webgl.org/

More information here:
https://superuser.com/questions/836832/how-can-i-enable-webgl-in-my-browser
