### ISSUE TITLE
linewidth option for line no longer works

### ISSUE THREAD

**Issue by dllahr** [3dmol/3Dmol.js#279]
It appears that the linewidth option / parameter when drawing a line no longer works.  For example, in the following code adjusting the linewidth all the way up to 10,000 doesn't change anything.

```javascript
var swapViewer = $3Dmol.createViewer('viewerDiv');

swapViewer.addLine({
      dashed:true,
      linewidth:10000,
      dashLength:0.25,
      gapLength:0.25,
      start:{x:0, y:0, z:0},
      end:{x:100, y:100, z:100}
});
swapViewer.setBackgroundColor(0xffffff);
        
swapViewer.render();
```

@dkoes  suggested:
> Chrome and Firefox decided they were going to stop supporting linewidths other than 1:
https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/lineWidth
>
>...As a workaround you could draw cylinders, but we don’t have a dashed cylinder.
>
> ... We need to decide the best way to restore the previous behavior (or an alternate behavior that’s just as good).  Perhaps remove the linewidth option and add dashed cylinders?

My coworker suggested we investigate how three.js does it - they do have a linewidth parameter for dashed lines, but I haven't tried using it / adjusting it (my initial guess is that it too will not work):
https://threejs.org/examples/?q=line#webgl_lines_dashed
https://github.com/mrdoob/three.js/blob/master/examples/webgl_lines_dashed.html

**Comment by dllahr** [comment]
quick follow up - I cloned the three.js repository and attempted to modify linewidth in the above example, it did not do anything, so I suspect three.js is suffering from the same issue.

**Comment by helblazer811** [comment]
I have added dashed cylinders.
`
viewer.addCylinder({
    dashed:true,
    radius:1,
    dashLength:2,
    gapLength:4,
    start:{x:-10, y:10, z:10},
    end:{x:-20, y:20, z:20},
    fromCap:2,
    toCap:2,
    color:"red",
});`

**Comment by dkoes** [comment]
Example:
http://3dmol.csb.pitt.edu/tests/auto/generate_test.cgi?test=test77

Given the removal of browser support for different widths in true lines, I think this is going to be our solution.

**Comment by dllahr** [comment]
Looks great to me - thanks!  I'll try it out.
