### ISSUE TITLE
Reverse ROYGB misses green colors

### ISSUE THREAD

**Issue by tryptochan** [3dmol/3Dmol.js#281]
Hi, I would like to color proteins from blue to red. 

The problem can be shown at http://3dmol.csb.pitt.edu/tests/example.html. Download 1UBQ and show as cartoon. 

The following code works as expected.
```javascript
glviewer.setStyle({chain: 'A'}, {cartoon: {
  colorscheme: {prop: 'resi', gradient: new $3Dmol.Gradient.ROYGB(1, 76)} 
}});
glviewer.render();
```

But reversing the index does not simply reverse the coloring. 
```javascript
glviewer.setStyle({chain: 'A'}, {cartoon: {
  colorscheme: {prop: 'resi',gradient: new $3Dmol.Gradient.ROYGB(76, 1)} 
}});
glviewer.render();
```
The green colors are missing and the blue part is also messed up. Reversing with Sinebow and RWB seems OK.

**Comment by dkoes** [comment]
That's because the math was wrong on the reverse ROYGB gradient :-(

Fixed. 5c26e6b
