### ISSUE TITLE
npm 3Dmol

### ISSUE THREAD

**Issue by pablowatson** [3dmol/3Dmol.js#283]
Hi,

I am trying to use 3Dmol.js ins a node project that is using browserify to generate a final js file for use on the client. I saw there was a npm version of 3Dmol.js so I installed in the usual way and (after reading some of the issues that the way to import it was the following.

const $ = require('jquery');
window.$ = $; // Do this globalize jquery.
const $3Dmol = require('3dmol');

Then you can go ahead and use $3Dmol to create the viewer.

However, the returned $3Dmol object does not seem to have any of the functions required to do this. The $3Dmol object looks like this:

![image](https://cloud.githubusercontent.com/assets/11069551/23628140/398623b0-0268-11e7-8bea-9501ccd0a319.png)

What am I missing here. The main in package.json for the 3dmol project seems to point to the minified version in the build directory (e.g. build/3Dmol-min.js). I tried changing it to 3Dmol.js, but there seem to be a set of dependency errors if I do this.

e.g.

Error: Cannot find module './common' ......
Error: Cannot find module './adler32' ......
Error: Cannot find module '../utils/common' ......

Any help would be great. 

Cheers,
Paul

**Comment by helblazer811** [comment]
Could you try using the relative path to "build/3Dmol-min.js". I need to look into support for commonjs, and that may be why require doesn't work.

**Comment by pablowatson** [comment]
Hi, thanks for getting back to me so quickly. So I tried each of the following:

const $3Dmol = require('3dmol');
const $3Dmol = require('3dmol/build/3Dmol-min.js');
const $3Dmol = require('../node_modules/3dmol/build/3Dmol-min.js');

All gave the same result as above.

Cheers,
Paul

**Comment by helblazer811** [comment]
OK thanks. I think that it is simply not compatible with commonjs(ie. require) currently. I will get that setup.

**Comment by pablowatson** [comment]
That is interesting as it looks like this guy got it working.

https://github.com/Autodesk/molecule-3d-for-react/blob/7265240a84c92253db62807e9e36c5d7ef7acbbb/src/components/molecule_3d.jsx

I wonder what I am doing differently? Anyway it would be great if you can make commonjs/node compatible. Thanks for the speedy response.

**Comment by ppillot** [comment]
I had the same problem previously with requirejs and the only workaround I found was to disable pako lib from the build script.
The 3dmol.js file embeds other libraries and it seems that only the first is being imported (at least with requirejs and browserify)

**Comment by dkoes** [comment]
I've added code to export to node.js modules (342508e428a25c30cdd94f5fbe275c967e38980f).

@helblazer811 - can you pull the latest code and update the npm package?

**Comment by helblazer811** [comment]
It should now be updated.

**Comment by helblazer811** [comment]
Let us know if it fixes your problems.

**Comment by pablowatson** [comment]
Nice one! I just install the latest npm package and I think it has resolved the issue. I am able to require 3dmoljs is the usual way e.g.

const $3Dmol = require('3dmol');

Great stuff
Cheers
