### ISSUE TITLE
Tiled View

### ISSUE THREAD

**Issue by pablowatson** [3dmol/3Dmol.js#285]
Apologies in advance as this might be a few issues in one.

I was wondering if there are any plans to implement a tiled view (I can't be the first person to have asked for this, though I didn't see anything that looked like this in the issues).

I am in the process of implementing a tiled viewer using 3Dmol.js and was able to link the viewers' rotation and orientation together using the linkViewer function, which I was really happy to discover. It might be work linking the slab modification i.e. ctrl + right button + drag to be linked as well.

This works really nicely and I can add or remove viewers to display whatever the user wants. The problems start when there are say 4 viewers and each contains a large-ish molecule with a surface. If I collapse the tiled view down to one viewer (or vice versa, create a tiled view from from one viewer that contains 4 large-ish molecules with surfaces) I can pretty reliably crash the  browser. I assume this is to do with regenerating the 4 surfaces. I did notice some references to web workers in the source so I assume the surface generation is multi threaded. Is there some way of doing this sequentially, perhaps a callback that notifies when the surface generation is complete.

Also, am I right in assuming you cannot hide/show surfaces - you can only add or remove them.

Sorry for the large list of questions.
Cheers,
Paul

**Comment by helblazer811** [comment]
You can hide/show surfaces with setSurfaceMaterialStyle, which takes a surface style spec, by specifying the opacity to be zero.

**Comment by dkoes** [comment]
You can set `$3Dmol.syncSurface` to true to render surfaces sequentially rather than in parallel (should probably rename this to be more descriptive..).

I'm not entirely sure what your vision is for the tiled viewer that is different than having multiple views linked together?

**Comment by pablowatson** [comment]
Thanks for the suggestions. I will try out the syncSurface setting and setting the opacity of surface to 0 to hide them.

I was hoping for a single canvas/glviewer that would do the tiling. You load the objects in to the viewer, define the tile layout  (e.g. 2 x 2) and say which tile you want it each object to appear in. Each 'tile' is really represents a translation matrix that would place the objects assigned to that 'tile'. Would something like that actually be feasible?

**Comment by dkoes** [comment]
Each tile is the exact same object, or are they different objects?

**Comment by pablowatson** [comment]
The tiles doesn't really exist. 

Maybe you have a map of tile locations to translation matrices e.g. assuming I have a 2 x 2 layout.

tile[0,0] -> matrix that moves the molecules/surfaces etc. to this tile to the top-left
tile[0,1] -> matrix that moves the molecules/surfaces etc. to this tile to the top-right
tile[1,0] -> matrix that moves the molecules/surfaces etc. to this tile to the bottom-left
tile[1,1] -> matrix that moves  the molecules/surfaces etc. to this tile to the bottom-right

You could also associate the various molecules/surface/maps to the 'tiles'. Each matrix then moves the molecule/surfaces/map to the right locations and it looks tiled even though you only have one viewer. Does that make sense?
