### ISSUE TITLE
Color in setStyle overwrites color set by other methods

### ISSUE THREAD

**Issue by tryptochan** [3dmol/3Dmol.js#288]
I am trying to do some custom coloring and found a problem that can be simplified as follows.
```javascript
var mod = glviewer.getModel();
mod.setStyle({chain: 'A'}, {cartoon: {color: 0xf6ff00}});
glviewer.render();     //yellow
mod.setColorByFunction({chain: 'A'}, function() { return 0x0004ff;});
glviewer.render();   //nothing changes
mod.setStyle({chain: 'A'}, {cartoon: {}});
glviewer.render();  //now blue
```

BTW, I was also trying to directly manipulate `atom.color` at the beginning, but there is not a public way of forcing rebuild. Is it a good idea to add a optional parameter to `GLViewer.render` or `GLModel.globj` to force a fresh rebuild?

**Comment by dkoes** [comment]
Actually, it may be a little unintuitive, but that is the correct behavior.  The color specified in the style object takes precedence over the atom object color.  We should really deprecate the atom object coloring approach.

You can provide a function to color by atom properties within the style object like this:
```
                 var colorAsSnake = function(atom) {
                   return atom.resi % 2 ? 'white': 'green'
                 };

                 viewer.setStyle( {}, { cartoon: {colorfunc: colorAsSnake }});
```
