### ISSUE TITLE
py3dmol + jupyter notebook, align plots horizontally

### ISSUE THREAD

**Issue by gosiao** [3dmol/3Dmol.js#290]
dear developers,

first, thank you for developing a very nice tool! 
i learned about it this morning and i thought that py3dmol together with Jupyter notebook would be a perfect combination to present results to my colleagues who do not use cheminformatics tools.

for instance, i would like to present various structures using

p = py3Dmol.view(width=200, height=200)
p.addModel(mol, 'xyz')
p.show()  

construct, but to align many such "p"s horizontally or create a matrix of "p"s, as for instance in FacetGrid method of seaborn: http://seaborn.pydata.org/generated/seaborn.FacetGrid.html
is it possible with py3Dmol.view? Or what would be the easiest way to hack it? 

thank you and best regards,
gosia

**Comment by dkoes** [comment]
You could hack it - all we are doing is returning html object and so they can certainly be put in a table.  However, be aware that browsers limit the number of WebGL contexts allowed on a page (usually no more than 8), so if you are envisioning an 8x8 grid, it isn't going to happen.

The easiest change to make is to provide the option of specifying the HTML container to put the viewer into.  I've implemented an `insert` method that does precisely that.  This gives you complete control over where the viewer goes, but you have to embed custom html into your notebook.

Here's an example:
http://nbviewer.jupyter.org/github/3dmol/3Dmol.js/blob/56c71a4fd2be130b0c201bd3bc068cf5b97fcafb/py3Dmol/insert.ipynb

If this seems good I'll updated the pip package.

**Comment by gosiao** [comment]
dear @dkoes,
thank you for the prompt reply!

i tried to reproduce your example, but with no success:
http://nbviewer.jupyter.org/github/gosiao/test_notebooks/blob/master/test.ipynb

i use jupyter installed via anaconda (ubuntu 16.04) within the defined rdkit environment (as explained here: http://www.rdkit.org/docs/Install.html),
do you know what i could be missing?

thanks!
gosia

**Comment by dkoes** [comment]
Did you get the latest py3Dmol from git?  Like I said, I haven't updated the package yet.

**Comment by gosiao** [comment]
I did it yesterday by:

pip install py3Dmol

and it is in my ~/anaconda3/lib/python3.6/site-packages/  py3Dmol version 0-6-1

i can install the latest from git if that will solve it

**Comment by dkoes** [comment]
I went ahead and updated the pip package.  If you `pip install --upgrade py3Dmol` you should get version 0.6.2.

**Comment by gosiao** [comment]
oh wow, thank you!!
(and i just started to clone git;))
i'll upgrade and try all right away

**Comment by gosiao** [comment]
that worked just great!
thank you!

**Comment by gosiao** [comment]
i'm sorry to bother you again,
i wanted to let you know that it does not seem to work with more than one figure, for instance:

http://nbviewer.jupyter.org/github/gosiao/test_notebooks/blob/master/test.ipynb

(unless i messed up with html code)

**Comment by gosiao** [comment]
hi again, update: everything works, all one needs to remember is to put

view.insert("label")

of all figures in separate jupyter cells

thanks again for help!! 
best regards,
gosia
