### ISSUE TITLE
interactive py3Dmol in jupyter notebook - not all py3Dmol.view() are visible

### ISSUE THREAD

**Issue by gosiao** [3dmol/3Dmol.js#291]
dear all,

i'm using rdkit with py3Dmol in jupyter notebook, as in this example (*):
http://nbviewer.jupyter.org/github/greglandrum/rdkit_blog/blob/master/notebooks/Trying%20py3Dmol.ipynb

is there a limit of how many py3Dmol.view() frames can be in one notebook?
i'm asking because it seems that jupyter notebook can handle only a limited number of these: with running all cells, even one-by-one, only few frames are visible and some disappear while scrolling, restarting does not help.

example:
http://nbviewer.jupyter.org/github/gosiao/test_notebooks/blob/master/notes_m1.ipynb

can that be changed somewhere? it does not seem to be related to the browser (firefox and chrome do the same), i don't have any problem in viewing or running similar example notebooks like the one pasted as first (*).

thank you and best regards,
gosia

**Comment by dkoes** [comment]
Browsers limit the number of allowed active WebGL contexts:
http://stackoverflow.com/questions/4951370/is-there-a-limit-to-how-many-opengl-rendering-contexts-you-can-create-simultaneo

Unfortunately, there's nothing we can do.
