### ISSUE TITLE
Question regarding VASP support + crystallographic data generally

### ISSUE THREAD

**Issue by mkhorton** [3dmol/3Dmol.js#295]
Hello,

I hope this is an appropriate place to ask.

I can see that 3Dmol's volume class has a 'vasp' option, and there are some references to POSCAR files in the code too, but I can't find documentation for this anywhere. Does 3Dmol.js support visualization of VASP POSCAR/CHGCAR files? (Edit: I've now found the vasp_test.html file in your source, so will try this out!)

More generally, how robust is 3Dmol.js' support for crystallographic data generally? i.e. is it possible to draw the unit cell bounding box, axes compass, or co-ordination polyhedra (if bonds have been detected)?

Thank you kindly for your time!

**Comment by mkhorton** [comment]
As a follow-up, these CHGCAR files can be very large (10s-100s MB) and not suitable for providing directly online. If 3Dmol can derive an isosurface, is there a way to serialize this isosurface, so that we can do the generation once and then supply the user with the derived isosurface instead of the CGHCAR, to save time loading/processing?

**Comment by dkoes** [comment]
You can call addUnitCell to draw the unit cell bounding box, but this currently only works with pdb and mmcif file formats.  We could certainly add support for other file formats if they have the required information.

Can you give examples of axes compass and co-ordination polyhedra?

You can use addMesh to provide pre-rendered isosurfaces.

**Comment by mkhorton** [comment]
Sure,

Axes compass: this is simply three arrows showing the direction of a, b and c lattice vectors defining the unit cell bounding box, e.g. see the arrows in this [image](https://www.researchgate.net/profile/O_Parasyuk/publication/258922075/figure/fig1/AS:297314498433024@1447896708322/Figure-1-A-unit-cell-of-Cu-2-CdGeS-4-Drawn-by-VESTA-40.png)

Co-ordination polyhedra: instead of a ball+stick atoms+bonds representation, it's common to draw spheres for atoms, and then join all the atoms an atom is bonded to together to form a polyhedron, example: https://www.materialsproject.org/materials/mp-12992/ This is a very common approach used by e.g. JMol, Vesta, CrystalMaker etc.

Regarding the vasp_test.html file, I've got this working on my computer (macOS, Safari, latest versions of each), but the web inspector complained about a missing 'chgcar.list' file the test page failed to load, I had to copy some files around to get it to work. I'm not sure if this was error on my part or a bug in the test file.

> You can use addMesh to provide pre-rendered isosurfaces.

Thanks, will look into this.

**Comment by mkhorton** [comment]
> You can call addUnitCell to draw the unit cell bounding box, but this currently only works with pdb and mmcif file formats. We could certainly add support for other file formats if they have the required information.

It looks like you're already parsing the relevant lattice vectors for VASP (POSCAR/CONTCAR) files:

https://github.com/3dmol/3Dmol.js/blob/master/3Dmol/parsers.js#L402

This should directly give the matrix necessary for [addUnitCell](https://github.com/3dmol/3Dmol.js/blob/8ee35f3840c943ee9db2404335c3b3df203518c9/3Dmol/glviewer.js#L2019)

I would submit a PR to add this, but my JavaScript is a bit rusty and I'm not sure I understand how 3Dmol.js works yet.

**Comment by mkhorton** [comment]
My previous implementation for addUnitCell didn't work, I think I tracked it down to the line `modelData.cryst = {'matrix':matrix}`. I'm not sure what was wrong with that, but it caused an exception [here](https://github.com/3dmol/3Dmol.js/blob/5cc81e0a6528413297b18b83d03e94dc6f634a85/3Dmol/glmodel.js#L1203) with `modelData.symmetries` being undefined?

Regarding my previous questions (axes compass, co-ordination polyhedra + more), is it okay if I create separate issues for these? I think I can probably implement the axes compass myself and submit a PR, but it might be easier to discuss if these were separate issues.

**Comment by dkoes** [comment]
Yes, separate issues please.  A contribution for co-ordination polyhedra would be especially welcome since I'm not familiar with them (the axes would be a fairly simple convenience function that draws three arrows)
