### ISSUE TITLE
New Version on NPM

### ISSUE THREAD

**Issue by danielholmes** [3dmol/3Dmol.js#297]
Is it possible to get a new version published on NPM with the last 7 weeks or so of changes? Using non NPM published versions is difficult for a client of ours and they need some of the recent updates.

Thanks!

**Comment by helblazer811** [comment]
It should be updated.

**Comment by helblazer811** [comment]
I will most likely start updating every other week.

**Comment by NicolasCARPi** [comment]
Hello,

It seems npm/yarn is stuck at 1.1.4. Can you publish the 1.3.0 there (and make it automatic so you don't have to do it manually at each release ;) ) ?

Cheers,
~Nico

**Comment by dkoes** [comment]
Updated to 1.3
