### ISSUE TITLE
improve support for multi-model file formats

### ISSUE THREAD

**Issue by mattragoza** [3dmol/3Dmol.js#30]
eg. 1MO7 and 1MO8 from pdb

**Comment by xiang-jun** [comment]
Is there any progress for supporting a MODEL/ENDMDL delineated ensemble of PDB structures? As an [example of use-cases](http://3dmol.csb.pitt.edu/viewer.html?url=http://x3dna.org/luxfiles/1ehz-triplets.pdb) I am interested in, 3Dmol.js currently overlaps the 4 base triplets. As shown below,  3Dmol.js takes them as a single structure, leading to erroneous linakges.
![3dmol-multi-model](https://cloud.githubusercontent.com/assets/12628634/9011172/87209f76-3779-11e5-8d59-e1121df114c8.png)
Upon my request, [pv](https://github.com/biasmv/pv) has already implemented [Support for displaying a MODEL/ENDMDL ensemble](https://github.com/biasmv/pv/issues/102). Another reference is ChemDoodle.MovieCanvas3D or ChemDoodle.SlideshowCanvas, even though the ChemDoodle Web Components library does **not** support a multi-model PDB file either.

**Comment by dkoes** [comment]
Ah, the pdb parser wasn't doing what it was suppose to and only read a single model.  I've committed a fix (please check with your file if possible).
6fdc4ef

Full multi-model support is coming Real Soon Now.  You will be either to load multiple models into a single model as frames or load them as separate model objects.

**Comment by xiang-jun** [comment]
Thanks for the quick fix. I've checked and verify that the PDB parser now reads correctly the first model. I am looking for full multi-model support in 3Dmol.js.

**Comment by dkoes** [comment]
Multi model support was implemented a while ago.
