### ISSUE TITLE
OnHover continue?

### ISSUE THREAD

**Issue by thomashrabe** [3dmol/3Dmol.js#300]
I am implementing the on hover method and see a `continue` printed to the console every time hover occurs. 

`3Dmol-nojquery-min.js:403 continue`

Can this be disabled for the future?

**Comment by dkoes** [comment]
Whoops.. that was some debug code left in.  I pushed a fix.  It will percolate to future releases.

**Comment by thomashrabe** [comment]
Thanks :D
