### ISSUE TITLE
The viewer.png() falls dont work.

### ISSUE THREAD

**Issue by r1z1a** [3dmol/3Dmol.js#301]
After looking though the source code i got to find this.
```
 /**
         * Return image URI of viewer contents (base64 encoded).
         * @function $3Dmol.GLViewer#png
         * 
         */
        this.pngURI = function() {
            return $('canvas',container)[0].toDataURL('image/png');
```

Seems like a small lable mistake, so if you call viewer.pngURI() works perfectly.
Possibly just update the [This page](http://3dmol.csb.pitt.edu/doc/$3Dmol.GLViewer.html#png)
Since its a little misleading for users seeing as one method is called png() but the actual one is pngURI().
Or possibly allow for both methods so if anyone else use the second one they code does not break.

**Comment by dkoes** [comment]
Fixed
bed76960eb8380a704ce206c1a2fac93d225cdf5
