### ISSUE TITLE
Extend clickable to onMouseUp

### ISSUE THREAD

**Issue by thomashrabe** [3dmol/3Dmol.js#305]
Does a `onMouseUp` feature already exist? It would be extremely helpful if it existed. Right now, running a short calculation in the `clickable` `callback` lags the user interaction with rotating the model. It would be great if the callback fired at `onMouseUp`. Right now it seems the `callback` fires whenever the mouse pointer touches the model. If you click and rotate the background, no callback function is executed. 

The current implementation lags the user interaction quite significantly.

**Comment by dkoes** [comment]
If you are clicking the background you aren't clicking the model and you don't need to do intersection testing.  If only care about clicks and not model interactions, you can install regular javascript handlers directly on the canvas.  Would that work for your use case?

**Comment by thomashrabe** [comment]
Hm, the call back needs the 3D intersection testing because it executes a residue specific process. However, it would be cool if it fired only at `onMouseUp` because the intermediate calculations make it slow...

**Comment by dkoes** [comment]
But the clickable callback should only fire on a mouseup event already.  Are you using the hover callback?

**Comment by thomashrabe** [comment]
No, we do not use the hover callback here. That created major delays for the user since the computation in that function took a few moments...

**Comment by dkoes** [comment]
Can you provide a self-contained example where you see the bad performance?

**Comment by thomashrabe** [comment]
Would take a while to re-implement, not much time now. But the issue was with mapping PDB residue IDs onto protein residue ids through a mapping function. Hover would execute the mapping function for every move - a loop over N integers. A hash lookup was not much better. The click now behaves similarly, but only then the mouse pointer hovers over the structure.

**Comment by dkoes** [comment]
I'm trying to understand the problem.  Callbacks and intersection testing should not happen during a mouse move; they should only happen on a mouseUp or after the hoverDuraction delay if the cursor _isn't_ moving.  Can you explain how your mapping function was getting called during a mouse move?

**Comment by dkoes** [comment]
Closing due to lack of communication about the issue.
