### ISSUE TITLE
$3DMol.download() stops functioning with different jQuery versions 

### ISSUE THREAD

**Issue by r1z1a** [3dmol/3Dmol.js#306]
So when loading 3Dmol.js it overides your current version of jQuery to ver. 1.11.3
If you load your jQuery after loading 3Dmol the download function breaks and console prints 
"parsererror" 

There is also a bunch of other errors that are coming up with setting style of residues when parsing info to 3dmol.

Not sure if there is a good workaround for this, or how it would be done.

EDIT:
http://conceptf1.blogspot.ch/2013/12/conflict-in-multiple-jquery-files-on-same-page.html

This blog post talks about the conflict of $ sign with multiple libraries, and how to work with 2 jQuery versions at same time, so it should be possible to remove the conflict and replace $ with say $jQ1.11.3 in 3Dmol so it would not cause issues. Hope this can be of help

**Comment by r1z1a** [comment]
I realised there is a "3dmol-nojquery.js" version, which i think solves the problem

**Comment by helblazer811** [comment]
Ok, let us know If you have any more issues.

**Comment by r1z1a** [comment]
@helblazer811 
Hey, yeah since the new release I have an issue with both 3dmol.js and 3dmol-nojquery.js when i try to use the new release version. 
I get an error:

> Uncaught TypeError: Cannot read property '1' of null
>     at propertyMatches (3Dmol.js:27547)
>     at GLModel.atomIsSelected (3Dmol.js:27649)
>     at GLModel.selectedAtoms (3Dmol.js:27685)
>     at getAtomsFromSel (3Dmol.js:30865)
>     at GLViewer.selectedAtoms (3Dmol.js:30913)
>     at selectPoint (pointUpdate.js:115)
>     at n.<anonymous> (plotScatter.js:126)
>     at n.emit (plotly-latest.min.js:18)
>     at HTMLDivElement.t.emit (plotly-latest.min.js:57)
>     at r (plotly-latest.min.js:53)
> 

The previous release is working just fine but the new one are giving me this error, so i'm unsure what was changed in the release that is causing this.

**Comment by dkoes** [comment]
That's a bug with code I recently added that provides support for numerical ranges, eg:
`resi: '3-30'`
I bet `number` in your example is a string instead of an integer.  Unfortunately, all our test cases for resi selection used integer typed values so the bug wasn't caught.  I've pushed a fix and updated the tests.

I'm not sure what's up with jquery.  I tried upgrading to 3.2.1 and don't experience any problems.  Really, we should remove the jquery dependency from the core library and implement the few functions we use ourselves.

**Comment by r1z1a** [comment]
Yes I was passing the `resi `as a string, so I would guess that's the issue. 

As far as the jQuery issue, i'm unsure myself why its like so, I think i will from now on use the nojquery version so there is no conflicts. Personally It would be great to see it without the dependency, as it will give it a better future life.

**Comment by dkoes** [comment]
To be clear, this wasn't your bug - you should be able to pass the resi number as a string. 

The inclusion of jquery is more for our convenience than for the convenience of people using the library, so I think we'll change that sooner rather than later.
