### ISSUE TITLE
documentation of gradient colorcheme needs improvement

### ISSUE THREAD

**Issue by dkoes** [3dmol/3Dmol.js#309]
References examples that don't exist.  Doesn't specify that builtin gradients can be specified by name.

**Comment by keshavg2** [comment]
Hi @dkoes How can I proceed with this issue?

**Comment by dkoes** [comment]
See http://3dmol.csb.pitt.edu/doc/types.html#ColorschemeSpec  for the inadequate documentation in question.

**Comment by keshavg2** [comment]
Hi @dkoes sorry for ask you here.
Can you please review this Proposal 
https://docs.google.com/document/d/1Yo7a6EUj0OZcfDZBh8bM8vYT4bdp_TezFxJmgZXoBZE/edit?usp=sharing

**Comment by gaurivn** [comment]
I would like to work on this issue.
