### ISSUE TITLE
better support for gradients

### ISSUE THREAD

**Issue by dkoes** [3dmol/3Dmol.js#310]
We should have more builtin gradients.  A lot of inspiration can be taken from seaborn (especially sequential and diverging palletes):
http://seaborn.pydata.org/tutorial/color_palettes.html

Should have setStyle interrogate the syle object to regonize gradients without min/max value and computer them automatically from the selection.

**Comment by lukaszgit** [comment]
I have a (probably naive) question - how can I access objects such as Sinebow to directly get rainbow colors ? I would like to render a series of arrows (generated in a loop) and color them using the same gradient that I use for cartoon model.
best,
Lukasz

**Comment by lukaszgit** [comment]
I think, I figured it out (probably not optimally) thanks for a great program !
 var grad=new $3Dmol.Gradient.Sinebow(scalelength,0)

/* and colors would be:

 color=grad.valueToHex(i)

/* for i from 0 to scalelength

**Comment by dkoes** [comment]
That's what I'd do, so looks good to me.
