### ISSUE TITLE
support atom selections in place of coordinates

### ISSUE THREAD

**Issue by dkoes** [3dmol/3Dmol.js#315]
For example, the start/end of a line specification could be atom selections. The center of the selected atoms would be used.  Basically, if the start/end objects don't have x/y/z fields but are objects, assume they are selections

**Comment by helblazer811** [comment]
I could do it by just taking the selection and replacing it with the coordinates as right after the user passes it. This will mean that no changes to the code other then this conversion need to be made.

**Comment by dkoes** [comment]
but you need to verify that it isn't an object that has x,y,z members.  Also, you want to take the average of all the selected atoms.  This would be in a function that could be called by all the methods in draw that have start/ends
