### ISSUE TITLE
Enable auto-rotate on rendering

### ISSUE THREAD

**Issue by vishalkpp** [3dmol/3Dmol.js#330]
Is it possible to auto-rotate the scene as soon as it is rendered on a web page? (a feature similar to 'spin on/off' in JS Mol). Would be glad to see an example implemented on 3Dmol.js web site.

**Comment by dkoes** [comment]
You mean like the one embedded in the first page of the documentation?
http://3dmol.csb.pitt.edu/doc/index.html

**Comment by vishalkpp** [comment]
Yes! My bad, I haven't noticed this. Was playing around with other implementations to use rotate function. Thanks for pointing to the example implementation.

**Comment by dkoes** [comment]
Still, wouldn't be a bad idea to have a `spin` viewer function.  If called with no arguments or `true`, it would spin around [1 0 0], if called with `false` it would disable any spinning, if called with 'x', 'y', or 'z' it would spin around the specified axis, if called with a list of 3 numbers, it would spin around that axis.  @helblazer811 - when you get a chance

**Comment by vishalkpp** [comment]
That would be perfect! Will look forward. Thank you!

**Comment by helblazer811** [comment]
This should be implemented. You can call viewer.spin(true,'x',50). This will spin the specified viewer around the x axis by 1 degree every 50 milliseconds. If the timing is not how you imagined it implemented i can change how that is done. 'x' is also interchangeable with lists of numbers [0,1,1] and objects {x:0,y:1,z:1}. You can turn off the current spin by doing viewer.spin(false).

**Comment by vishalkpp** [comment]
Thanks @helblazer811 . I tried using the spin function but somehow couldn't get it to work. Rotate works well though. Should the new spin function be used the same way? Please correct me if I am wrong. https://pastebin.com/8eDZRn8K

**Comment by helblazer811** [comment]
Is this link pulling from npm or some other place? http://cdn.jsdelivr.net/3dmol.js/latest/3Dmol-min.js .
If so you can try cloning and building yourself. I will update the npm repository.

**Comment by helblazer811** [comment]
The directions for building are on the main github page https://github.com/3dmol/3Dmol.js. You can download the files as a zip and just follow these directions. I do not think that i can personally update jsdelivr, but @dkoes may be able to.

**Comment by dkoes** [comment]
The jsdelivr mirror only gets updated when we tag a release.  For the latest version link to `3dmol.csb.pitt.edu/build/3Dmol-min.js`
