### ISSUE TITLE
disable tracking

### ISSUE THREAD

**Issue by jjgao** [3dmol/3Dmol.js#337]
Is there any way that we can disable tracking (https://3dmol.csb.pitt.edu/track/report.cgi). 

3Dmol is a great tool -- thanks for that. But automatically turn on tracking actually created a data leaking problem for us especially for hospital users? Is there any way we can turn it off except hacking the code?

Thanks!

**Comment by dkoes** [comment]
Tracking is how we can report usage to our funding agencies, so we prefer you don't disable it. I suspect the NIH in particular would be quite happy to know that hospitals are using software it is funding. It does nothing more than make a connection (it is not sending data).

Nonetheless, I've added a notrack option: ddb36509fe8f73db1b8091b0096bfe7113c271d8
Before loading the 3Dmol.js script, you need to initialize a global $3Dmol object with this option set
```
$3Dmol = {notrack: true};
```

**Comment by jjgao** [comment]
@dkoes thank you!

**Comment by onursumer** [comment]
@dkoes thanks for this new option! When should we expect this to be released on npm?

**Comment by dkoes** [comment]
@helblazer811  I tagged a new release (1.2.0).  Can you push this to npm?

**Comment by jjgao** [comment]
Thanks. Could the new release be pushed to npm soon?

**Comment by dkoes** [comment]
Done!

**Comment by onursumer** [comment]
Thanks @dkoes, but looks like the `release` folder within the published npm version still contains files from 8 months ago...

**Comment by dkoes** [comment]
The build directory should be up to date

**Comment by onursumer** [comment]
@dkoes We have been using the `build` directory previously, but looks like with the latest release there is no `bulid` directory anymore.

**Comment by dkoes** [comment]
Whoops.  That was a mistake.  I've pushed a patch to put the build directory back (1.3.2)
