### ISSUE TITLE
Render two ligands from the same SD file

### ISSUE THREAD

**Issue by vishalkpp** [3dmol/3Dmol.js#338]
Hi there!

I am very much pleased using the library for visualization of 3D structures on my project website. I am now wondering if it is possible to render two ligands that are present in a single SD file, and probably color them differently in order to distinguish? (similar to: a ligand and target displayed at the same time in different colors using a PDB file).

Please ignore my question if it is addressed before.

Thanks a lot!
Vishal

**Comment by dkoes** [comment]
You probably want to use addModels to create multiple independently styles models from your multi-structure input.
http://3dmol.csb.pitt.edu/doc/$3Dmol.GLViewer.html#addModels

**Comment by vishalkpp** [comment]
Thank you! I couldn't crack it with 'addModels' but it seems that the SD file could not be read when I tried it with 'AddModel'. I get an 'invalid XML' error when I tried to load an sd file dynamically. Please find below a small piece of code.

https://pastebin.com/DbvgpCjK

I'd be thankful if you could point me to an example implementation of loading multiple models from the same sd file.

Thank you!

**Comment by dkoes** [comment]
The fact that you are getting an invalid XML error makes me think that jQuery.ajax things you are trying to load xml instead of a plain text file.  Try using get instead (https://api.jquery.com/jquery.get/).
