### ISSUE TITLE
AddModel - Error reading SDF/PDB

### ISSUE THREAD

**Issue by vishalkpp** [3dmol/3Dmol.js#339]
Hi,

It seems that the SD file cannot be parsed when I try 'AddModel'. It throws an 'invalid XML' error when I load a single sd file. The paste (link below) has the code that I just tried and also please find below the screenshots of the error console.

https://pastebin.com/DbvgpCjK

<img width="1278" alt="screen shot 2017-09-05 at 22 00 07" src="https://user-images.githubusercontent.com/5487952/30080954-bcbafca8-9285-11e7-9f01-1a2201afc2ad.png">

The same holds true for a PDB file.

<img width="1278" alt="screen shot 2017-09-05 at 22 32 58" src="https://user-images.githubusercontent.com/5487952/30082198-3b15ccb4-928a-11e7-9b4c-6444eb7b85d2.png">

Thank you in advance!

**Comment by dkoes** [comment]
Don't use ajax, use get. You aren't loading an xml file.

**Comment by vishalkpp** [comment]
Oh yes, it works with 'get'. Thank you! But I wonder what makes the same script not work on Firefox. I still get the XML parsing error on Firefox. But it works on Safari. (see result below).

<img width="613" alt="screen shot 2017-09-06 at 00 47 10" src="https://user-images.githubusercontent.com/5487952/30086737-fe3b8622-929c-11e7-86dc-28fb272f2c33.png">

**Comment by dkoes** [comment]
Most likely you have to refresh your cache in Firefox.

**Comment by vishalkpp** [comment]
I tried that too! Did not help.
https://pastebin.com/Vk0VyuV2 (in case you would like check it at your end.)

**Comment by dkoes** [comment]
https://support.mozilla.org/en-US/questions/1103414

**Comment by vishalkpp** [comment]
Unfortunately, that does not help too! :(

**Comment by vishalkpp** [comment]
Sadly, my Google chrome console complains too (screenshot below). Do you think this is a browser issue again? @dkoes Sorry for constantly poking regarding this but it would be nice to know the solution, especially when I want my website to be used in different browsers.

<img width="555" alt="screen shot 2017-09-06 at 01 04 29" src="https://user-images.githubusercontent.com/5487952/30087292-296afe9c-92a0-11e7-8133-26b90dff522e.png">

I would really appreciate any suggestions to this end.

Thanks a lot!

**Comment by dkoes** [comment]
If you are making a cross-orgin request, it isn't going to work unless the server specifically allows them. https://en.wikipedia.org/wiki/Cross-origin_resource_sharing

**Comment by vishalkpp** [comment]
Many thanks @dkoes !

In that case, I guess I would resort to embedding the data in the webpage itself, which pretty much solved the issue.
