### ISSUE TITLE
setView documentation help

### ISSUE THREAD

**Issue by thomashrabe** [3dmol/3Dmol.js#341]
We need a little help in understanding the `setView` method. We have translations and rotation matrices from a structure alignment tool and would like to input the parameters into 3DMol to adjust models.

```
setView(arg)

Sets the view to the specified translation, zoom, and rotation.

Name | Type | Description
-- | -- | --
arg | Array.<number> | Array formatted identically to the return value of getView
```

**Comment by dkoes** [comment]
This was kinda intended to function more as a black box, but the numbers are:
`[ pos.x, pos.y, pos.z, rotationGroup.position.z, q.x, q.y, q.z, q.w ]`
First three are translation, then scale factor, then the rotation quaternion.

I'm not sure this will help you, though.  This will rotate the whole scene, not individual models, which is what you need to do if you are aligning two proteins.  In fact, we don't have a way to manipulate models.  You have to directly manipulate the coordinates of the atoms (call selectedAtoms, iterate over the results changing the coordinates, re-render).

**Comment by thomashrabe** [comment]
Thanks for the input! We showing one model per view, hence rotating the whole scene should be ok.

Can you please advise - what is the best way to transform a rotation matrix to your quaternion notation? I did it long time ago transforming the rot. matrix back into the 3 euler angles and then into quaternions. But there might be a cleaner approach...

**Comment by dkoes** [comment]
The $3Dmol.Matrix4 class (which isn't really documented since it was intended for internal use) has a decompose method that will convert a rotation matrix to all these numbers.
https://github.com/3dmol/3Dmol.js/blob/master/3Dmol/WebGL/math.js

You probably also want to look into linkViewers.  @helblazer811 also recently implemented a splitviewer that uses only a single canvas (and you should be able to link the subviewers) that I would appreciate feedback on:
https://github.com/3dmol/3Dmol.js/pull/334

**Comment by thomashrabe** [comment]
Maybe would be worth making it available in the documentation for interacting with distributed systems...

**Comment by dkoes** [comment]
I've created in issue to add documentation (#342)

**Comment by thomashrabe** [comment]
A little help - I'm confused with the `return function` notation for the matrix `decompose` method. How would I call it? 

My guess is something like `[translation, rotation, scale] = myMatrix.decompose()`, but I am not sure with that nested return function with parameters...

**Comment by thomashrabe** [comment]
Oh no, I get it

`return function ( translation, rotation, scale )` => ` translation, rotation, scale ` are attributes of `this`. I wasn't sure where they came from. Cheers.
