### ISSUE TITLE
Rendering seems not to work on SDF files with no title

### ISSUE THREAD

**Issue by mark-cresset** [3dmol/3Dmol.js#343]
In my testing, if you provide a molecule in SDF format, but with an empty title and comment, then it is not rendered by 3DMol - you just get  a blank screen. Example SDF is attached.

[sdf_title.zip](https://github.com/3dmol/3Dmol.js/files/1302723/sdf_title.zip)

**Comment by dkoes** [comment]
I can't reproduce this, and we don't parse the title anyway - we skip right past the first three lines.  Is it possible that whatever code you are using to fetch the data is stripping off whitespace from the beginning of the string?

**Comment by mark-cresset** [comment]
Hi David,

Yes, that’s possible – we embed the SDF data in the HTML as a hidden textarea and tell 3Dmol to use that as the input data. I’ll see if I can narrow down the test case more.

Thanks for looking into this!

Regards,
Mark

--
Mark Mackey
Chief Scientific Officer
Cresset
New Cambridge House, Bassingbourn Road, Litlington, Cambridgeshire, SG8 0SS, UK
tel: +44 (0)1223 858890    mobile: +44 (0)7595 099165    fax: +44 (0)1223 853667
email: mark@cresset-group.com<mailto:mark@cresset-group.com>    web: www.cresset-group.com<http://www.cresset-group.com/>    skype: mark_cresset

**Comment by mark-cresset** [comment]
OK, I think I’ve managed to track this down. It might be my misunderstanding of HTML syntax that’s the problem. We’re reading the SDF data from a textarea within the document. Our HTML framework was emitting

<textarea id=”moldata”>Title_line
SDF_data_line
Comment_line
#atoms #bonds etc…
…
</textarea>

which works fine, _unless_ the title line is empty. If I change this to

<textarea id=”moldata>
Title_line
SDF_data_line
Comment_line
#atoms #bonds etc…
…
</textarea>

then all is well. I don’t remember seeing any HTML specifications on whether a newline immediately after the <textarea> tag is included in the textarea data, but I’m far from being an expert.

Anyway, it looks like including a newline after the textarea tag and before the SDF data starts fixes this, so it’s probably a HTML/Javascript bug/oddity, rather than being a bug in 3dmol?

Regards,
Mark

--
Mark Mackey
Chief Scientific Officer
Cresset
New Cambridge House, Bassingbourn Road, Litlington, Cambridgeshire, SG8 0SS, UK
tel: +44 (0)1223 858890    mobile: +44 (0)7595 099165    fax: +44 (0)1223 853667
email: mark@cresset-group.com<mailto:mark@cresset-group.com>    web: www.cresset-group.com<http://www.cresset-group.com/>    skype: mark_cresset

**Comment by dkoes** [comment]
Yup, and, if you're lucky, it's an HTML oddity that is consistent across browsers...
