### ISSUE TITLE
Problem with opening a PDB-format file

### ISSUE THREAD

**Issue by rkiminsilico** [3dmol/3Dmol.js#345]
A PDB-format file (https://drive.google.com/file/d/0B0x59qdP62X1aTFVZFVLMWNlazA/view?usp=sharing) does open with an embedded 3Dmol at http://www.cravat.us/MuPIT_Interactive/?gene=prune2 (the file is served from the inside the server. The Google drive file is just for anyone to see get the file). If line 9900 "ATOM   9871  CA  GLU  1300      44.735  45.565  31.537  1.00 64.41           C" is removed from the file, the same embedded 3Dmol opens it without a problem. Can you shed a light on this phenomenon?

**Comment by dkoes** [comment]
Sending links to localhost isn't very helpful.  Can you please provide the actual file?

**Comment by rkiminsilico** [comment]
Sorry, I didn't notice it. I changed the links in the post to Google drive and public server ones.

**Comment by dkoes** [comment]
I can't reproduce this using this html:
```
<html>
<head>
     <script src="../build/3Dmol.js"></script> </head>    
<title>Test DIV</title></head>
<body>
     <div style="height: 400px; width: 400px; position: relative;" 
     class='viewer_3Dmoljs' data-href='ENSP00000389706_2.pdb' 
     data-style='cartoon'
     data-backgroundcolor='0xffffff' 
     ></div>

</body>
</html>
```
It loads just fine.  Are you using the latest version?  Can you provide the exact style specifications you are using?

**Comment by rkiminsilico** [comment]
With the latest version, the error is gone it seems. Thanks for having looked at it.
