### ISSUE TITLE
ligands not rendered

### ISSUE THREAD

**Issue by mbsimonovic** [3dmol/3Dmol.js#347]
is it possible to have ligands rendered? when i try pdb:1I1Q 

        var viewer = $3Dmol.createViewer($("#3dviwer"));
	$3Dmol.download("pdb:1i1q",viewer,{multimodel:true, frames:true},
		function(){
		viewer.setStyle({}, {cartoon:{color:"spectrum"}});
		viewer.addStyle({chain:'A'},{cartoon:{color:"red"}});
		viewer.addStyle({chain:'B'},{cartoon:{color:"blue"}});
		viewer.render();
	});

it doesnt render them:

<img width="797" alt="screen shot 2017-10-31 at 23 00 12" src="https://user-images.githubusercontent.com/888008/32251011-6198803a-be8f-11e7-9a14-cfcab57fcf70.png">

here's how [ngl](http://www.rcsb.org/pdb/ngl/ngl.do?pdbid=1I1Q&bionumber=1) renders it:

<img width="414" alt="screen shot 2017-10-31 at 23 02 43" src="https://user-images.githubusercontent.com/888008/32251109-d833f0da-be8f-11e7-8907-44f5168221f7.png">

**Comment by dkoes** [comment]
This is the expected behavior. Ligands won't display in cartoon style.  You need to select the ligand and style it how you want.  For example:
```
viewer.addStyle({hetflag:true},{sphere:{colorScheme:"greenCarbon"}});
```

**Comment by mbsimonovic** [comment]
hetflag: true seems to select water molecules, but not ligands. Is there something like {ligand: '[TRP](http://www.rcsb.org/pdb/ligand/ligandsummary.do?hetId=TRP&sid=1I1Q)'} ?

**Comment by dkoes** [comment]
hetflag: true will select everything in the pdb that is marked as a hetatm.  You can select by the residue number (resi) or name (resn).  You can also exclude the water molecules by excluding molecules with "bonds: 0".

**Comment by mbsimonovic** [comment]
got it, thanks.

**Comment by mbsimonovic** [comment]
is it posible to have hetatm transparent? setting opacity on them doesn't seem to work..

**Comment by dkoes** [comment]
Do you have an example of it not working? It works fine for me:
http://3dmol.csb.pitt.edu/tests/auto/generate_test.cgi?test=test98

Note that transparent objects are not transparent with respect to one another.

**Comment by mbsimonovic** [comment]
yes, just change your example from _sphere_ to _stick_:

        viewer.setStyle({hetflag:true},{stick:{opacity:0.8}});

**Comment by mbsimonovic** [comment]
one more question, is it possible to show all hetero atoms excluding water by just using a selection? Currently i do it using a predicate function:

		viewer.addStyle({hetflag:true,predicate: a => a.resn != 'HOH'},{sphere:{opacity:0.75}});

**Comment by dkoes** [comment]
Apparently I'd never gotten around to implementing stick transparency.  It's fixed now.

You can use boolean selectors:
`{and:[{hetflag:true},{not:{resn:'HOH'}}]}`
Unfortunately, it looks like these weren't documented, so I've added them to the AtomSelectionSpec documentation.

Examples here:
http://3dmol.csb.pitt.edu/tests/auto/generate_test.cgi?test=test98
