### ISSUE TITLE
How to zoom out (Mouse wheel)

### ISSUE THREAD

**Issue by xploregopi** [3dmol/3Dmol.js#348]
Hi Friends,

 I tried the below line,
viewer.zoom({factor:2});

and also zoomTo() function disabled but still it's working.

**Comment by dkoes** [comment]
Can you explain more clearly what the problem is, preferably with a small test case?

I have no trouble zooming with the mouse wheel.  To zoom by a constant factor, pass that factor as an argument (`viewer.zoom(2)`).  How can zoomTo be disabled but working?

**Comment by xploregopi** [comment]
I don't want mouse wheel scroll zoom option. Any suggestion?

**Comment by xploregopi** [comment]
I comment the zoomTo() also but still zooming(Mouse wheel scroll)

**Comment by dkoes** [comment]
If you want to disable all mouse control you can set `nomouse: true` in the viewer configuration object.  Otherwise you'd need to manually remove the event listeners from the `canvas` object.
