### ISSUE TITLE
Click handling broken on sphere styles

### ISSUE THREAD

**Issue by kmoad** [3dmol/3Dmol.js#349]
I have a function set up to show atom labels on click. It works when the atoms are represented as cartoon, stick, or line, but fails on spheres. A look at the atom objects shows that spheres are not being added to the intersection shapes. The click raycast seems to be passing through the spheres and the click is handles by whatever other-styles atom is below.

Problem can be seen at mupit.icm.jhu.edu

**Comment by dkoes** [comment]
I can't find any problems with spheres.  I did find some problems with sticks.  Both are working now:
http://3dmol.csb.pitt.edu/tests/auto/generate_test.cgi?test=glviewer_js_setHoverable
http://3dmol.csb.pitt.edu/tests/auto/generate_test.cgi?test=glviewer_js_setClickable

Can you provide a test case where it isn't working?

**Comment by kmoad** [comment]
Looks like that update fixed things on our end. Thanks!
