### ISSUE TITLE
Feature: limit zoom

### ISSUE THREAD

**Issue by mbsimonovic** [3dmol/3Dmol.js#350]
Would you perhaps consider putting upper and lower limits to zoom? Currently it can zoom out indefinitely, so it's not even visible on the screen, and that doesn't seem very useful nor user-friendly. Putting a limit doesn't require many code changes, it all would probably end up in _handleMouseScroll:

```
            var newZ = 0;
            if (ev.originalEvent.detail) { // Webkit
                newZ = rotationGroup.position.z + mult * scaleFactor
                        * ev.originalEvent.detail / 10;
            } else if (ev.originalEvent.wheelDelta) { // Firefox
                newZ = rotationGroup.position.z - mult * scaleFactor
                        * ev.originalEvent.wheelDelta / 400;
            }
            if(newZ > CAMERA_Z) newZ = CAMERA_Z*0.999; //avoid getting stuck
            //setLabelStyles(scaleFactor/originalPosition);
            if (config.lowerZoomLimit && 
                        (newZ < config.lowerZoomLimit || newZ > config.upperZoomLimit)) {
		return;
            }
            rotationGroup.position.z = newZ;
```
p.s.  this line `if (ev.originalEvent.detail) { // Webkit` is false and `} else if (ev.originalEvent.wheelDelta) { // Firefox` is true on Chrome, so the comment is misleading.

**Comment by dkoes** [comment]
Implemented:
http://3dmol.csb.pitt.edu/doc/$3Dmol.GLViewer.html#setZoomLimits
