### ISSUE TITLE
py3dmol: resolution issue with view.png() command

### ISSUE THREAD

**Issue by eguarnera** [3dmol/3Dmol.js#354]
Hi there,

Since I did the upgrade to the version 7.0.0 I have noticed that the command view.png() produces lower resolution images. As also other updates were involving iPython and Jupiter perhaps this change in the resolution has nothing to do with the change of version in py3dmol. Any suggestion to increase the resolution of the png() command?

Best,
Enrico

**Comment by dkoes** [comment]
It should be equal to the size of the viewer (unless you have a "retina" display, in which case it would be 2x).  You can set the size of the viewer to be larger when you create it.
