### ISSUE TITLE
[feature request] visibility of GLShape

### ISSUE THREAD

**Issue by jksr** [3dmol/3Dmol.js#355]
Is there a way to set some GLShapes invisible so that the viewer needs not render them?
In this way GLShapes can be buffered, and there is no need to calculate when they are needed again.
And maybe a new addShape() function will be needed in this case, for the current one only accept addShape(ShapeSpec)

**Comment by dkoes** [comment]
You can do this with updateStyle by setting `hidden: true` in the ShapeSpec object.  The hidden flag wasn't documented, so I fixed that. d4d68a0eee11e57f8ced4a5103baa008c9d86a4f
