### ISSUE TITLE
add GLViewer.addCuboid()

### ISSUE THREAD

**Issue by tlafarge** [3dmol/3Dmol.js#358]
Hi I'm wondering if there is an easy way that would make the viewer draw a cuboid, (rectangle in 3d) 
defined by 4 vertices.

It looks like it should be possible by defining a new isosurface or a mesh but maybe the tool could benefit from a more user-friendly function similar to addSphere() or addline().

Thank you.

**Comment by dkoes** [comment]
A flat rectangle doesn't seem useful enough to justify a built-in method.  It's fairly straightforward to use `addCustom` to create a rectangle.  

What is the use case?

**Comment by tlafarge** [comment]
Not a flat one, a 3d one, a box if you will. Sound like a common enough occurrence to have a dedicated method.

**Comment by dkoes** [comment]
I've never felt a need for a box.   The use case matters, since we would want to have the cleanest api for the most common usage.  For example, if the most common usage is an axis aligned cube, you only need to define a center and a radius, whereas if you want to support any arbitrary shape with 8 corners, you would need to specify all 8 corners.   I'm curious how you want to use it?

**Comment by tlafarge** [comment]
In my case it is to display a scene compose of spheres and boxes.
The sphere are defined with a radius and center and the boxes are defined by 4 points (non coplanar).

In my case the ideal function would be a 
      viewer.addBox taking 4 non coplanar vertices

 Would you consider adding such a function?

In the meantime I am trying to go around it using custom spec but I have a problem with the normal and the lightning. assuming a regular box defined by 4 (or 8) given vertices what value should a give to the normal of the vertices?

**Comment by dkoes** [comment]
I've created addBox functionality (http://3dmol.csb.pitt.edu/tests/auto/generate_test.cgi?test=glshape_js_addBox)

You specify a corner of the box and its dimensions. The dimensions can be scalars (resulting in an axis aligned box) or vectors.

**Comment by tlafarge** [comment]
Sounds perfect I''l check it out.
