### ISSUE TITLE
GSOC application

### ISSUE THREAD

**Issue by migom6** [3dmol/3Dmol.js#361]
Hey @dkoes ,
I am Madhurjya Pegu from Indian Institute of Information Technology Allahabad. I am interested in contributing towards this project for Google Summer Of Code 2018. I would like to build a VR library for the existing code base, also the synchronized classroom guide is really interesting. Should I make a draft for the proposal so that you can review or should I directly submit to the GSOC portal? Also any tips for head start?
Thanks 😄

**Comment by dkoes** [comment]
Yes, the GSoC portal is the appropriate venue.  For VR the goal is to adapt the existing code to correctly display split views and respond to deviceorientation events.  A proposal for the "synchronized classroom guide" should clearly indicate the architecture of the solution.
