### ISSUE TITLE
py3Dmol not compatible with jupyterlab

### ISSUE THREAD

**Issue by mcs07** [3dmol/3Dmol.js#362]
The new jupyterlab interface for jupyter notebooks seems to be more strict about injecting arbitrary javascript into a notebook, for security reasons. As a result, py3Dmol outputs don't appear.

The recommended solution is to make a "jupyterlab extension". The bokeh extension might be a good example of how to do this:

- https://github.com/bokeh/jupyterlab_bokeh
- https://github.com/bokeh/bokeh/issues/6700
- https://github.com/jupyterlab/jupyterlab/issues/3118

**Comment by mcs07** [comment]
@cjh1 and @cryos work might also be relevant:

- https://github.com/OpenChemistry/jupyterlab_cjson
- https://blog.kitware.com/open-chemistry-in-jupyterlab/

**Comment by dkoes** [comment]
Bugger.

**Comment by cryos** [comment]
A very British response :smile:. We have been working on JupyterLab integration using 3DMol.js, if the project this is linked to goes ahead we were planning on rewriting what we have to be more flexible, and would gladly contribute it where it could be of most use to the most people.

**Comment by dkoes** [comment]
My guess is we need a separate py3Dmol extension for JupyterLab integration.  It would be fantastic if someone could contribute.  However, it isn't clear to me if extension would let you save a notebook to html with the 3Dmol javascript intact, which is a hard design requirement for me.

**Comment by mcs07** [comment]
Yeah, I think a separate "jupyterlab_py3dmol" package will be needed on npm.

As for the static HTML export, this seems to be possible - I did a quick test with jupyterlab_bokeh and it seems able to produce output that works both in the jupyterlab interface and after exporting as HTML.

**Comment by cryos** [comment]
So we are using https://github.com/OpenChemistry/molecule-3d-for-react but would like to create something a little more general/robust. We share the goal of saving to HTML, but I don't think that works for the 3D molecule just yet (I know Chris did some work in that area though).

**Comment by dkoes** [comment]
I just finished implementing this in my plane is about to land so I don't have time to test it much, but I've added support for JupyterLab.  You must update to 0.7 of py3Dmol and install the extension:

`jupyter labextension install jupyterlab_3dmol
`

Let me know how it works.

**Comment by mcs07** [comment]
Fantastic! I just did a quick test with the example notebook and it seems to work well.

**Comment by scottwsides** [comment]
mcs07... what version of jupyterlab worked for you with the 3dmol extension?

**Comment by anuprulez** [comment]
I am using Jupyterlab 3.6.5 along with Colabfold 1.2.0. The compatible version of py3Dmol is 1.8.1 but unfortunately, it does not work for showing the 3D structure of proteins and asks me to install `jupyter labextension install jupyterlab_3dmol`. 

But when I aggressively installed `py3Dmol==2.0.0.post2` via pip after installing Colabfold, the 3D structure is shown nicely, and there was no need to do `labextension` install of `jupyterlab_3dmol` package.

**Comment by dkoes** [comment]
Glad you got it to work, although I routinely pip install py3Dmol on colab with no problems, so I don't know why you are having to set versions.
