### ISSUE TITLE
Bug of ray intersection in orthographic mode

### ISSUE THREAD

**Issue by crane-may** [3dmol/3Dmol.js#364]
I use orthographic mode with `viewer.setProjection('orthographic')`, and click detection is inaccurate.
Example is here: [https://jsfiddle.net/kg9wsynn/11/](https://jsfiddle.net/kg9wsynn/11/)

**Comment by dkoes** [comment]
Please verify that my last commit, 18818bc50cc22906ca5cf3fab2d820924b3368b1, fixes the problem.

**Comment by dkoes** [comment]
This fix is now included in 1.3.3.

**Comment by crane-may** [comment]
Cool, thx! 👍
