### ISSUE TITLE
view.png() upside down

### ISSUE THREAD

**Issue by eguarnera** [3dmol/3Dmol.js#365]
![image](https://user-images.githubusercontent.com/8078280/38420499-3529804a-39a4-11e8-9c55-1cf6f6e0d946.png)

Hi there,

Any hint on why my view.png() image is upside down? see attached

Best,
Enrico

**Comment by dkoes** [comment]
That's a new one.  What operating system/browser?  Does the problem replicate in other browsers?

**Comment by eguarnera** [comment]
Hi,

it's on a mac sierra 10.13.4 and Safari. It actually works normally on chrome.

**Comment by dkoes** [comment]
This appears to be a bug in Safari (https://stackoverflow.com/questions/31082912/canvaselement-todataurl-for-webgl-canvases).  It is possible to work around it, but it requires adding a bunch of grubby code that would be unique to Safari (which might then start flipping the image unnecessarily if Apple ever fixes the bug).  How important is this feature?

**Comment by eguarnera** [comment]
Not really important. I just realized that because I've been working with Safari lately, I can just go back to Chrome. Thanks!

**Comment by K7S3** [comment]
@dkoes Since this not an issue of 3dmol on its own, I think it is better to close it and have a compatibility file which mentions which browsers 3Dmol.js supports.
