### ISSUE TITLE
Include license file in py3Dmol distribution

### ISSUE THREAD

**Issue by mcs07** [3dmol/3Dmol.js#369]
The py3Dmol README says that it is licensed under the MIT license (as opposed to the BSD license for 3Dmol.js as a whole) but the license is not actually present.

Would it be possible to include a copy of the MIT license as a `LICENSE` file in the py3Dmol directory, and also to add `include LICENSE` to `MANIFEST.in` so it is included in the source distribution on PyPI?

**Comment by mcs07** [comment]
By the way, there seems to be some issues with the files on PyPI for v0.7.1... the source distribution appears to have a very specific platform restriction (`macosx-10.13-x86_64`, I've never seen this before?) and also there is an egg file just for python 2.7:
https://pypi.org/project/py3Dmol/0.7.1/#files

The source dist and wheel file look completely fine for v0.7.0, apart from the fact that the wheel is from September 2017 and the source is from March 2018:
https://pypi.org/project/py3Dmol/0.7.0/#files

**Comment by dkoes** [comment]
Okay, should be fixed now.
