### ISSUE TITLE
Problem in the PDB visualization 

### ISSUE THREAD

**Issue by dcbmariano** [3dmol/3Dmol.js#370]
Hi, I am trying to load a PDB, but this bug appears (PDB ID: 5cg0). How to solve this?
![image](https://user-images.githubusercontent.com/3708360/39945129-abe80f38-553f-11e8-8a3b-34006f9efb39.png)

Thanks.

**Comment by dkoes** [comment]
Can you explain how you are generating that?  5cg0 looks fine here:
http://3dmol.csb.pitt.edu/viewer.html?pdb=5cg0&select=all&style=cartoon;stick
