### ISSUE TITLE
better boolean selection operators

### ISSUE THREAD

**Issue by dkoes** [3dmol/3Dmol.js#371]
within doesn't work inside of and/or.  Should change these to get the set of atoms selected rather than calling atomIsSelected on each atom.

**Comment by bistaastha** [comment]
Hi @dkoes! I want to understand 3Dmol.js better and this shows up as a good first issue. Can I look into this?

**Comment by dkoes** [comment]
Sure, start by writing a test case.

**Comment by bistaastha** [comment]
Hi @dkoes ! I tried to write a test case for `atomIsSelected`. However, I am not able to figure out how to define [AtomSpec](https://3dmol.csb.pitt.edu/doc/types.html#AtomSpec) and [AtomSelectionSpec](https://3dmol.csb.pitt.edu/doc/types.html#AtomSelectionSpec). Is there a way to define their properties without $3Dmol.download?

**Comment by dkoes** [comment]
Here are examples of using within:
http://3dmol.csb.pitt.edu/tests/auto/generate_test.cgi?test=test18
http://3dmol.csb.pitt.edu/tests/auto/generate_test.cgi?test=testComplexSelection

Here an example of using boolean selectors:
http://3dmol.csb.pitt.edu/tests/auto/generate_test.cgi?test=test71

**Comment by bistaastha** [comment]
@dkoes Thanks! I was actually working on a QUnit test for this :woman_facepalming: . Seems like I got that wrong.

**Comment by bistaastha** [comment]
@dkoes Is there a way to build these tests locally?

**Comment by dkoes** [comment]
npm install 3dmol.js and then configure your local webserver to read from the 3dmol.js directory.
