### ISSUE TITLE
ligand style

### ISSUE THREAD

**Issue by aldosc** [3dmol/3Dmol.js#378]
Hi 3Dmol team,

I'm working on a notebook and using py3Dmol for visualizing the structure of some ligands.
Everything is working fine, but I'd like to get a visualization similar to the one displaying the aromatic and hydrogen donor properties in the main website: http://3dmol.csb.pitt.edu/
Would you share what style/parameters shoul be used to obtain something similar? 

Thanks!

**Comment by dkoes** [comment]
Those are sphere objects with a wireframe style:
`viewer.addSphere({center:{x:0,y:0,z:0},radius:2.0,color:'red',wireframe:true});`
