### ISSUE TITLE
Mouse events (hover / click) for surfaces?

### ISSUE THREAD

**Issue by dbryanbio** [3dmol/3Dmol.js#381]
I believe mouse events on surfaces are not currently supported as such.  Is this on your roadmap at all?  

With a small change to add/removeSurface, I can ensure that the surface reference atoms have an intersection sphere, so they generate mouse events (even if hidden).  However, it would be nice if I didn't have to modify 3dmol.  Is there a better way to do this?

Feel free to close this if the answer is no.
Thanks!

**Comment by dkoes** [comment]
We could have every triangle in the surface be tested for intersecting the mouse, but I don't think this would scale very well.  One alternative I was thinking about was having the ability for click/hover testing to be performed on hidden atoms.  So you would have hidden atom spheres that are only their for interpreting mouse events (can't see them).  Would that have the desired effect?

**Comment by dbryanbio** [comment]
Yes! That is what I did to make it work.  However, we don't always want hidden atoms to generate mouse events.  Could it be that a "pseudo-clickable" property in the surface spec instructs the hidden reference atoms to provide an intersection shape?

**Comment by dbryanbio** [comment]
As I thought about it more, I realized our purposes are better served by using the underlying atoms, rather than monolithic mouse events which apply to the whole surface.  We need to display different data depending on which area of the surface you are interacting with.

**Comment by dkoes** [comment]
For the hidden atoms you don't want to respond to mouse events, you wouldn't set the clickable/hoverable attributes...

**Comment by dbryanbio** [comment]
In our application, we have zoomed-out and zoomed-in views and in either case the protein can be viewed as lines, sticks, spheres, cartoon, or surface.  All visible atoms have mouse click and hover behavior.

In zoomed-in line/stick/sphere/cartoon view, only the visible atoms should be clickable and hoverable - not hidden atoms from other parts of the structure.
In the zoomed-in surface view, most of the atoms in the system (maybe all) will be hidden, but we'd want the atoms related to the surface to respond to the mouse events.

**Comment by dkoes** [comment]
So what if we had a 'clicksphere' style which displayed nothing but enabled click/hover events for the associated atoms.  Would that serve your purpose?

**Comment by dbryanbio** [comment]
Yes, that should work.  When we display the surface, we'll put the reference atoms in clicksphere.
Thanks, Doug!

**Comment by dkoes** [comment]
Okay, this is implemented.

http://3dmol.csb.pitt.edu/tests/auto/generate_test.cgi?test=clicksphere

4c9ec610df6212ed5b6fcb0cc84c910e53d45243
