### ISSUE TITLE
Direct support for AtomSpec-formatted input data.

### ISSUE THREAD

**Issue by asford** [3dmol/3Dmol.js#382]
It would be useful, particularly when using py3dmol in jupyter notebooks, to be able to provide fully structured input data to 3dmol. This would enable client applications to directly construct 3dmol's preferred data format, which is both more expressive and more efficient than than serializing into an alternate (PDB/cdjson/...) format. 

I *believe*, from looking through `glmodel.js` and `parsers.js`,, this could be accomplished by adding a single parser "passthrough" parser to `parsers.js` which would (at most) call `JSON.parse` on incoming string data. The client would then be responsible for providing the list-of-AtomSpec-lists that's expected by `3dmol`.

**Comment by dkoes** [comment]
I think you could use addAtoms for this. http://3dmol.csb.pitt.edu/doc/$3Dmol.GLModel.html#addAtoms

**Comment by asford** [comment]
I agree, that's the proper solution when working within javascript. However when working with `py3Dmol` we only have access to the `GLViewer` api.

My instinct is that adding a pass-through data format option in the parsing layer would be preferable to expanding the `GLViewer` api with more pass-through functions to `GLModel`, though either implementation option would work. Do you have a preference?

**Comment by dkoes** [comment]
Huh.  I was sure I had added support for accessing models, but apparently I was delusional.  It's been added and a new release (0.8.0) created.  This will work now:
```
p = py3Dmol.view()
p.addModel()
p.getModel(0).addAtoms([{'elem':'C','x':0,'y':0,'z':0},{'elem':'C','x':1.5,'y':0,'z':0}])
p.setStyle({'sphere':{}})
p.zoomTo()
p.show()
```

**Comment by asford** [comment]
Great! Thanks for the quick update.
