### ISSUE TITLE
export vrml mesh file of entire scene

### ISSUE THREAD

**Issue by dkoes** [3dmol/3Dmol.js#384]
I'm thinking VRML would be best, obj doesn't have color, right?

**Comment by durrantlab** [comment]
Thanks so much for your help with this. I would definitely use this feature a lot. With OBJ, you have to create a separate MTL file for color information. I don't think you can embed color into the OBJ file itself: https://gamedev.stackexchange.com/questions/21303/how-can-i-include-vertex-color-information-in-obj-files

VRML should work fine for my purposes.

**Comment by ghutchis** [comment]
I hired an undergrad to implement color VRML export for Avogadro. The alternative seems to be PLY, which allows vertex colors (http://paulbourke.net/dataformats/ply/) Unfortunately, very few services support PLY.

I was looking at OBJ + MTL, but it seems a bit of a pain.

**Comment by durrantlab** [comment]
Here's code for PLY, though it only works for things like surfaces and cartoon. Blender supports PLY, FYI. The problem is I don't know how to access all the Geometry (or Mesh) objects in a given scene from outside $3Dmol.js, so I have to modify the $3Dmol.js source code itself.

`/**
 * A function to join the numbers in a Float32Array
 * @param  {Float32Array|Uint16Array} typedArr   The array.
 * @param  {int=}                     precision  The precision (number of
 *                                               decimal points).
 * @return {string} The numbers of typedArr, connected by spaces.
 */
var joinTypedArr = function(typedArr, precision=6) {
    var arr = Array.prototype.slice.call(typedArr)
    var sArr = arr.map(i => i.toFixed(precision));
    return sArr.join(" ");
}

/**
 * Makes a list of PLY-formatted strings from a $3Dmol.Geometry object. One
 * string for each geometry group.
 * @param  {$3Dmol.Geometry} geometry The geometry object.
 * @returns string[] A list of PLY-formatted strings.
 */
var makePLY = function(geometry) {
    // To keep track of the PLY-formatted strings
    plyStrings = [];

    // Go through each of the geometry groups.
    for (var geoGrpIdx=0; geoGrpIdx<geometry.geometryGroups.length; geoGrpIdx++) {
        // Define a few variables to simplify things.
        var geoGrp = geometry.geometryGroups[geoGrpIdx];

        // Create the PLY-file header.
        var plyTxt = "";
        plyTxt += "ply\n";
        plyTxt += "format ascii 1.0\n";
        plyTxt += "comment Created by 3DMol.js\n"
        plyTxt += "element vertex " + geoGrp.vertices.toFixed(0) + "\n";
        plyTxt += "property float x\n";
        plyTxt += "property float y\n";
        plyTxt += "property float z\n";
        plyTxt += "property float nx\n";
        plyTxt += "property float ny\n";
        plyTxt += "property float nz\n";
        plyTxt += "property uchar red\n";
        plyTxt += "property uchar green\n";
        plyTxt += "property uchar blue\n";
        plyTxt += "element face " + (geoGrp.faceidx/3).toFixed(0) + "\n";
        plyTxt += "property list uchar uint vertex_indices\n";
        plyTxt += "end_header\n";

        // Go through each of the verticies
        for (var vertIdx=0; vertIdx<3*geoGrp.vertices; vertIdx=vertIdx+3) {
            // Get the appropriate verts, norms, and colors.
            var vertCoors = geoGrp.vertexArray.slice(vertIdx, vertIdx+3);
            var norms = geoGrp.normalArray.slice(vertIdx, vertIdx+3);
            var colors = geoGrp.colorArray.slice(vertIdx, vertIdx+3);

            // Colors need to be scaled. Math.abs to fix rounding error (-0).
            colors = colors.map(i => Math.abs(255 * i));

            // Make the PLY line for this vertex.
            plyTxt += joinTypedArr(vertCoors) + " ";
            plyTxt += joinTypedArr(norms) + " ";
            plyTxt += joinTypedArr(colors, 0) + "\n";
        }

        // Go through each of the faces.
        for (var faceIdx=0; faceIdx<geoGrp.faceidx; faceIdx=faceIdx+3) {
            // Get the face vertex indecies.
            var faceVertIdxs = geoGrp.faceArray.slice(faceIdx, faceIdx+3);

            // Make the PLY line for this face. The 3 is because it's a
            // triangle.
            plyTxt += "3 " + joinTypedArr(faceVertIdxs, 0) + "\n"
        }

        plyStrings.push(plyTxt);
    }

    return plyStrings;
}
`

**Comment by dkoes** [comment]
Blah.  I thought this would be fairly quick but ended up spending most of the day on it.  However, it seems to work.  I've added a VRML button to the viewer for testing.  For example:
http://3dmol.csb.pitt.edu/viewer.html?pdb=4KW4&style=cartoon:color~spectrum;stick:radius~0.25,colorscheme~greenCarbon&select=bonds:0&style=sphere:radius~0.5

(click on the hamburger).

I've wanted this functionality to support 3d printing (pymol, surprisingly, has issues exporting usable vrml).

I need to think of how to write an automated test for this.  Let me know how it works for you.

**Comment by durrantlab** [comment]
Works great! The geometries of these meshes are much more ordered than what I've seen from VMD exports. There are many duplicate vertices, which makes the file bigger than necessary, but it's easy to remove duplicates in programs like MeshLab or Blender. I made this video to show what the meshes look like when imported into Blender: https://vimeo.com/303653638

Thanks so much for putting this together! It will be very useful for a project I'm working on.

**Comment by durrantlab** [comment]
I've been enjoying the new exportVRML(), but I found what I think might be a bug. After calling the function, I can no longer change the styles on the meshes. I'd appreciate any help you could offer to overcome this problem.

I put together some minimal code that replicates the issue, which I posted to https://durrantlab.bio.pitt.edu/tmp/test_3dmoljs_prob/

I'll put the code here, too, in case it helps:

```
<!doctype html>

<html lang="en">
    <head>
        <title>3DMol.js Test</title>
        <style>
            .mol-container {
                width: 60%;
                height: 400px;
                position: relative;
            }
        </style>
    </head>
        <div class="mol-container"></div>

        <script src="jquery-3.2.1.min.js"></script>
        <script src="3Dmol-nojquery.min.js"></script>

        <script>
            $(function() {
                let element = $(".mol-container");
                let config = {backgroundColor: "white"};
                let viewer = $3Dmol.createViewer(element, config);

                alert("I'll now load a small molecule and give it a stick representation.");

                data = "HETATM 2364  C1 A1BO A 501       9.103  27.061  27.339  0.50 40.13           C  \n";
                data += "HETATM 2365  C2 A1BO A 501       8.290  25.757  27.249  0.50 40.25           C  \n";
                data += "HETATM 2366  C3 A1BO A 501       8.877  24.861  26.140  0.50 40.02           C  \n";
                data += "HETATM 2367  C4 A1BO A 501       7.814  24.631  25.053  0.50 40.18           C  \n";
                data += "HETATM 2368  OH A1BO A 501       7.249  23.322  25.194  0.50 40.25           O  ";

                var model = viewer.addModel(data, "pdb");

                model.setStyle(
                    {},
                    {
                        "stick": {
                            "colorscheme": "default",
                            "hidden": false,
                            "radius": 0.3,
                        },
                        "line": {
                            "hidden": true
                        }
                    },
                    true
                );

                viewer.zoomTo();
                viewer.render();

                setTimeout(() => {
                    alert("I'll now hide that molecule. It will work fine.");

                    model.setStyle(
                        {},
                        {"stick": {
                            "hidden": true,
                        }},
                        true
                    );

                    viewer.zoomTo();
                    viewer.render();

                    setTimeout(() => {
                        alert("Now I'll show it again, and display the output of exportVRML() in the console.");

                        model.setStyle(
                            {},
                            {"stick": {
                                "hidden": false,
                            }},
                            true
                        );

                        viewer.zoomTo();
                        viewer.render();

                        var txt = viewer.exportVRML();
                        console.log(txt);

                        setTimeout(() => {
                            alert("I'll now try to hide it. It won't work, because I've called exportVRML().");
                            model.setStyle(
                                {},
                                {"stick": {
                                    "hidden": true,
                                }},
                                true
                            );

                            viewer.zoomTo();
                            viewer.render();

                        }, 1000);
                    }, 1000);
                }, 1000);

                // viewer.zoom(0.8, 2000);
            });
        </script>
    </body>
</html>
```
Thanks!

**Comment by dkoes** [comment]
Fixed. ced8b4d775efdc5d0b1de79802fae058f9d89554

We do some trickery to re-render without imposters when generating VRML and I wasn't being careful enough about clearing out cached objects.

**Comment by durrantlab** [comment]
Hi David. So sorry to keep bringing this up. :) I'm having a new problem now. I built the library with your changes, but now the VRML is empty. Here's some minimal code that reproduces the error: https://durrantlab.bio.pitt.edu/tmp/test_3dmoljs_prob.v2/

```
<!doctype html>

<html lang="en">
    <head>
        <title>3DMol.js Test</title>
        <style>
            .mol-container {
                width: 60%;
                height: 400px;
                position: relative;
            }
        </style>
    </head>
        <div class="mol-container"></div>

        <script src="jquery-3.2.1.min.js"></script>
        <script src="3Dmol-nojquery.js"></script>

        <script>
            $(function() {
                let element = $(".mol-container");
                let config = {backgroundColor: "white"};
                let viewer = $3Dmol.createViewer(element, config);

                data = "HETATM 2364  C1 A1BO A 501       9.103  27.061  27.339  0.50 40.13           C  \n";
                data += "HETATM 2365  C2 A1BO A 501       8.290  25.757  27.249  0.50 40.25           C  \n";
                data += "HETATM 2366  C3 A1BO A 501       8.877  24.861  26.140  0.50 40.02           C  \n";
                data += "HETATM 2367  C4 A1BO A 501       7.814  24.631  25.053  0.50 40.18           C  \n";
                data += "HETATM 2368  OH A1BO A 501       7.249  23.322  25.194  0.50 40.25           O  ";

                var model = viewer.addModel(data, "pdb");

                model.setStyle(
                    {},
                    {
                        "stick": {
                            "colorscheme": "default",
                            "hidden": false,
                            "radius": 0.3,
                        },
                        "line": {
                            "hidden": true
                        }
                    },
                    true
                );

                viewer.zoomTo();
                viewer.render();

                setTimeout(() => {
                    alert("I'll now call viewer.exportVRML() and will write the output to the console.");

                    var txt = viewer.exportVRML();
                    console.log(txt);

                    viewer.zoomTo();
                    viewer.render();

                    setTimeout(() => {
                        alert("Interestingly, the model disappears until I call viewer.render(). That's fine, but the VRML is empty (see console).");

                    }, 1000);
                });
            });
        </script>
    </body>
</html>
```

The VRML is empty (see the search console):

```
#VRML V2.0 utf8
 Transform {
  center 0 0 0
  rotation 0 0 0 0
  children [
 ]
}
```

Thanks.

**Comment by dkoes** [comment]
I'm an idiot.
d47e7c759a55ee266845edab8a366d76102481ea
swaps the order of two lines to fix the problem.
