### ISSUE TITLE
Typo in glmodel.js: midpoint is labeled mp1 in the var declaration, but referenced as mp3.

### ISSUE THREAD

**Issue by dbryanbio** [3dmol/3Dmol.js#385]
Typo in glmodel.js: midpoint is labeled mp1 in the var declaration, but referenced as mp3.

Should I check it into a branch and send a pull request?

**Comment by dkoes** [comment]
Is the only issue pollution of the global namespace?  If so, I think this will fix it: 62882d45f7156d19fff74ddf6d8d8a96a8bad011

**Comment by dbryanbio** [comment]
A few weeks ago I saw some unknown variable errors in certain cases...more recently it has handled it ok, and I don't remember the specific scenario for the error.  Yes, that fix should do it, thanks.
