### ISSUE TITLE
Problem with uploading mmtf file

### ISSUE THREAD

**Issue by pilare** [3dmol/3Dmol.js#387]
I'm having issues with using addModel function with mmtf files downloaded from mmtf.rcsb.org. It works for me perfectly with any other formats: pdb, cif, sdf, mol2 and mmcif. 
Here is what I'm trying to do:
`viewer.addModel(window.atob(file.content_as_base64), 'mmtf')`
or
`viewer.addModel(file.content_as_base64, 'mmtf')`

I'm always getting this error:

**Uncaught ReferenceError: MMTF is not defined
    at b.mmtf.b.MMTF (3Dmol-min.js:776)**

Is there something missing that I need to run previously? Additional parsing? Do I need to pass it as Uint8Array instead?
I've noticed that there is no tests that are using mmtf files in 3Dmol.js

**Comment by dkoes** [comment]
If the data is passed as a string it should be base64 (http://3dmol.csb.pitt.edu/tests/auto/generate_test.cgi?test=testMMTFstring) otherwise it is treated as binary data, but that error looks like the MMTF module is missing.
Can you provide the error with a non-minified js?  Did you build this yourself or is it from 3dmol.csb.pitt.edu?

**Comment by pilare** [comment]
Thank you @dkoes for quick response. I'm using if from npm repository imported into react project. What I'm getting is:

```
3Dmol.js:39938 Uncaught ReferenceError: MMTF is not defined
    at $3Dmol.Parsers.parsers.mmtf.parsers.MMTF (3Dmol.js:39938)

```

line 39938:
       var mmtfData = MMTF.decode( bindata );

In parsers.mmtf function. This time I'm using unminified 3Dmol.js form build folder. I can see that there is a module with MMTF function but the way the declaration and the way it is exposed it's puzzling to me. I need to find out more time to find out how it suppose to work.

**Comment by pilare** [comment]
We are using react and webpack with babel-loader. To get $3Dmol import statement is used but with require statement I'm getting exactly the same problem.
`import $3Dmol from '3dmol'`
or to use unminified file:
`import $3Dmol from '3dmol/build/3Dmol.js'`
otherwise  I can use require:
`const $3Dmol = require('3dmol/build/3Dmol.js')`

All of them giving me the same problem.

When debugging it seems there is no access to **global** when setting up MMTF:
`  (factory((global['MMTF'] = global.MMTF || {})));`

All other file types and features works perfect in the app.

I've noticed there is a react wrapper for 3Dmol, but I'm not sure If that would help with that problem, and it seems not to be active repository anymore. And for me it would mean I need to refactor the code that works perfectly for most of use cases.
https://github.com/Autodesk/molecule-3d-for-react

**Comment by dkoes** [comment]
`global` is whatever `this` is when the script is run.  Typically thats the window (global) object and the rest of the library assumes that MMTF (and netcdfjs and pako, which are the other external dependencies) are loaded into the global namespace.

Without a reduced test case of your environment, I don't know why these aren't getting loaded at the global scope.

If you just want to get it working, you could try replacing `this` with `window` or just bypassing import/require and include the 3Dmol javascript directly.

**Comment by pilare** [comment]
I understand, @dkoes thank you for all your feedback. I'll try to recreate our environment for public test case. I just need to find time for that.

**Comment by dkoes** [comment]
Please try out version 2.0 as we've changed bundlers and it would be great to know it works in your setup.
