### ISSUE TITLE
Protein alignments?

### ISSUE THREAD

**Issue by rayoub** [3dmol/3Dmol.js#388]
Is there a way to visualize a protein alignment with 3d mol?

**Comment by dkoes** [comment]
What sort of input files and visualization do you have in mind?

**Comment by dkoes** [comment]
Generally I like to keep 3Dmol focused on visualization.  You will need to use another tool to generate an alignment.  For example, you could use prody:
http://mscbio2025.csb.pitt.edu/notes/prody1.slides.html#/39
