### ISSUE TITLE
Position of labels

### ISSUE THREAD

**Issue by drc007** [3dmol/3Dmol.js#391]
Is there a good way to work out the coordinates for labels? Other than trial and error?

viewer.addLabel("Hydrogen Donor", {position: {x:-5.4217, y:-0.4795, z:0.6395}, backgroundColor: 0x808080, backgroundOpacity:0.8});

**Comment by dkoes** [comment]
Would setting the alignment property help?
http://3dmol.csb.pitt.edu/doc/types.html#LabelSpec

**Comment by drc007** [comment]
I don't think so. I ended up just trying values to manipulate the table to the correct position in space.

**Comment by dkoes** [comment]
But what makes the preferred position the right position?

**Comment by drc007** [comment]
I actually want to put a label on a binding pocket.

**Comment by drc007** [comment]
At the moment I manually edit the x,y,z coordinates and view the results, I then manipulate the x,y,z coordinates to get the label into the desired position. Close to the identified pocket, but not obscuring key features when it is first displayed.

**Comment by dkoes** [comment]
But what sort of api do you envision that would make this process easier?

**Comment by drc007** [comment]
I don't know, I was just worried I might have missed something.
