### ISSUE TITLE
Change default zoom state of PDB file

### ISSUE THREAD

**Issue by nvelden** [3dmol/3Dmol.js#392]
I embedded the viewer on my webpage to load a local PDB file.  My molecule looks tiny and I every time need to zoom in to see anything. How do I change the default zoom state of the molecule? I tried to zoom into the molecule with PyMOL and then save the zoomedmolecule to a  PDB  but this does not work.

**Comment by dkoes** [comment]
The embedded viewer should call zoomTo, which should zoom in the required amount so the molecule fills the viewer.  Most likely your molecule has some atoms that are far away from the main molecule.  Can you provide a sample file?

**Comment by nvelden** [comment]
Unfortunately I am not allowed to give the structure but what if you for instance want to by default zoom into the binding site? Would there be anyway to do this?

**Comment by dkoes** [comment]
There wasn't, but adding zoomto support for the embedded viewer was simple enough for me to do while eating my lunch.  I've pushed an update so you can specify a zoomto selection with a data-zoomto field.  
 http://3dmol.csb.pitt.edu/tests/auto/generate_test.cgi?test=embed_zoomto

1f7f7898f977615677cdcb53679fafe34432ef6e

**Comment by nvelden** [comment]
Amazing. This is very handy. Looking forward to try it out!
