### ISSUE TITLE
data-zoomto not working in Firefox

### ISSUE THREAD

**Issue by nvelden** [3dmol/3Dmol.js#393]
Thanks a lot for the awesome new feature. It works really nice in internet explorer but it does not work for me in firefox. As a side note, would it be possible to implement a zoom by % function for the overall structure or Ang from the center as described for pyMOL: https://pymolwiki.org/index.php/Zoom?

**Comment by dkoes** [comment]
Are you sure it doesn't work in firefox?  Is it possible you were using previously and firefox and you just need to reload the cache?

**Comment by nvelden** [comment]
That solved the issue. Thanks a lot!
