### ISSUE TITLE
Highlight atoms/bonds?

### ISSUE THREAD

**Issue by proteneer** [3dmol/3Dmol.js#397]
Is there a way to highlight certain atoms/bonds in the 3d structure? Ideally something that can take in a list of indices to highlight?

**Comment by dkoes** [comment]
You would need to manually style the desired selection. For example, you can change the color to yellow.  You can specify a selection with a list of atom serial numbers if you have them.

What exactly is your desired outcome?

**Comment by proteneer** [comment]
Basically a way to highlight a substructure (I've already mapped the indices using the RDKit)

**Comment by proteneer** [comment]
eg. in the rdkit, the drawing API allows one to pass in a list of highlightAtoms=[1,2,3,6,7] which will highlight both the atoms and any bonds between said atoms

**Comment by proteneer** [comment]
my current solution is to do something like this:

    for h in ha:
        p.setStyle({'serial':h},{'stick':{'color': 'purple'}});

**Comment by dkoes** [comment]
You should be able to do
`p.setStyle({'serial':ha},{'stick':{'color': 'purple'}});`
assuming ha is a list.

**Comment by proteneer** [comment]
Thanks. This suffices for my use case :)
