### ISSUE TITLE
Can't access atom/style color

### ISSUE THREAD

**Issue by DanBuchan** [3dmol/3Dmol.js#398]
When I load and initialise a pdb file for display I can't seem to access the atom colours at a later point in the code. I'm using this method to colour the chain in a custom fashion given some artificial b factors we've written to the file: 

```
let hotspot_color = function(atom){
    if(atom.b == 1.0){return 'red';}
    if(atom.b == 0.5){return 'black';}
    if(atom.b == 50){return 'white';}
    if(atom.b == 100){return 'red';}
    return("blue");
 };
viewer = $3Dmol.createViewer( element, config );
let data = get_text(uri, "GET", {});
viewer.addModel( data, "pdb" );  
viewer.setStyle({}, {cartoon: {colorfunc: hotspot_color}}
viewer.render();  
```

In response to user action on my website I want to be able to toggle some residue colours, something like the following wrapped in an onClick() event:

```
highlightToggle = function(atom) {
  return atom.color == 'green' ? 'blue' : 'green';
};

viewer.setStyle({chain: 'A'}, {cartoon: {colorfunc: highlightToggle}});
```
except by the time I get to this bit of code `atom.color` seems to only ever be set to 13158600 for all atoms/residues and `atom.style.color` is always undefined. Where do I access the current colour value for an atom in a cartoon representation? I've been unable to work this out from the docs atm.

**Comment by dkoes** [comment]
Since you are using colorfunc, your hotspot_color function is called directly to set the color.  The result is not stored in the atom.  If you want it to be stored, modify hotspot_color to set atom.color.

**Comment by DanBuchan** [comment]
Thanks for the prompt response, that makes sense. And out of interest where is the colour info otherwise stored for cartoon rendering?

**Comment by dkoes** [comment]
That would be in atom.style.cartoon.color.  atom.color is a default color for the atom that is overridden by style color information (if set).

**Comment by DanBuchan** [comment]
Ah, I think my confusion arises here because atom.style.cartoon.color seems to return undefined when I'd tried to read/set it in my highlightToggle function
