### ISSUE TITLE
Add support for X-ray density maps

### ISSUE THREAD

**Issue by dkoes** [3dmol/3Dmol.js#4]
Takanori has some really cool looking volume rendering.  Adding simple meshes shouldn't be too hard.

**Comment by ghutchis** [comment]
There's some nice volumetric rendering demos now up:
http://www.lebarba.com/blog/
http://www3.cs.stonybrook.edu/~igutenko/webglvolrender.html#

**Comment by wojdyr** [comment]
They are nice, but it's not how el.den. maps are visualized. Normally it's blue (or green/red for difference maps) chicken wire:
https://www.google.com/search?tbm=isch&q=protein+electron+density+map

**Comment by dkoes** [comment]
We can already do meshes of isosurfaces (e.g. http://3dmol.csb.pitt.edu/tests/check/test14.html), but the only volumetric file format we support are cube files.  What are the common file formats and how do you get them? CCP4?

**Comment by wojdyr** [comment]
I'd guess that the most popular map format is ccp4, although crystallographic programs usually don't need map files at all - they generate maps internally from the reflection list.
You can get maps for example from [EDS](http://eds.bmc.uu.se/eds/), for example - [for 1ubq](http://eds.bmc.uu.se/cgi-bin/eds/gen_maps_zip.pl?pdbCode=1ubq).

BTW apart from Takanori's viewer there is another viewer (Nat's) that also can show el. density: http://natechols.github.io/xtal.js/map_viewer.html

**Comment by wojdyr** [comment]
@dkoes: for some uses it could be good enough to show just a single isosurface. To make it faster. I haven't looked into 3dmol internals yet, but I suppose that if I had pre-generated results of marching cubes (tentatively from [coot](https://github.com/pemsley/coot/)), it would be not too difficult to display it as wireframe?

**Comment by dkoes** [comment]
You can create custom shapes ($3Dmol. GLShape.addCustom) from vertex and facedata.   There's also addMesh in the viewer class.

We do have our own marching cubes, so ideally we will implement ccp4, I just need time to look at it.

**Comment by dkoes** [comment]
@zanguef contributed support for ccp4.  See:
http://3dmol.csb.pitt.edu/tests/check/test45.html

We need to make this accessible through the embedded and viewer apis.  Are there conventional defaults that crystallographers use when looking at this stuff (like isosurface values, colors, and styles)?

**Comment by wojdyr** [comment]
It's usually shown as blue mesh (chickenwire):
https://www.google.com/search?tbm=isch&q=protein+electron+density+map
If difference map is shown (difference between experimental data and model - this would be read from a separate ccp4 file) it is conventionally in green and red.
But for example http://pymolwiki.org/index.php/Display_CCP4_Maps suggests grey mesh.

BTW test45 is rather slow, I get Firefox warning:
> A script on this page may be busy, or it may have stopped responding. [...]
> Script: http://3dmol.csb.pitt.edu/build/3Dmol.js:29630

**Comment by zanguef** [comment]
Hi Dkoes embedded and viewer apis are certainly needed for this but i get the same error as @wjdyr when i try to access the example . What could be the problem?

**Comment by zanguef** [comment]
I can see the example now i think my browser was the problem

**Comment by wojdyr** [comment]
yes, it's eventually rendered, it just takes time -- that's what the warning in the browser was about

**Comment by dkoes** [comment]
It's a very large map - it takes time.

**Comment by dkoes** [comment]
In looking at this more, I realized the ccp4 implementation assumes an orthonormal unit cell. So there's still more work to be done.

Am I correct to assume we should support an option to normalize the data to have zero mean and unit stddev so that isosurfaces can be drawn based on the stddev easily?

**Comment by wojdyr** [comment]
I'd think that the same isosurface can be easily shown regardless of normalization. If you know std.dev. and mean of the map you can just convert rms value to absolute value and show isosurface at that level as quickly without normalization?
I'm not an expert here, so take everything I write with a grain of salt.
People like to be able to easily change the contour level and to see both absolute value and rms (which is often referred to as sigma) of the selected level. I think 1 - 1.5 rms are typical value when looking at density map. But some [prefer absolute levels](https://www.jiscmail.ac.uk/cgi-bin/webadmin?A2=coot;720165a1.1511).

**Comment by wojdyr** [comment]
NGL has nice example at http://arose.github.io/ngl/ (Examples > ccp4).

**Comment by dkoes** [comment]
Okay, I completely overhauled the ccp4 code (greatly aided by the ngl code).  We now handle any sort of unit cell and the data is not scrambled. There's also an option to normalize the data now.
http://localhost/3Dmol/tests/check.html
http://3dmol.csb.pitt.edu/tests/check/test45.html

Leaving this open since we still need more convenient APIs and hooks for fetch data directly (which is a pain since it is binary).

**Comment by wojdyr** [comment]
Thanks! I tried it on one file, it looks good. I'll test it more later this week.

When I look at the performance in Firefox, laplacianSmooth() takes 80% of the time in addIsosurface(). I think it's normally not used for density maps.

**Comment by dkoes** [comment]
Try setting smoothness to 0 and see what happens with the performance and appearance.

**Comment by wojdyr** [comment]
the performance chart looks similar, apparently most of the work in laplacianSmooth() is done before it gets to the final loop. I've opened https://github.com/3dmol/3Dmol.js/pull/170 for this.

Not-smoothed maps look a bit square-ish. I'm quite sure that density maps should not be smoothed, but I'm yet to determine why they look differently than in other programs.

**Comment by dkoes** [comment]
I think other codes (e.g. PyMOL) interpolate the grid values whereas we fully discretize the voxels.  Smoothing is an approximate way to get some interpolation, but we could do better.

This merits its own issue: #171

**Comment by wojdyr** [comment]
Yes, that explains the squares.

Usually you need to show the density map only in a small area (like 10A around the center of the screen), so the calculation of isosurface is much faster than for the whole map.

**Comment by dkoes** [comment]
That suggests another feature (#172) where users can control how much of the map to show

**Comment by wojdyr** [comment]
Just to let you know, regarding this issue and #172 .
In the meantime I've put together a viewer focused on el. density that always renders density around the center of the screen (like model-building programs). See:
http://uglymol.github.io/
https://github.com/uglymol/uglymol

This viewer is in early stage and, by design, is very basic in showing molecules. But I think it reads map files better than other JS viewers (it can read files in mode 0 and it applies symmetry operators from the header).
I've been [pondering](https://github.com/uglymol/uglymol/wiki/ccp4-dsn6-mtz) for a while what format we should use for local deployment in a synchrotron. Ideally it'd be mtz file, but it'd be even more work.
Anyway, if you'd come across any problems when reading ccp4 files, ping me, I may be able to help.

**Comment by dkoes** [comment]
Looks great. We'll definitely check it out.  Incidentally #172 is almost closed.

**Comment by dkoes** [comment]
Only reason for leaving open was hooks for fetching data? Have `$3Dmol.getbin`
