### ISSUE TITLE
Jupyter as an optional dependency

### ISSUE THREAD

**Issue by dgasmith** [3dmol/3Dmol.js#418]
Currently py3Dmol requires Jupyter to install via conda-forge which does make sense as it is quite integrated. However, we have a tool that we distribute quite a bit and it does not necessarily require Jupyter notebooks (though we recommend them heavily). This leads to the following scenarios:
 - If a user wants our tool in Jupyter and we do not depend on py3Dmol, no 3D molecule is automatically displayed (rough, quasi hidden feature) unless they download separately.
 - If a user does not want to use Jupyter and we require py3Dmol, then they will always get the entire Jupyter stack (large stack to pull every time).

This creates a bit of a rough patch for us. A recommendation is to make py3Dmol not depend on Jupyter. While granted somewhat odd as the project would only serve as a HTML/JS generator for py3Dmol without Jupyter. The general distribution control flow for downstream projects works much better without this very heavy dependency. At worse case, consider the following flow: `conda install py3dmol; Jupyter notebook` you have two options:
 - Everything boots fine as Jupyter was pre-installed (expected)
 - `zsh: command not found: Jupyter` at which point a user would likely simply install Jupyter.

Happy to do make the PR to patch this correctly with exception handling.

Most of these tools are part of the MolSSI [QCArchive](https://qcarchive.molssi.org) stack.

**Comment by dkoes** [comment]
I had not considered this use case.  I assume the idisplay dependency is still okay?

**Comment by dkoes** [comment]
4fa1ab8fba2619352dfb778c4d46d3647bd91e1d

**Comment by dgasmith** [comment]
Thank you for getting this so quickly. A few notes:
 - It does not appear that you use the `idisplay`, `idisplay` does pull iPython which gets you your dependancy. `idisplay` appears to be a little used [package](https://github.com/lebedov/idisplay).
 - Would you mind if I made a PR that wrapped the `import IPython` statements so that commands like `show` would soft fail if not present.

**Comment by dkoes** [comment]
I do use IPython.display.  I'd be happy to review a pull request.

**Comment by dgasmith** [comment]
Right, the requirement is `IPython` but not `idisplay` (which pulls `IPython` indirectly). PR incoming.

**Comment by dgasmith** [comment]
Thanks! Ping me on the next Python release and I can adjust the conda-forge builds.

**Comment by dgasmith** [comment]
@dkoes Any thoughts on a timeline for a new Python release?

**Comment by dkoes** [comment]
New release (1.5) is out (finally).  Sorry about the delay - this switches to WebGL 2.0 which wasn't trivial.

**Comment by dgasmith** [comment]
Awesome, thank you!
