### ISSUE TITLE
 Selectively delete a label

### ISSUE THREAD

**Issue by Chensanyu** [3dmol/3Dmol.js#419]
Can only delete one label instead of having to delete all use function removeAlllabels.

**Comment by dkoes** [comment]
Can you provide an example of it not working?  The following code works:
```
        $3Dmol.download("pdb:1ubq",viewer,{},function(){
                          
               viewer.addResLabels();
               viewer.setStyle({},{stick:{}}); 
               viewer.render( ); //show labels

               viewer.removeAllLabels();              
               viewer.render(); //hide labels
        });
```

**Comment by Chensanyu** [comment]
'viewer.removeAllLabels();  ' can working.
But if i have many labels, i must remove all at one time. For example, i have 4 labels:A,B,C,D. I have to remove  these 4 labels, and i can't only remove the 'A' label.

**Comment by dkoes** [comment]
Please provide the code that isn't working.  The following code works for me to remove an individual label:
```
         $3Dmol.download("pdb:2EJ0",viewer,{},function(){
                  var toremove = viewer.addLabel("Aromatic", {position: {x:-6.89, y:0.75, z:0.35}, backgroundColor: 0x800080, backgroundOpacity: 0.8});
                  viewer.addLabel("Label",{font:'sans-serif',fontSize:18,fontColor:'white',fontOpacity:1,borderThickness:1.0,
                                           borderColor:'red',borderOpacity:0.5,backgroundColor:'black',backgroundOpacity:0.5,
                                           position:{x:50.0,y:0.0,z:0.0},inFront:true,showBackground:true});
                  viewer.removeLabel(toremove);
                  viewer.render();

                  
                });
```

**Comment by Chensanyu** [comment]
FOR EXAMPLE. `viewer.addResLabels({resi:350,chain:"A"},{fontSize:10,backgroundOpacity:0.5});`
I added a label of residue in 350, and i can't  remove label by the residue in 350 by `'viewer.removeLabel({resi:350,chain:"A"})`

**Comment by dkoes** [comment]
There wasn't support for getting the labels added by addResLabels.  I have pushed a change so that addResLabels returns an array of the labels added.  Example:
http://3dmol.csb.pitt.edu/tests/auto/generate_test.cgi?test=removereslabels
This is now in release 1.4.0.
