### ISSUE TITLE
how to select a range of residue numbers?

### ISSUE THREAD

**Issue by angel-herraez** [3dmol/3Dmol.js#421]
Hi. I just found out 3Dmol.js and am exploring its possibilities. Great work!

I regularly use JSmol in writing web pages with structures; for large complexes I might use 3Dmol due to faster loading.
I have started by using the html method with data-etc attributes. I cannot find a way to use "resi" with a range of residue numbers, i.e. to select a segment of a protein.

`<div id="panelMol" class="viewer_3Dmoljs" data-href="3rze.pdb" data-select1="resi:[40-50]" data-style1="color:red"></div>`

Can anyone give me a hint to the syntax?
Thanks

**Comment by dkoes** [comment]
The issue is with the styling, not the selection.  You have to specify the geometry style first and then provide its parameters.  Also, this div needs to have its size set or you will see nothing (perhaps this is being done via css):
```
<div id="panelMol" style="width: 400px; height: 400px; position: relative;" class="viewer_3Dmoljs" 
 data-pdb="3RZE" 
 data-style="line;cartoon"
 data-select1="resi:[40-50]" data-style1="stick:color=red"
 data-zoomto="resi:[40-50]"
 ></div>   
```

In the above example I set a default style of line and cartoon and then select residues 40-50, set them to red sticks, and zoom in on them.

**Comment by angel-herraez** [comment]
Thanks for the prompt feedback, David

Finally the problem was not in the syntax, but in the library. I was using 
v.1.4.0 for CloudFare CDN and that one does not interpret the "resi" 
selection. Same for v.1.3.0
Using the one from your site does work.

(Yes, the size of the div was being set in css)

Cheers,
Angel


El 21 Jul 2019 a las 11:10, David Koes escribió:

> 
> The issue is with the styling, not the selection. You have to specify the geometry style first and 
> then provide its parameters. Also, this div needs to have its size set or you will see nothing 
> (perhaps this is being done via css):
> 
> <div id="panelMol" style="width: 400px; height: 400px; position: relative;" class="viewer_3Dmoljs" 
>  data-pdb="3RZE" 
>  data-style="line;cartoon"
>  data-select1="resi:[40-50]" data-style1="stick:color=red"
>  data-zoomto="resi:[40-50]"
>  ></div>   
> 
> 
> In the above example I set a default style of line and cartoon and then select residues 40-50, set 
> them to red sticks, and zoom in on them.
> -
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.

·
 Dr. Angel Herráez
 Biochemistry and Molecular Biology,
 Dept. of Systems Biology, University of Alcalá
 E-28871 Alcalá de Henares  (Madrid), Spain

**Comment by dkoes** [comment]
Are you sure the problem is with the CDN library?  1.4.0 is a recent release and should work fine with resi.

**Comment by dkoes** [comment]
It looks like the CDN version isn't getting updated properly.. working on a fix.

**Comment by angel-herraez** [comment]
Pretty sure. See
http://biomodel.uah.es/angel/test_CloudFare.htm
http://biomodel.uah.es/angel/test_Pitt.htm


El 22 Jul 2019 a las 6:51, David Koes escribió:

> 
> Are you sure the problem is with the CDN library? 1.4.0 is a recent release and should work fine 
> with resi.
> -
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.

·
 Dr. Angel Herráez
 Biochemistry and Molecular Biology,
 Dept. of Systems Biology, University of Alcalá
 E-28871 Alcalá de Henares  (Madrid), Spain
