### ISSUE TITLE
very large file visaulized?

### ISSUE THREAD

**Issue by renjf1** [3dmol/3Dmol.js#422]
I have some .dump file about 10Gb ~, we want visualize through 3dmol, but out of memory . can any suggest for this? is it possible?
Thanks!

**Comment by dkoes** [comment]
What is a dump file?

**Comment by renjf1** [comment]
hello @dkoes ，.dump just a file suffix, you can open it with notepad++. it's lammps output.

**Comment by dkoes** [comment]
lammps files are read completely into memory. If it doesn't all fit in memory you need to host the trajectory using mdsrv and provide the URL to setCoordinatesFromURL so frames can be fetched on demand.
