### ISSUE TITLE
How to set specific colors for specific atoms

### ISSUE THREAD

**Issue by quadmachine** [3dmol/3Dmol.js#431]
[:LABEL:]
Feature request or help with implementation.

**Description**
I am using 3Dmol to embed molecule from http://molview.org/?cid=24295
When I embed it, the colors of atoms are different. I need a way to set color of each atom
https://monosnap.com/file/9cmha7c2Tuk8wyq3uzxbn3gPvU3RUv

**Relevant Context**
You can see the difference in rendered colors here https://monosnap.com/file/9cmha7c2Tuk8wyq3uzxbn3gPvU3RUv

this is my code used for loading the model

````
loadModel() {
      let self = this
      var viewer = $3Dmol.createViewer(
        `molecule-${this._uid}`, //id of div to create canvas in
        {
          defaultcolors: $3Dmol.elementColors.rasmol,
          backgroundColor: '#000'
        }
      );

      this.loading = true

      $.get(self.conf.model.path, function(data) {
        self.loading = false

        viewer.addModel(data, 'sdf');
        viewer.addStyle( { stick: { radius: 0.15 } } );
        viewer.addStyle( {sphere:{ scale: 0.25 }} );

        viewer.zoomTo();
        viewer.render();
      });
    },
```

**Comment by dkoes** [comment]
Use the Jmol default color scheme (`$3Dmol.elementColors.Jmol`) if you want greenish fluorines, or define your own mapping from elements to colors either by setting the default color scheme or setting the colorscheme as part of the style (http://3dmol.csb.pitt.edu/doc/types.html#ColorschemeSpec)

**Comment by dkoes** [comment]
http://3dmol.csb.pitt.edu/tests/auto/generate_test.cgi?test=test_defaultcolors
