### ISSUE TITLE
[BUG] Missing documentation on ES6 import

### ISSUE THREAD

**Issue by NicolasCARPi** [3dmol/3Dmol.js#435]
**Describe the bug**
Hello,

First, thank you for this library, it is great and I'm happy to see that it is still maintained!

In the old days, a javascript library such as 3dmol was included directly with a `<script>` tag in the html file and everyone was happy.

Nowadays, most modern libraries can be included in a project with `import library;` statement in a .ts/.js file. This allow tree shaking and is a better way to handle dependencies in code.

I wanted to use npm to include 3dmol (was previously in source control in a `vendor/` directory and bundled with other code with `grunt`).

It appears that no documentation is available for such a process.

Here is the correct line that should be added in a .ts/.js file to import the lib (after `npm i 3dmol` or `yarn add 3dmol`)

~~~javascript
// note the different capitalization of 3dmol
import 3dmol/release/3Dmol-nojquery.js';
~~~

Provided of course that a line like `import jquery;` exists somewhere in the project.

I wanted to make a PR to improve the README but I'm not sure if this should be added to the README or the documentation hosted at pitt.edu. My opinion is to add it on the README as that's clearly the best place to have such information. Also, the pitt.edu website is not open source AFAIK so changes can't be proposed there.

Hence this issue to have your opinion on the matter.

**To Reproduce**
1. Try to use 3dmol in a modern project (with typescript, webpack, babel, ...)

**Expected behavior**
Expect instructions in README to achieve this.

**Actual behavior**
No documentation on modern usage could be found.

**Comment by dkoes** [comment]
Actually, the whole website is part of git, but is generated using jsdoc.  The best document to edit is 
https://github.com/3dmol/3Dmol.js/blob/master/doc.md
since this is what is put under the "Develop" tab (in the using the source code section).
If you run gulp, or just "gulp doc" it will create the website.

Look forward to seeing your pull request
