### ISSUE TITLE
Add label for each frame in animation?

### ISSUE THREAD

**Issue by Jack-XHP** [3dmol/3Dmol.js#441]
**Is your feature request related to a problem? Please describe.**
Currently, I use addLabel to add a description and extra info to a molecule view. However, I want to display a molecule generation process and the label is changing during that process. Would be great if there is a function to add label for each frame when molecules are imported using addModelsAsFrames

**Describe the solution you'd like**
in addLabel add an argument (frame index) so the label will be added to just that frame.

**Describe alternatives you've considered(Optional)**

**Additional context(Optional)**

**Comment by dkoes** [comment]
The `frame` property of the LabelSpec options can be used to set a label to only appear in a specific frame:
http://3dmol.csb.pitt.edu/doc/types.html#LabelSpec

Here's an example of it in action:
http://3dmol.csb.pitt.edu/tests/auto/generate_test.cgi?test=animatelabels

I'm pretty sure this does exactly what you are requesting, so I'm closing the issue.  Feel free to open if I'm not understanding the issue properly.
