### ISSUE TITLE
Question about embedded viewer

### ISSUE THREAD

**Issue by khoivan88** [3dmol/3Dmol.js#446]
Hi, first of all, thank you very much for your useful library.

I have a question related to embedded viewer, specifically on how to add zoom or set rotate(). I am very new to JS so if I miss anything obvious, I'm sorry. 

Following this [tutorial](http://3dmol.csb.pitt.edu/doc/tutorial-embeddable.html), I was able to create an embeded viewer using 3DMol.js. However, I am having a hard time calling that specific viewer with id so that I can do something with the view, such as zoom or rotate. 
Below is my simple html page:
```html
<!DOCTYPE html>
<html lang="en">
    <head>
        <link rel="shortcut icon" href="images/Romo_logo copy.ico" />
        <title>Romo Group | 3D Viewer</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="//code.jquery.com/ui/1.12.0/themes/base/jquery-ui.css">

        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <script src="http://3Dmol.csb.pitt.edu/build/3Dmol-min.js""></script>
        <style>
            .mol-container {
                width: 100%;
                height: 100vh;
                position: relative;
            }
        </style>

    </head>
    <body>
        <div class='container-fluid'>
            <div id="3dviewer" class='viewer_3Dmoljs mol-container' 
                data-href data-backgroundcolor='white' 
                data-style='stick'
                onload="loadfile()">
            </div>
        </div>
            
        <script>
            function getUrlVars() {
                var url = new URL(window.location.href);
                var file = url.searchParams.get("file");
                return file;
            };

            var file = getUrlVars();
            file = 'images/CrystalStructures/' + file + '.xyz'
            document.getElementById('3dviewer').setAttribute('data-href', file);        
        </script>

        <script>
            let viewer = $3Dmol.viewers["#3dviewer"];
            viewer.setBackgroundColor('orange');
        </script>

    </body>
</html>
```

In the example above, the last `<script>` was me trying to call the view with id="3dviewer" and then for testing, just change background. However, it is not successful. If you have sometime, would you mind giving me some pointer on how to solve this issue?

Thank you very much!

Khoi

**Comment by dkoes** [comment]
Remove the hashtag from the viewer name.
`viewer = $3Dmol.viewers['3dviewer']`

**Comment by khoivan88** [comment]
thank you so much for your answer!

**Comment by ramithuh** [comment]
somewhat of a related question, so thought to post here.

I'm saving a `3Dmol.js` grid view through python, (saved HTML is also listed below).

My goal is to access the views separately so that I can add an HTML button to change properties.
I can access the first grid view, `viewer_17156140122427943`, so I can edit things like `viewer_17156140122427943.setBackgroundColor(225,92,153)`
* but I'm not sure how to access the second. Is there a way to list all the `3Dmol.js` views in HTML/js?
* Since the HTML below is dynamically generated (random names for the viewer), is there a way to hardcode it?

```python
test = py3Dmol.view(viewergrid=(1,2))
test.write_html(f"test.html")
```


```html
<html>
<body style="margin: 0; padding: 0; display: block;">
<div id="3dmolviewer_17156140122427943"  style="position: relative; width: 640px; height: 480px;">
        <p id="3dmolwarning_17156140122427943" style="background-color:#ffcccc;color:black">3Dmol.js failed to load for some reason.  Please check your browser console for error messages.<br></p>
        </div>
<script>

var loadScriptAsync = function(uri){
  return new Promise((resolve, reject) => {
    //this is to ignore the existence of requirejs amd
    var savedexports, savedmodule;
    if (typeof exports !== 'undefined') savedexports = exports;
    else exports = {}
    if (typeof module !== 'undefined') savedmodule = module;
    else module = {}

    var tag = document.createElement('script');
    tag.src = uri;
    tag.async = true;
    tag.onload = () => {
        exports = savedexports;
        module = savedmodule;
        resolve();
    };
  var firstScriptTag = document.getElementsByTagName('script')[0];
  firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);
});
};

if(typeof $3Dmolpromise === 'undefined') {
$3Dmolpromise = null;
  $3Dmolpromise = loadScriptAsync('https://cdnjs.cloudflare.com/ajax/libs/3Dmol/2.1.0/3Dmol-min.js');
}

var viewer_17156140122427943 = null;
var warn = document.getElementById("3dmolwarning_17156140122427943");
if(warn) {
    warn.parentNode.removeChild(warn);
}
$3Dmolpromise.then(function() {
var viewergrid_17156140122427943 = null;
viewergrid_17156140122427943 = $3Dmol.createViewerGrid(document.getElementById("3dmolviewer_17156140122427943"),{rows: 1, cols: 2, control_all: true},{backgroundColor:"white"});
viewer_17156140122427943 = viewergrid_17156140122427943[0][0];
viewergrid_17156140122427943[0][0].zoomTo();viewergrid_17156140122427943[0][1].zoomTo();viewergrid_17156140122427943[0][1].render();
viewergrid_17156140122427943[0][0].render();
});
</script>
</body>
</html>
```

**Comment by dkoes** [comment]
In your example `viewergrid_17156140122427943` is an array of GLViewers that you can access.  You can get the number part from the python view objects as `v.uniqueid`
I'm guessing for what you want to do you would have python write out the HTML for your button using that unique id to specify the JavaScript.  Or are you trying to do something else?

**Comment by ramithuh** [comment]
Thank you! accessing `v.uniqueid` is helpful for my usecase!

This page, https://c195659f.boston-nmr-org.pages.dev/test, is a minimal example of what I'm trying to accomplish.. 

* My guess is that the array of GLViewers (`viewergrid_17156140122427943`) is not accessible beyond the scope of `$3Dmolpromise.then(function(){});` — this prevents me from controlling views beyond (0,0).
* However, `viewer_17156140122427943` is accessible (which is the 0,0 view)

In my actual usecase, I have generated a bunch of grid views, (https://c195659f.boston-nmr-org.pages.dev/), and have added them as an iframe to parent HTML. I was trying to see if I could add a button to the parent HTML to turn on/off spinning without making changes to the generated HTML files with grid views.

**Comment by ramithuh** [comment]
lovely! `viewer_17156637335138817.viewers` helped.. 
now controlling (e.g. spin) the iframe works — https://cf67d5c3.boston-nmr-org.pages.dev
