### ISSUE TITLE
viewer rotate molecule in the same viewing axis after user manual rotate

### ISSUE THREAD

**Issue by khoivan88** [3dmol/3Dmol.js#450]
Prof @dkoes, 

I was playing around with 3dmol.js and able to get a viewer for a molecule with spinning using `rotate`. [Example](http://danielromogroup.com/3dviewer-test.html?file=cmpd15). With this page, I set the rotation to around y-axis, I notice that if user rotate the molecule into a different orientation and then resume the autorotation, it rotates around the original y-axis of the molecule when it started and not the viewer y-axis. My question is if there is an easy way to have the molecule spin around the viewing axis and not the origin-axis of the the molecule? 

I tried to read through the API to see if there is any methods to do this easily and the only think I can think of is maybe use `getView()` and then pass the parameter to `setInternalState()`?

This is how I set the rotation view, in case it is relevant:
```html
...
    <body>
        <div class='container-fluid'>
            <div class="container-fluid text-center">
                <button  type="button" class="btn btn-dark" onclick="tmr=!tmr">Pause/Play rotation</button>
            </div>
            <div id="3dviewer" class='viewer_3Dmoljs mol-container' 
                data-href
                data-style='stick' data-backgroundcolor='white'
                >
            </div>
        </div>
...
        <script>
            tmr = true;
            var viewer;           
            interval = setInterval(function() {
                if (tmr) {
                    viewer = $3Dmol.viewers['3dviewer'];
                    viewer.rotate(1, 'y');
                    //viewer.spin();
                }
            }, 42);
        </script>
    </body>
```

Thank you!

**Comment by dkoes** [comment]
Well, you can call getView, extract the quaternion, do the math to figure out how to update it to rotate with respect to the viewer's frame of reference, and then call setView, but I've just pushed a change where you can now specify you want to rotate a view axis by specifying 'vx', 'vy', or 'vz'.
e433b3ee63fc611292895d37080491e7f6801538
Example
http://3dmol.csb.pitt.edu/tests/auto/generate_test.cgi?test=testviewrotate

**Comment by dkoes** [comment]
(This works for spin as well)

**Comment by khoivan88** [comment]
Amazing. Thank you very much for your quick response and update! This has helped me so much!
