### ISSUE TITLE
Visual glitch when changing vibration on same viewer

### ISSUE THREAD

**Issue by RaphaelRobidas** [3dmol/3Dmol.js#453]
I am loading an XYZ file containing vibration data (dx,dy,dz). This works just fine, but if I try to clear the viewer and load another XYZ file, there seems to be a visual glitch happening. Refreshing the page and loading the second structure produces the expected animation without glitch. I tried using all the remove functions as well as stopping the animation, but the glitch still occurs.

Here is a minimal working example: https://jsfiddle.net/ybpvocmk/

I am on Debian 10. This bug seems to occur both on Firefox 68.6.1esr (64-bit) and chromium 80.0.3987.149.

I think this is a bug, but maybe I am just using the library incorrectly?

**Comment by dkoes** [comment]
Stop animation was working asynchronously, so there was a lag between calling it and the animation actually stopping (on the next view update).  If a new animation loop was started during that period, bad things happen.

I've pushed a fix:
264763ddf9ab508e7405a73b91257ecd4c1cb802

Note that if you pass and empty arrowSpec option, with the latest version of the code it will assume you actually want arrows and will draw them with defaults.  Pass null if you don't want arrows.

Please verify the fix and close the issue.
https://jsfiddle.net/16v7znty/

**Comment by RaphaelRobidas** [comment]
Everything seems to work great now, thank you!
