### ISSUE TITLE
Running out of RAM when using py3Dmol to view many structures

### ISSUE THREAD

**Issue by gciaberi** [3dmol/3Dmol.js#454]
I'm using py3Dmol to view a large n° of protein structures and every time I create a new `py3Dmol.view()` object they add up in my RAM (on average I'd say + 50-100M per structure), so after viewing +/- 30 structures my RAM is nearly full and I have already crashed my computer a few times when I didn't pay attention. The only way I have found to free my RAM is to close all jupyter notebooks and local host server and start again.

I have already tried using `clear_output()` from `IPython.display` and garbage collection `gc.collect()` but they don't solve the RAM issue. Any suggestions ? Or am I missing something very obvious ?

Code:
```
for PDB_ID in PDB_list:
    view = py3Dmol.view(query = f'pdb:{PDB_ID}')
    # Configure the viewer 
    #...
    view.show()
    input() # To hold the image
    clear_output()
```

**Comment by dkoes** [comment]
You want to avoid creating a new viewer (with show) everytime you want to update it.  Use update instead.
```
view = py3Dmol.view()
view.show()
for pdb in ['1ycr','3erk']:
    mol = requests.get(f'https://files.rcsb.org/view/{pdb}.pdb').text
    view.addModel(mol,'pdb')
    view.setStyle({'cartoon':{}})
    view.zoomTo()
    view.update()
    view.clear()
    input()
```

Let me know if this resolves your memory issues and if the issue can be closed.

**Comment by gciaberi** [comment]
Yes `view.update()` did the trick, thanks.
