### ISSUE TITLE
opacity vs alpha

### ISSUE THREAD

**Issue by dkoes** [3dmol/3Dmol.js#458]
Shapes use an alpha property to indicate transparency while styles use opacity.  This is confusing. Standardize on one and deprecate the other.

**Comment by arnab15** [comment]
hello,
sir,
I'm new to open source contributions. I want to contribute here.I know Html,css,JavaScript,nodejs,React js,MongoDB How should I start contributing here .sir can you please suggest me something so that I can start contributing here.

**Comment by dkoes** [comment]
This would be a good, simple issue to get started with so you can gain familiarity with the code.  I believe support for opacity is already implemented for shapes, so all that needs to be done is updating the documentation and test files.

**Comment by arnab15** [comment]
@dkoes There is not defined documentation on how to set up a development environment.  should I work upon it to write proper Documentation for development environment setup.?

**Comment by dkoes** [comment]
Sure, what sort of environment would you setup?

**Comment by arnab15** [comment]
@dkoes I want to set up a development environment but I didn't find appropriate documentation in contributing .md file. I want to contribute to this project. So I think we can make documentation for the dev environment setup.

**Comment by dkoes** [comment]
There are many possible development environments.  I'm curious what it is you want to setup.
