### ISSUE TITLE
AddModels/addModelsAsFrames to support read multiple crystal structures from one cif file

### ISSUE THREAD

**Issue by qzhu2017** [3dmol/3Dmol.js#463]
**Is your feature request related to a problem? Please describe.**
In fact, the `cif` format usually allows one to read multiple crystal structures (like `xyz`). I wonder if you can also add a support on this. If this feature is available, we may be able to do some cool animations on the symmetry operation of molecules

**Comment by dkoes** [comment]
It's suppose to work already, but you need to use addModels (note the s) or addModelsAsFrames (for animation), but I'm not sure what will happen if the different molecules have different symmetry operations.  Can you provide an example?

**Comment by qzhu2017** [comment]
@dkoes 
sorry for the late reply. I just tried this function.

```python
import py3Dmol
import urllib
cif = urllib.request.urlopen("https://raw.githubusercontent.com/qzhu2017/PyXtal/master/doc/files/all.cif").read()

viewer = py3Dmol.view()
viewer.addModelsAsFrames(cif.decode('utf-8'),'cif',{'doAssembly':True,'duplicateAssemblyAtoms':True})
viewer.addUnitCell()
viewer.setStyle({'stick':{'colorscheme':'greenCarbon'}})
viewer.animate({'loop': "forward", 'step': 10})
viewer.zoomTo()
```

There are two major problems.

- If each structure has different lattice vectors, the animation fails to update the UnitCell for each frame
- I tried to adjust the speed of animation by setting different numbers to `step`. But it does not really show too much difference. 

Btw, I just tried to do some animation with the structures generated from my simulation. 
https://nbviewer.jupyter.org/github/qzhu2017/PyXtal/blob/master/examples/tutorials_notebook/02_molecular_crystals.ipynb

Thank you so much for providing this nice tool.

**Comment by dkoes** [comment]
Sorry to take so long to cycle back around to this.  Unit cells will now animate:
http://3dmol.csb.pitt.edu/tests/auto/generate_test.cgi?test=testmulticif
