### ISSUE TITLE
[question] What's the best way to create GLModel from JavaScript, with unitcell information?

### ISSUE THREAD

**Issue by Luthaf** [3dmol/3Dmol.js#469]
**Description**

I want to create GLModels **without** parsing a file, i.e. I already have the full structure data as JavaScript Object & want to pass these directly to 3Dmol.

I currently do this by creating an empty model & adding atom manually, with 
```js
const viewer = new $3Dmol.GLViewer(...);
const model = viewer.addModel();
model.addAtoms(atoms);
```

My question is how can I then add unitcell/box/CRYST information to the model? I've seen there is a `GLModel.getCrystData`, which seems to look at `modelData.cryst`, containing cell information as `a/b/c/alpha/beta/gamma`. Should I add a public function to `setCrystData`? 

At the same time, using `a/b/c/alpha/beta/gamma` instead of a full cell matrix (three cell vectors/axis) might be problematic since I would have to do a rotation of the entire cell and atoms if the axis are not aligned with `x/y/z`, and potentially loose some information regarding cell orientation (this situation comes up in anisotropic NPT simulation of materials).

My end goal is being able to (a) draw the unit cell box and (b) replicate the unit cell to create supercell, hopefully using `GLViewer.replicateUnitCell`.

**Relevant Context**

For the context, I'm evaluating if we could switch from JSmol to 3Dmol.js in [chemiscope](chemiscope.org/) for molecular rendering. It seems that 3Dmol fits our needs very well, while being easier to use & integrate in a modern JS application. The question above is my main blocking point right now =)

**Comment by Luthaf** [comment]
And by the way, thank you very much for 3Dmol, it is quite nice to work with!

**Comment by dkoes** [comment]
Yes, a setCrystData method is what is needed.  And here it is:
f01af8d8283794d75776c4eda20925da52d007c9

Note that I do plan on getting around to addressing #463 sometime in the next week or so, which may also be relevant to you (or you can work on it if you'd like!).

**Comment by Luthaf** [comment]
Thanks for the `setCrystData`! 

Do you have any plans on supporting full unit cell vectors in addition to `a/b/c/alpha/beta/gamma`?

**Comment by dkoes** [comment]
What is a full unit cell vector?

**Comment by Luthaf** [comment]
By that I mean describing the cell as three vectors **a**, **b** and **c**, possibly joined into a cell matrix:
```
| ax bx cx |
| ay by cy |
| az bz cz |
```

The a/b/c/alpha/beta/gamma representation can be converted to a matrix in this form, with the additional property of being an upper-triangular matrix

```
| ax bx cx |
| 0  by cy |
| 0  0  cz |
```

All full cell matrices can be transformed into the upper-triangular/`a/b/c/alpha/beta/gamma` representation by a rotation, aligning **a** along **x** and **b** in the xy plane. But doing this transformation requires to also rotate the molecules in the system, and loose some information (namely the cell orientation, which can change during a simulation).

**Comment by dkoes** [comment]
Some formats (VASP) set cryst.matrix instead of a/b/c/alpha/beta/gamma and addUnitCell will use this matrix property.  I didn't implement support for using cryst.matrix to replicateUnitCell, but this should be straightforward.

Arguably, cryst.matrix should always be set even if the input file doesn't use that representation and add/replicate unit cell and friends should only use the matrix representation.
