### ISSUE TITLE
I have some questions that i want to know

### ISSUE THREAD

**Issue by J-DuYa** [3dmol/3Dmol.js#472]
[:LABEL:]
About the interaction between molecules

**Description**
I want to know if I can do intermolecular interaction through this plugin.？

**Relevant Context**
I want to click on a certain molecular structure, and then the interface will initially show the schematic diagram of the related molecular action in this area
If possible, can I achieve Schrödinger’s intermolecular effect through 3dmol.js?

**Comment by dkoes** [comment]
No, 3dmol.js is for visualization only.  You would have to write any molecular analysis yourself.  You can define distance based selection objects, which may help.
