### ISSUE TITLE
I have a question: how to change the linewidth of a line?

### ISSUE THREAD

**Issue by wangyu-97** [3dmol/3Dmol.js#473]
[:LABEL:]
addLine, LineStyleSpec, linewidth

**Description**
After I use the "addLine" API to draw a line, like this:
`glviewer.addLine({start:{x:0,y:0,z:0},end:{x:100,y:100,z:100}});`
I find the line drawn really fine, however I want it to be more thicker.
Nevertheless, the "linewidth" PROPERTY is said to be "deprecated due to vanishing browser support", so the code below will not work:
`glviewer.addLine({start:{x:0,y:0,z:0},end:{x:100,y:100,z:100},linewidth:10});`
Therefore, I really wonder whether there are some solutions to make the line more thicker? Do I need to modify the source code? The simpler method, the better~

**Relevant Context**
Just as the picture shown below, the default linewidth is really thin！Not good for viewing.
![image](https://user-images.githubusercontent.com/32156765/92706103-d8ff5200-f386-11ea-8d2f-a02ffbd16119.png)

**Comment by dkoes** [comment]
You need to use addCylinder (or addDashedCylinder) with the desired radius.  The line style uses a specific kind of WebGL rendering that is no longer supported by browsers.
