### ISSUE TITLE
Import in React does not work. Help with a basic working example? Also want to use geometry file.

### ISSUE THREAD

**Issue by coltonbh** [3dmol/3Dmol.js#475]
**Describe the bug**
I am unable to import the 3Dmol object as per the instructions in the documentation.

This currently fails
```
import $ from "jquery";
import * as $3Dmol from "3dmol/build/3Dmol-nojquery.js";
```

with the error:

```
ReferenceError: $ is not defined
./node_modules/3dmol/build/3Dmol-nojquery.js
node_modules/3dmol/build/3Dmol-nojquery.js:6954
  6951 | */
  6952 | 
  6953 | // use this transport for "binary" data type
> 6954 | $.ajaxTransport(
  6955 |                "+binary",
  6956 |                function(options, originalOptions, jqXHR) {
  6957 |                    // check for conditions and support for blob / arraybuffer response type

```
https://github.com/coltonbh/mtzgroup-ts-frontend/tree/feature/3Dmol

**To Reproduce**

I have a repo setup where you can repo this:

```
git clone git@github.com:coltonbh/mtzgroup-ts-frontend.git
cd mtzgroup-ts-frontend
git checkout feature/3Dmol
npm install
npm start
```

**Expected behavior**
I would expect the module to import the object as per the documentation [here](http://3dmol.csb.pitt.edu/doc/index.html) regarding an ES6 export.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome

**Additional context**
Could you help me see a working example to import the 3Dmol object and then use it to display xyz geometry data? I can currently import the viewer using the script tag found in the `useEffect` hook, but I'd like to import and use the viewer directly in the code instead. Additionally, I'd love an example of how to use it to visualize xyz coordinate data held locally in the main function. Thank you very much!

**Comment by dkoes** [comment]
You need to export the jquery $ to the global scope (https://stackoverflow.com/questions/34338411/how-to-import-jquery-using-es6-syntax).  I've updated the docs.  

I'd be very interested in knowing if there is a better way for 3Dmol to include the jquery dependency in this case.

**Comment by coltonbh** [comment]
Using your code from the docs (added necessary quotes):
```
import "jquery";
// note the different capitalization of 3dmol
import * as $3Dmol from '3dmol/build/3Dmol-nojquery.js';
window.$ = $; //export jquery to the global scope so 3Dmol can use it
```

Creates the error:
```
./src/App.js
  Line 7:12:  '$' is not defined  no-undef

Search for the keywords to learn more about each error.
```
The export to the window comes after the attempted use of the `$` variable.

Changing the order of the imports and the syntax to match the SO answer to:
```
import { $} from "jquery";
window.$ = $; //export jquery to the global scope so 3Dmol can use it
import * as $3Dmol from '3dmol/build/3Dmol-nojquery.js';
```

Causes the error:
```
./src/App.js
  Line 6:1:  Import in body of module; reorder to top  import/first
```
Which is related to improper variable hoisting detailed [here](https://github.com/benmosher/eslint-plugin-import/blob/v2.20.1/docs/rules/first.md).

So I'm still stuck unable to import 3Dmol into a react project. Any chance you could pull my repo and see if you could get a working import? I think there are many of us, myself included, who can build decent UIs with React but the inner workings of getting 3Dmol's jQuery + script setup is a bit of a blocker. Having a working example with react to show people here would be super helpful!

Thanks so much!

**Comment by dkoes** [comment]
```
import {$,jQuery} from 'jquery';
import * as $3Dmol from "3dmol/build/3Dmol.js";
window.$ = $;
```

**Comment by dkoes** [comment]
Okay, you can chain the dependencies like this so that 3Dmol gets jquery:
```
import('jquery').then(($) => {
import("3dmol/build/3Dmol-nojquery.js").then( ($3Dmol) => {
console.log($3Dmol);
//can do things with $3Dmol here
})});
```
You could probably do flat imports if you had a version of jquery that exported itself to the window object (https://github.com/craigmichaelmartin/weather-app--birch/blob/4d9f3b03719e0a2ea3fb5ddbbfc453a10e9843c6/javascript/util/leak_jquery.js).

I would like to know if @NicolasCARPi has a better pattern since he contributed the original ES6 documentation.

**Comment by NicolasCARPi** [comment]
I'm using the expose-loader to make jquery globally available in the window:

file: webpack config file
~~~javascript
 {
        test: require.resolve('jquery'),
        loader: 'expose-loader',
        options: {
          exposes: ['$', 'jQuery'],
        },
      },
~~~

**Comment by dkoes** [comment]
I feel like this has been resolved.

**Comment by coltonbh** [comment]
@dkoes i haven’t had a minute to try the new solution. Got pulled into other projects. I’ll reopen if this doesn’t work. Thanks for the reply!
