### ISSUE TITLE
[BUG]unexcepted straight bars across the protein (i.e. 3hl2)

### ISSUE THREAD

**Issue by NatureGeorge** [3dmol/3Dmol.js#477]
**Describe the bug**
When load `3hl2` via `3Dmol`, there exist two arbitrary straight bars across the proteins.

**To Reproduce**
1. GOTO <http://3dmol.csb.pitt.edu/viewer.html?pdb=3hl2&style=cartoon>

**Expected behavior**
Just molecules.

**Screenshots**
![3hl2_bug](https://user-images.githubusercontent.com/43134199/96688540-df381380-13b3-11eb-9985-129032fd36e2.png)

Meanwhile, I am new to this module and I am wondering whether there is an easy way to display the DNA/RNA (let's assume its chain id is "A") in cartoon style while display ligand (also with the same chain id "A") in stick style. Can 3Dmol implement `struct_asym_id` (`label_asym_id`) defined by `mmCIF`?

**Comment by dkoes** [comment]
This is fixed now.  The asym_id from cif is stored as the chain identifier.  You can set styles to specific chains:
view.setStyle({chain:'A'},{cartoon:{}});
view.setStyle({chain:'B'},{stick:{}});
