### ISSUE TITLE
[BUG] - 3Dmol automatically redirects to get.webgl.org if webgl is not supported or is disabled

### ISSUE THREAD

**Issue by jonwedell** [3dmol/3Dmol.js#479]
**Describe the bug**

When WebGL is disabled or not functioning, the user is redirected to get.webgl.org if the 3Dmol autoloader is used. The line causing this is located here: https://github.com/3dmol/3Dmol.js/blob/351a096275088367b7d4ea8c5c58f07b1978db21/3Dmol/autoload.js#L147

**To Reproduce**
1. Disable WebGL in Firefox. (Go to about:config, and toggle webgl.disabled to true, then restart browser)
1. Go to [bmrb.io](https://bmrb.io/data_library/summary/index.php?bmrbId=15000)
2. Be automatically redirected to get.webgl.org when the 3Dmol widget loads

**Expected behavior**
An error with a link to get.webgl.org is displayed, but the entire webpage isn't automatically redirected to get.webgl.org. This lead to users of our webpage thinking that we were hacked.

**Desktop (please complete the following information):**
 - Known to occur on Microsoft Edge on Windows 10, but also on Firefox 68.5.0esr on Centos 7.7.1908. I think it happens whenever WebGL is not supported.

@gryk - Tagging you since you first encountered this issue on our site.

Thanks!

**Comment by dkoes** [comment]
This is the intended behavior, but I can see how it is needlessly intrusive so I've changed it.
509afa8b21501607b10092315818f4dd4b2c67d6

**Comment by jonwedell** [comment]
Thanks!
