### ISSUE TITLE
Cannot load files in SDF format[BUG] Error 

### ISSUE THREAD

**Issue by donnrri** [3dmol/3Dmol.js#480]
I cannot load SDF formatted files into a 3Dmol.js viewer. An error is thrown
```
TypeError: Cannot read property 'trim' of undefined
    at u (3Dmol-min.js:489)
    at Object.drawCartoon 
```
I would appreciate any help with this.

I have the following code

```
   let element = $("#container-01");
            let config = { backgroundColor: "white"};
            let viewer = $3Dmol.createViewer(element, config);
```
 ```
const url = mypath -to-file
    $.ajax( unannotated_url , { 
                    success: function(data) {
                        console.log(data)
                        let v = viewer;
                        v.addModel( data, "sdf" );  
                        v.setStyle({}, {cartoon: {color: 'spectrum'}});                   
                        v.zoomTo();                                   
                        v.render();                                      
                        v.zoom(1.2, 1000);                               
                    },
                    error: function(hdr, status, err) {
                        console.error( "Failed to load SDF file " + sdf_file_path + ": " + err );
                    },
                });
```
While pdb files load with no problem , I have tried several .sdf files and the same error is thrown

My sdf file is belowSDF
  -OEChem-11062022473D

 21 21  0     1  0  0  0  0  0999 V2000
    3.5700    2.5150   68.6270 C   0  0  0  0  0  0  0  0  0  0  0  0
    2.5990    4.5620   70.3380 P   0  0  0  0  0  0  0  0  0  0  0  0
    0.9220    2.9880   68.4650 S   0  0  0  0  0  0  0  0  0  0  0  0
    4.9350    4.2750   66.8770 Cl  0  0  0  0  0  0  0  0  0  0  0  0
    4.6010    2.7290   67.6920 C   0  0  0  0  0  0  0  0  0  0  0  0
    6.5890   -0.8370   67.5410 Cl  0  0  0  0  0  0  0  0  0  0  0  0
    5.5120    1.7140   67.3760 C   0  0  0  0  0  0  0  0  0  0  0  0
    5.4030    0.4570   67.9520 C   0  0  0  0  0  0  0  0  0  0  0  0
    4.3610    0.2200   68.8410 C   0  0  0  0  0  0  0  0  0  0  0  0
    3.4540    1.2340   69.1490 C   0  0  0  0  0  0  0  0  0  0  0  0
    2.4700    3.4170   69.0660 C   0  0  3  0  0  0  0  0  0  0  0  0
    3.9880    5.1310   70.5140 O   0  0  0  0  0  0  0  0  0  0  0  0
    1.5520    5.6310   70.1400 O   0  0  0  0  0  0  0  0  0  0  0  0
    2.3100    3.6060   71.4840 O   0  0  0  0  0  0  0  0  0  0  0  0
    6.3090    1.9120   66.6750 H   0  0  0  0  0  0  0  0  0  0  0  0
    4.2530   -0.7540   69.2950 H   0  0  0  0  0  0  0  0  0  0  0  0
    2.6340    1.0150   69.8160 H   0  0  0  0  0  0  0  0  0  0  0  0
    3.9510    6.0790   70.4670 H   0  0  0  0  0  0  0  0  0  0  0  0
    1.4910    3.8480   71.9000 H   0  0  0  0  0  0  0  0  0  0  0  0
    0.1660    3.9100   68.9830 H   0  0  0  0  0  0  0  0  0  0  0  0
    2.8940    4.3220   68.6070 H   0  0  0  0  0  0  0  0  0  0  0  0
  1 11  1  0  0  0  0
  1 10  1  0  0  0  0
  2 12  1  0  0  0  0
  2 14  1  0  0  0  0
  3 11  1  0  0  0  0
  4  5  1  0  0  0  0
  1  5  2  0  0  0  0
  6  8  1  0  0  0  0
  5  7  1  0  0  0  0
  7  8  2  0  0  0  0
  7 15  1  0  0  0  0
  8  9  1  0  0  0  0
  9 10  2  0  0  0  0
  9 16  1  0  0  0  0
 10 17  1  0  0  0  0
  2 11  1  0  0  0  0
 12 18  1  0  0  0  0
  2 13  2  0  0  0  0
 14 19  1  0  0  0  0
  3 20  1  0  0  0  0
 11 21  1  0  0  0  0
M  END
> <OPENEYE_ISO_SMILES>
c1cc(c(cc1Cl)Cl)C(P(=O)(O)O)S

> <OPENEYE_INCHI>
InChI=1S/C7H7Cl2O3PS/c8-4-1-2-5(6(9)3-4)7(14)13(10,11)12/h1-3,7,14H,(H2,10,11,12)/t7-/m1/s1

> <OPENEYE_INCHIKEY>
WJVBVZOYOCLGPI-SSDOTTSWSA-N

> <FORMULA>
C7H7Cl2O3PS

$$$$

**Comment by dkoes** [comment]
Style it as sticks/wires/spheres anything other than cartoon which will only display something if you have a protein.

**Comment by donnrri** [comment]
Thanks . Could that e made a bit clearer in the Docs , I did not see that there.
