### ISSUE TITLE
[BUG] Atom click handlers sometimes get erroneously triggered

### ISSUE THREAD

**Issue by andfaulkner** [3dmol/3Dmol.js#481]
Sometimes clicking locations where one atom is present triggers the click handler for another atom. Other times, clicking an area with no atom present at all will trigger the handler on an atom.

I've attached a video demonstrating the issue including steps to produce it. The halos appear on clicking an atom in my 3DMol configuration. It tends to happen with larger, more complex molecules.

[3dmol-bug-video.mp4.zip](https://github.com/3dmol/3Dmol.js/files/5539655/3dmol-bug-video.mp4.zip)

Desktop:
 - OS: It's been observed on OSX, Windows, and Linux
 - Browser: Seen on both Chrome and Firefox, across multiple versions. That video was taken in Chrome, v86.
 - Version: 3dmol v1.5.4

**Comment by dkoes** [comment]
Can you please provide the structure and code used in the example?

**Comment by andfaulkner** [comment]
Here's the molecular structure used in the example:
[C111tiny.xyz.zip](https://github.com/3dmol/3Dmol.js/files/5544302/C111tiny.xyz.zip)

As for the code...there are over 7000 lines used to instantiate that, since we have a custom UI wrapper around 3DMol (to implement various features involving re-rendering the 3DMol view with different characteristics changed, such as which atoms to highlight) across over 20 separate files, so there isn't really a nice way to attach it.

However, it can be replicated with any 3DMol viewer that attaches click handlers to atoms and has said atoms respond in some way - nothing low-level has been touched on our end. I don't know if you have a setup like that already somewhere? i.e. some example where atoms respond to click handlers, and it's visible which atom was clicked?

**Comment by andfaulkner** [comment]
Why the close? It's a pretty serious bug.

I can create a little toy code snippet if you'd like that replicates it. I just wanted to first ask if you already have some sort of test example showing atom responses to click handlers?

**Comment by dkoes** [comment]
Yes, we do have a test for click handling, but it was using a spheres only representation and it turns out the issue was with sticks.  This has now been fixed.

**Comment by andfaulkner** [comment]
Got it. What version is the fix in?

**Comment by dkoes** [comment]
1.6.1

**Comment by andfaulkner** [comment]
Great, I'll upgrade 👍
