### ISSUE TITLE
Expose absolute positions of atoms - i.e. each visible atom's X and Y coordinates on the canvas

### ISSUE THREAD

**Issue by andfaulkner** [3dmol/3Dmol.js#482]
### **Summary**
It'd be extremely helpful if the canvas X and Y coordinates for all visible atoms were available - i.e. if you could get the actual position of each atom on the canvas (even just the position of the centre of the atom would do).

### **Underlying problem & prior attempts to solve it (without atom positions on canvas available)**
In my project, if an atom is ctrl-clicked, it gets "selected," where the atom gets a sphere drawn around it, the atom index gets stored in that molecule viewer instance's state store, and the atom index gets stored in a visible "selected atoms" field (Method 1). You can also select atoms by inputting atom index "ranges" into the "selected atoms field." (Method 2)

However, both existing methods for selection are problematic in many cases. If you need to select a large number of atoms (which is common for us), it's annoying & time-consuming ctrl-clicking them 1-by-1; and if a user needs to select an unusual set of atoms that don't fall under an obvious "range" in the atom indexes, selecting atoms by manually inputting atom ranges in the selected atoms field isn't helpful (also common).

### **Desired solution**
I'm trying to set up a drag-selector, in which if the user holds a special hotkey, clicking and dragging will "draw" a temporary box in the canvas, and any atoms contained within the box on releasing the mouse button will have their onClick handlers triggered, thus "selecting" them.

However, this doesn't seem to currently be possible to manually implement, because the position that the click-and-drag covers is in relation to the mouse's position on the canvas, whereas the position of the atoms on the canvas is unknown.

This would be solvable if atoms exposed their current location on the canvas (i.e. their X and Y coordinates). Even just exposing a single coordinate for each atom that marks where the centre of the atom is would solve the problem, since I could calculate the actual area the atom covers using the atom's known radius. However, the atoms currently don't seem to provide this information, and I can't find any way to extract it that doesn't involve edge detection (infeasible) or modifying 3dmol itself.

### **Screenshots of full viewer + visual depiction of intended solution**
Baseline 3dmol-wrapping molecule viewer (no atoms selected):
![molecule-viewer--no-atoms-selected](https://user-images.githubusercontent.com/7527436/99496180-d1899580-2941-11eb-8813-a41a56ea0a89.png)

Viewer with random set of atoms selected by ctrl-clicking them one-by-one:
![molecule-viewer-random-atoms-selected](https://user-images.githubusercontent.com/7527436/99496298-fe3dad00-2941-11eb-8d57-7e81871797c1.png)

Viewer with atoms selected by inputting a range into the highlight atoms box:
![molecule-viewer-atoms-selected-by-range-w-note](https://user-images.githubusercontent.com/7527436/99497828-76a56d80-2944-11eb-88ae-abf2d5c2731e.png)

Viewer with atoms selected in a cluster, also by ctrl-clicking them one-by-one:
![molecule-viewer-atom-cluster-selected](https://user-images.githubusercontent.com/7527436/99496988-3a254200-2943-11eb-8585-919b51d844d1.png)

Desired selection method:
![molecule-viewer-atom-cluster-selected-by-click-and-drag](https://user-images.githubusercontent.com/7527436/99497473-f7b03500-2943-11eb-962a-2d644e41aa55.png)

(Again, the only thing I need here is access to each atom's "absolute" position - the above screenshots just outline the problem I intend to solve using each atom's X and Y coordinates on the canvas)

**Comment by dkoes** [comment]
In the above commit I've added a convenience function for converting between model coordinates and screen coordinates.  This should let you implement region selections (when they mouse down get the screen coordinates for any atoms of interest and then as the mouse moves add/subtract atoms from the selection as required).  Let me know if you run into any problems.

**Comment by andfaulkner** [comment]
@dkoes This is amazing, it perfectly solves my problem, and is precisely what I was looking for. Thanks so much!

FYI I locally built and installed it from your commit, and confirmed the fix is working with no issues. I was able to get atom coordinates (on the canvas) by calling `_this.viewer.modelToScreen`.

**Comment by andfaulkner** [comment]
Note: looks like I'll also need #483 to implement the click-and-drag selection feature referenced above.

**Comment by andfaulkner** [comment]
This is working 👍
