### ISSUE TITLE
Allow temporarily blocking mouse click-and-drag from moving the camera

### ISSUE THREAD

**Issue by andfaulkner** [3dmol/3Dmol.js#483]
### Summary
It'd be really useful to be able to temporarily block clicking and dragging from rotating, translating, or zooming the scene -  i.e. to have some sort of mechanism to freeze and unfreeze the camera as needed.

### Underlying problem
See issue #482 for more detailed explanation.

In short, I'm trying to set up selection of atoms by clicking-and dragging to draw a box that then selects any atoms that fall within the bounds of that box. However, without being able to lock the camera while doing the click-and-drag, it won't be an especially useful feature (since the atoms you're trying to select would end up moving too).

### Desired solution
It'd be great to have a method on `GLViewer` instances that allows freezing and unfreezing the camera (say, `viewer.setCameraFrozen`, although any name is fine).
- Calling `viewer.setCameraFrozen(true);` would lock the camera, stopping it from moving on click-and-drag.
- Calling `viewer.setCameraFrozen(false);` would unlock the camera again, allowing it to move on click-and-drag again.

### Prior attempts (without ability to freeze & unfreeze the camera available)
1. I tried playing around with the `nomouse` config option, but there doesn't seem to be a way to change it after initial instantiation of `GLViewer`. I was able to freeze the camera permanently on initialization by putting `nomouse: false` in the config object for GLViewer (ViewerSpec), but there didn't seem to be a way to unfreeze it after that.

2. I considered storing the current camera rotation on initial click, then on each `mousemove` event, forcibly resetting the camera to that original rotation. However, this is ugly, unintuitive, slow, and causes weird visual effects in the view...when it's possible to get it to work at all. Behaviour varies depending on the exact computing environment:
-   With small molecules on very fast machines with nothing else running, it looks like it's repeatedly rotating slightly then snapping back to the original position.
-   With large molecules on slow machines with lots of other processes running, it just hangs or stops registering mouse dragging altogether.

3. I looked into freezing the camera permanently on initial render, then having all click and drag events call manual camera changing methods in the `GLViewer` instance (such as `viewer.rotate`, `viewer.translate`, `viewer.zoom`, and `viewer.setInternalState`) as long as the camera isn't frozen. However, it's really difficult to make the behaviour act as expected (and it'd be a lot of duplicated effort to redo something already present in 3dmol).

### Screenshots of full viewer + visual depiction of desired behaviour
Recap of desired atom selection method this is being used for (from issue #482):
![molecule-viewer-atom-cluster-selected-by-click-and-drag](https://user-images.githubusercontent.com/7527436/99497473-f7b03500-2943-11eb-962a-2d644e41aa55.png)

This isn't possible if there's no way to temporarily freeze and unfreeze the camera.

**Comment by dkoes** [comment]
The way to do this is to initialize with nomouse and then install your own handlers on the canvas object.  The 3Dmol.js handlers are available for you to wrap (although a bit hidden since this is an advanced feature).

```
let canvas = $(viewer.getCanvas());
//you will write your own handlers that call the defaults as needed
canvas.bind('mousedown touchstart', viewer._handleMouseDown);
canvas.bind('DOMMouseScroll mousewheel', viewer._handleMouseScroll);
canvas.bind('mousemove touchmove', viewer._handleMouseMove);
```

**Comment by andfaulkner** [comment]
```
canvas.bind('mousedown touchstart', viewer._handleMouseDown);
canvas.bind('DOMMouseScroll mousewheel', viewer._handleMouseScroll);
canvas.bind('mousemove touchmove', viewer._handleMouseMove);
```
Exactly what I need, thank you! 👍 

This is a good feature - IMHO it's definitely worth exposing and adding to the documentation, rather than having it hidden in a set of semi-private handler methods like this.

**Comment by dkoes** [comment]
I've added them to the nomouse documentation.
