### ISSUE TITLE
Problem with atom color options

### ISSUE THREAD

**Issue by knc6** [3dmol/3Dmol.js#485]
**Description**
Hi, 

I have been trying to use 3Dmol.js in JARVIS-DFT.

Is there a documentation for selecting different color options in 3Dmol?

For example, in this Bi2Se3 example, both Bi and Se atomic colors are similar.( https://www.ctcms.nist.gov/~knc6/static/JARVIS-DFT/JVASP-1067)

Your help is greatly appreciated.

**Relevant Context**
![image](https://user-images.githubusercontent.com/16902896/100550898-36e75b80-324b-11eb-9c92-74f2ce34a94d.png)

I am using the following code:

<script>
data="135\n6.2913 -10.89687 0.0 6.2913 10.89687 0.0 0.0 0.0 29.18477\nBi -3.4952 -1.2108 22.3749\nBi -1.3981 2.4215 22.3749\nBi 0.699 6.0538 22.3749\nBi -1.3981 -4.8431 22.3749\nBi 0.699 -1.2108 22.3749\nBi 2.7961 2.4215 22.3749\nBi 0.699 -8.4753 22.3749\nBi 2.7961 -4.8431 22.3749\nBi 4.8932 -1.2108 22.3749\nBi -3.4952 -1.2108 28.2121\nBi -1.3981 2.4215 28.2121\nBi 0.699 6.0538 28.2121\nBi -1.3981 -4.8431 28.2121\nBi 0.699 -1.2108 28.2121\nBi 2.7961 2.4215 28.2121\nBi 0.699 -8.4753 28.2121\nBi 2.7961 -4.8431 28.2121\nBi 4.8932 -1.2108 28.2121\nSe -5.5923 -0.0 0.9728\nSe -3.4952 3.6323 0.9728\nSe -1.3981 7.2646 0.9728\nSe -3.4952 -3.6323 0.9728\nSe -1.3981 -0.0 0.9728\nSe 0.699 3.6323 0.9728\nSe -1.3981 -7.2646 0.9728\nSe 0.699 -3.6323 0.9728\nSe 2.7961 -0.0 0.9728\nSe -3.4952 1.2108 26.6391\nSe -1.3981 4.8431 26.6391\nSe 0.699 8.4753 26.6391\nSe -1.3981 -2.4215 26.6391\nSe 0.699 1.2108 26.6391\nSe 2.7961 4.8431 26.6391\nSe 0.699 -6.0538 26.6391\nSe 2.7961 -2.4215 26.6391\nSe 4.8932 1.2108 26.6391\nSe -5.5923 -0.0 23.9479\nSe -3.4952 3.6323 23.9479\nSe -1.3981 7.2646 23.9479\nSe -3.4952 -3.6323 23.9479\nSe -1.3981 -0.0 23.9479\nSe 0.699 3.6323 23.9479\nSe -1.3981 -7.2646 23.9479\nSe 0.699 -3.6323 23.9479\nSe 2.7961 -0.0 23.9479\nBi -3.4952 1.2108 2.9183\nBi -1.3981 4.8431 2.9183\nBi 0.699 8.4753 2.9183\nBi -1.3981 -2.4215 2.9183\nBi 0.699 1.2108 2.9183\nBi 2.7961 4.8431 2.9183\nBi 0.699 -6.0538 2.9183\nBi 2.7961 -2.4215 2.9183\nBi 4.8932 1.2108 2.9183\nBi -3.4952 1.2108 8.7556\nBi -1.3981 4.8431 8.7556\nBi 0.699 8.4753 8.7556\nBi -1.3981 -2.4215 8.7556\nBi 0.699 1.2108 8.7556\nBi 2.7961 4.8431 8.7556\nBi 0.699 -6.0538 8.7556\nBi 2.7961 -2.4215 8.7556\nBi 4.8932 1.2108 8.7556\nSe -3.4952 -1.2108 10.7011\nSe -1.3981 2.4215 10.7011\nSe 0.699 6.0538 10.7011\nSe -1.3981 -4.8431 10.7011\nSe 0.699 -1.2108 10.7011\nSe 2.7961 2.4215 10.7011\nSe 0.699 -8.4753 10.7011\nSe 2.7961 -4.8431 10.7011\nSe 4.8932 -1.2108 10.7011\nSe -5.5923 -0.0 7.1825\nSe -3.4952 3.6323 7.1825\nSe -1.3981 7.2646 7.1825\nSe -3.4952 -3.6323 7.1825\nSe -1.3981 -0.0 7.1825\nSe 0.699 3.6323 7.1825\nSe -1.3981 -7.2646 7.1825\nSe 0.699 -3.6323 7.1825\nSe 2.7961 -0.0 7.1825\nSe -3.4952 -1.2108 4.4914\nSe -1.3981 2.4215 4.4914\nSe 0.699 6.0538 4.4914\nSe -1.3981 -4.8431 4.4914\nSe 0.699 -1.2108 4.4914\nSe 2.7961 2.4215 4.4914\nSe 0.699 -8.4753 4.4914\nSe 2.7961 -4.8431 4.4914\nSe 4.8932 -1.2108 4.4914\nBi -5.5923 -0.0 12.6466\nBi -3.4952 3.6323 12.6466\nBi -1.3981 7.2646 12.6466\nBi -3.4952 -3.6323 12.6466\nBi -1.3981 -0.0 12.6466\nBi 0.699 3.6323 12.6466\nBi -1.3981 -7.2646 12.6466\nBi 0.699 -3.6323 12.6466\nBi 2.7961 -0.0 12.6466\nBi -5.5923 -0.0 18.4838\nBi -3.4952 3.6323 18.4838\nBi -1.3981 7.2646 18.4838\nBi -3.4952 -3.6323 18.4838\nBi -1.3981 -0.0 18.4838\nBi 0.699 3.6323 18.4838\nBi -1.3981 -7.2646 18.4838\nBi 0.699 -3.6323 18.4838\nBi 2.7961 -0.0 18.4838\nSe -3.4952 1.2108 20.4293\nSe -1.3981 4.8431 20.4293\nSe 0.699 8.4753 20.4293\nSe -1.3981 -2.4215 20.4293\nSe 0.699 1.2108 20.4293\nSe 2.7961 4.8431 20.4293\nSe 0.699 -6.0538 20.4293\nSe 2.7961 -2.4215 20.4293\nSe 4.8932 1.2108 20.4293\nSe -3.4952 -1.2108 16.9108\nSe -1.3981 2.4215 16.9108\nSe 0.699 6.0538 16.9108\nSe -1.3981 -4.8431 16.9108\nSe 0.699 -1.2108 16.9108\nSe 2.7961 2.4215 16.9108\nSe 0.699 -8.4753 16.9108\nSe 2.7961 -4.8431 16.9108\nSe 4.8932 -1.2108 16.9108\nSe -3.4952 1.2108 14.2196\nSe -1.3981 4.8431 14.2196\nSe 0.699 8.4753 14.2196\nSe -1.3981 -2.4215 14.2196\nSe 0.699 1.2108 14.2196\nSe 2.7961 4.8431 14.2196\nSe 0.699 -6.0538 14.2196\nSe 2.7961 -2.4215 14.2196\nSe 4.8932 1.2108 14.2196\n"

  var viewer = $3Dmol.createViewer("geometry", {
    backgroundColor: "white",
  });

  viewer.addModel(data, "xyz");

  viewer.setStyle({ sphere: { radius: 0.7 } });

  viewer.addStyle({ stick: { radius: 0.2 } });
  viewer.zoomTo();
  viewer.setClickable({},true,function(atom,viewer,event,container) {
                       viewer.addLabel(atom.resn+":"+atom.atom,{position: atom, backgroundColor: 'darkgreen', backgroundOpacity: 0.8});
                   });

  viewer.render();
</script>

**Comment by dkoes** [comment]
There are a number of built-in color schemes:
http://3dmol.csb.pitt.edu/doc/types.html#ColorschemeSpec

Jmol has the most distinct colors, including different colors for Se and Bi.  You can also specify your own mapping from elements to colors.  The easiest way to do this is to extend a pre-existing color scheme.

```
var mycolors = $3Dmol.extend({},$3Dmol.elementColors.defaultColors);
mycolors.Bi = 0xffff00;
mycolors.Se = 'silver';
viewer.setStyle({sphere:{colorscheme:{'prop': 'elem', map:mycolors}}});
```

https://3dmol.org/tests/auto/generate_test.cgi?test=testcolormap
