### ISSUE TITLE
Using hover_callback with py3Dmol

### ISSUE THREAD

**Issue by cbouy** [3dmol/3Dmol.js#487]
Hi,

How can I use the `hover_callback` to display some text when hovering an object (a cylinder in my case) when using py3Dmol. I could find examples for 3Dmol.js, but what is the equivalent for py3Dmol ?

```python
view.addCylinder({"start": dict(x=p1.x, y=p1.y, z=p1.z),
                  "end":   dict(x=p2.x, y=p2.y, z=p2.z),
                  "color": colors[interaction_name],
                  "hoverable": True,
                  "hover_callback": None,
                  "unhover_callback": None,
                  "radius": .15,
                  "dashed": True,
                  "fromCap": 1,
                  "toCap": 1,
                 })
```
In my case I'm only interested in displaying what's inside the `interaction_name` variable.

I hope this is doable 🤞
Cédric

**Comment by dkoes** [comment]
Adding support for converting python functions to javascript functions isn't something we're doing to do, but I've added the ability to provide a javascript function as a string for a callback.  See the last example on this page:
https://colab.research.google.com/drive/1T2zR59TXyWRcNxRgOAiqVPJWhep83NV_?usp=sharing

**Comment by cbouy** [comment]
Thanks for the swift reply 👍

I tried the last example both locally (py3Dmol v0.9.1) and on collab but unfortunately I can't see any label.

Upon inspection of the console logs in my browser (Chrome), I get the following message: `Hover_callback is not a function` for `3Dmol.js:32277`, probably because the JS function is directly passed as a string to 3Dmol.js ?

I remember that in bokeh (another python library that relies on JS for plotting), I had to put the JS callback in a `CustomJS` object where you could also give arguments in addition to the code for the function. [Here](https://docs.bokeh.org/en/latest/docs/user_guide/interaction/callbacks.html)'s their documentation, if that helps.

Thank you for your help,
Cédric

**Comment by dkoes** [comment]
Try completely clearing your cache on your browser as well as reloading and running the notebook.  I had trouble too with the newer version of the code not getting picked up until I did this.

**Comment by cbouy** [comment]
That did the trick, thank you!

So the only way to make hovers work in python is through the `setHoverable` method which acts on atoms, right ? It won't work for shapes like the Cylinder in this [example](https://3dmol.csb.pitt.edu/doc/$3Dmol.GLViewer.html#addCylinder) ?

**Comment by dkoes** [comment]
It should work if you provide the string version of the function, but I will admit I did not test it with shapes.

**Comment by cbouy** [comment]
FYI the following, taken from the above link,  doesn't do anything:
```python
import py3Dmol

v = py3Dmol.view(400, 400)
v.setBackgroundColor(0xffffffff)
v.addCylinder({
    "start":{"x":0.0,"y":0.0,"z":0.0},
    "end":{"x":10.0,"y":0.0,"z":0.0},
    "radius":1.0,
    "color":'red',
    "hoverable":True,
    "hover_callback": 'function(){ viewer.render( );}',
    "unhover_callback": 'function(){ this.color.setHex(0xFF000000);viewer.render( );}',
    })
```

Console logs say:
```
Uncaught TypeError: current_hover.unhover_callback is not a function
    at setHover (3Dmol.js:34765)
    at handleHoverContinue (3Dmol.js:34798)
    at HTMLCanvasElement.GLViewer._handleMouseMove._handleMouseMove (3Dmol.js:35101)
    at HTMLCanvasElement.dispatch (3Dmol.js:5429)
    at HTMLCanvasElement.elemData.handle (3Dmol.js:5233)
```

**Comment by cbouy** [comment]
Anyway I managed to add a label to the cylinder by adding a dummy atom to the model, with its position in the middle of the cylinder, and using the style "clicksphere" so it's hidden but still hoverable.

The code looks something like this:
```python

hover_func = """
function(atom,viewer) {
    if(!atom.label) {
        atom.label = viewer.addLabel(atom.customlabel,
            {position: atom, backgroundColor: 'mintcream', fontColor:'black'});
    }
}"""
unhover_func = """
function(atom,viewer) { 
    if(atom.label) {
        viewer.removeLabel(atom.label);
        delete atom.label;
    }
}"""

model = v.getModel()
model.addAtoms([{"elem": 'Z',
                 "x": c.x, "y": c.y, "z": c.z,
                 "customlabel": value}])
model.setStyle({"customlabel": value}, {"clicksphere": {"radius": .5}})
model.setHoverable(
    {"customlabel": value}, True,
    hover_func, unhover_func)
```

**Comment by dkoes** [comment]
There was one other change that had to be made for shapes to work.  Also, the callback needs to get the viewer as an argument:

```
import py3Dmol

v = py3Dmol.view(400, 400,js='http://localhost/3Dmol/build/3Dmol.js')
v.setBackgroundColor(0xffffffff)
v.addCylinder({
    "start":{"x":0.0,"y":0.0,"z":0.0},
    "end":{"x":10.0,"y":0.0,"z":0.0},
    "radius":1.0,
    "color":'red',
    "hoverable":True,
    "hover_callback": 'function(shape,viewer){ shape.color.setHex(0x0000ff); viewer.render( );}',
    "unhover_callback": 'function(shape,viewer){ shape.color.setHex(0x00FF00);viewer.render( );}',
    })
```
