### ISSUE TITLE
How can I display the atomic charge with coloring method as in VMD?

### ISSUE THREAD

**Issue by LZ0211** [3dmol/3Dmol.js#489]
[:surface style:]

**Description**
In order to display the atomic charge more directly, we usually use the charge coloring method to render the molecule structure. The input file format is *.pqr, which is just a PDB file with charge field.
For example below，the antepenultimate column is charge :
```
REMARK
HETATM    1  O   MOL A   1      -2.030   0.000  -0.000  -0.33957515   1.5200 O
HETATM    2  C   MOL A   1      -0.845  -0.000   0.000   0.36693862   1.7000 C
HETATM    3  O   MOL A   1      -0.068   1.100   0.105  -0.19657335   1.5200 O
HETATM    4  C   MOL A   1       1.285   0.755  -0.114  -0.05553065   1.7000 C
HETATM    5  C   MOL A   1       1.285  -0.755   0.114  -0.05533179   1.7000 C
HETATM    6  O   MOL A   1      -0.068  -1.100  -0.105  -0.19670603   1.5200 O
HETATM    7  H   MOL A   1       1.923   1.308   0.588   0.12701495   1.2000 H
HETATM    8  H   MOL A   1       1.569   1.025  -1.145   0.11137415   1.2000 H
HETATM    9  H   MOL A   1       1.569  -1.025   1.146   0.11136246   1.2000 H
HETATM   10  H   MOL A   1       1.923  -1.308  -0.588   0.12702678   1.2000 H
END
```
This is a gradient color scheme based on the atomic charge value and the gradient can be adjusted by setting the upper and lower value of atomic charge.
And how can I use APIs in the 3dmol.js to achieve the same effect as in VMD?

**Relevant Context**
![1](https://user-images.githubusercontent.com/9457118/103146078-3628e300-477f-11eb-953c-fde16909999b.png)

![vmdscene](https://user-images.githubusercontent.com/9457118/103146085-58bafc00-477f-11eb-8c1f-52215839c145.png)

**Comment by dkoes** [comment]
The charge from pqr files is put into the partialCharge property which you can map to colors by specifying a gradient in a colorscheme:
https://3dmol.org/tests/auto/generate_test.cgi?test=testpqrcharge
