### ISSUE TITLE
show legend for gradient color scale

### ISSUE THREAD

**Issue by lidaof** [3dmol/3Dmol.js#492]
Is there a way to show legend for gradient color scale? like a bar showing different colors for the gradient color scheme, with min and max value plotted along with the legend?

Thanks.

**Comment by dkoes** [comment]
No, you would have to implement that yourself as an html element.  You could position a floating div above or next to the canvas with a background gradient (https://www.w3schools.com/css/css3_gradients.asp).

**Comment by dkoes** [comment]
Another option would be to create a label with the backgroundImage property set to a picture of the desired gradient.

**Comment by lidaof** [comment]
Sounds nice.
Thank you for your suggestion!

**Comment by sk-wang** [comment]
A simple example may help you.
`<div class="legend" style="display: flex">

          <div style="width: 50px;height: 80%;background: linear-gradient(blue,Aqua,green,yellow,orange,red);">
          </div>
          <div style="
            height: 84%;
            margin-top: -10px;
            margin-left: 5px;
            text-shadow:1px 1px 1px #000000;
            color:white;
            display: flex;
            flex-direction: column;
            justify-content: space-between;
          ">
            <div>{{maxEsp | formatLegend}}</div>
            <div>{{ ((maxEsp + minEsp) / 2) | formatLegend}}</div>
            <div>{{minEsp | formatLegend)}}</div>
          </div>
        </div>`

**Comment by lidaof** [comment]
thank you @sk-wang !
