### ISSUE TITLE
[BUG] Missing Atoms when Rendering PDB in Sphere Mode

### ISSUE THREAD

**Issue by william-dawson** [3dmol/3Dmol.js#493]
**Describe the bug**
I am trying to render some water molecules in the pdb format using the sphere style. However, when I do so the hydrogen atoms are missing.

**To Reproduce**
This is the py3Dmol code (I apologize if this makes it hard, but I think it can be translated to javascript in a straightforward way)
```
import py3Dmol

file = """HETATM    1 H1   HOH A   0       2.924   3.219   1.550  1.00  0.00       B   H  
HETATM    2 H2   HOH A   0       4.098   2.445   0.948  1.00  0.00       B   H  
HETATM    3 O    HOH A   0       3.850   2.984   1.714  1.00  0.00       B   O  
HETATM    4 H1   HOH A   1       1.432   4.761   0.988  1.00  0.00       B   H  
HETATM    5 H2   HOH A   1       0.066   4.168   0.637  1.00  0.00       B   H  
HETATM    6 O    HOH A   1       0.884   3.972   1.119  1.00  0.00       B   O  
HETATM    7 H1   HOH A   2       2.280   0.928   1.171  1.00  0.00       B   H  
HETATM    8 H2   HOH A   2       0.907   1.567   1.386  1.00  0.00       B   H  
HETATM    9 O    HOH A   2       1.335   0.779   1.019  1.00  0.00       B   O  
HETATM   10 H1   HOH A   3       4.694   4.067   3.659  1.00  0.00       B   H  
HETATM   11 H2   HOH A   3       3.377   4.728   4.071  1.00  0.00       B   H  
HETATM   12 O    HOH A   3       3.945   4.569   3.303  1.00  0.00       B   O """

view = py3Dmol.view(width=400, height=300)
m = view.addModel(file)
view.setStyle({'model': -1}, {'sphere':{}})
view.zoomTo()
view.show()
```

**Expected behavior**
Render the hydrogens, just like they are shown if I use an XYZ file as input instead:
```
import py3Dmol

file = """12
free
H 2.924 3.219 1.55
H 4.098 2.445 0.948
O 3.85 2.984 1.714
H 1.432 4.761 0.988
H 0.066 4.168 0.637
O 0.884 3.972 1.119
H 2.28 0.928 1.171
H 0.907 1.567 1.386
O 1.335 0.779 1.019
H 4.694 4.067 3.659
H 3.377 4.728 4.071
O 3.945 4.569 3.303"""

view = py3Dmol.view(width=400, height=300)
m = view.addModel(file)
view.setStyle({'model': -1}, {'sphere':{}})
view.zoomTo()
view.show()
```

**Screenshots**
Broken using PDB
<img width="250" alt="broken" src="https://user-images.githubusercontent.com/19283177/104299804-fdbc2f80-5508-11eb-9032-f4b3b14f8b26.png">

Working using XYZ
<img width="250" alt="fixed" src="https://user-images.githubusercontent.com/19283177/104299819-03b21080-5509-11eb-8ab4-bf563c7134cb.png">

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]: macOS 11.1
 - Browser [e.g. chrome, safari]: firefox
 - Version [e.g. 22]: The source codes links to https://3dmol.csb.pitt.edu/build/3Dmol.js

**Additional context**
The PDB format supports both trajectories and unit cells, which makes it ideal compared to XYZ. It is also possible that my pdb file has an error in it, though translating back and forth with openbabel didn't change anything.

**Comment by dkoes** [comment]
Hydrogens are suppressed by default for pdb files.  Enable them be passing the keepH option:
`m = viewer.addModel(data, "pdb", {keepH:true});`

**Comment by william-dawson** [comment]
Thank you very much for the quick answer. I tried the option you suggested and everything works great!
