### ISSUE TITLE
[BUG] stick and cartoon~trace display nothing

### ISSUE THREAD

**Issue by lidaof** [3dmol/3Dmol.js#494]
not sure if it's a bug or I am not using 3dmol correctly.....thanks.
my data looks like this:
![image](https://user-images.githubusercontent.com/102806/104541187-a9877d00-55e6-11eb-9146-6d3ef724a76c.png)

The data are ordered, bonds only happen between 2 nearby atoms

I got it displayed ok in `line`, `sphere` style, but not `stick` (maybe too less bonds), or `cartoon` with style set to `trace`, both stick and cartoon~trace display nothing..

can you give some suggestions? thanks!

![image](https://user-images.githubusercontent.com/102806/104541300-fc613480-55e6-11eb-945e-4a340a4bcd09.png)

![image](https://user-images.githubusercontent.com/102806/104541320-06833300-55e7-11eb-933a-255e38286c21.png)

I tested with `assignBonds` from the 3dmol code, seems each atom get more bonds and stick style is working now..but cartoon~trace still nothing.. thanks!

**Comment by dkoes** [comment]
In order to have display a cartoon style you need standard PDB atom names (e.g. CA for alpha carbon) which it doesn't look like you have.

**Comment by lidaof** [comment]
Thanks for fast reply @dkoes 

yeah...this is nucleic data...I tried using atom.atom = 'A' and resn = 'DA' before, not working..
I also tried CA...not sure if I am doing correctly...but still empty display...

![image](https://user-images.githubusercontent.com/102806/104542456-2a477880-55e9-11eb-9a64-fbf9e49770c4.png)

**Comment by dkoes** [comment]
For nucleic acids in needs the phosphorus (P) and oxygens (O2P, O5, O3).  Your best bet is to copy all the standard atom names from a pdb file.

**Comment by lidaof** [comment]
I will try that, thank you so much @dkoes !

**Comment by lidaof** [comment]
tried with following data entry in a pdb format...still no luck -,- followed [this example](http://3dmol.csb.pitt.edu/viewer.html?pdb=1d3l&style=cartoon:style~trace)

![image](https://user-images.githubusercontent.com/102806/104544625-d0957d00-55ed-11eb-924e-bbedc0587128.png)

**Comment by dkoes** [comment]
These are proteins, not nucleic acids.  Are they also all the same chain?  Perhaps if you provided a complete example it would be easier to see what is wrong.

**Comment by lidaof** [comment]
Thank you @dkoes I would really appreciate that! I created a [codesandbox demo here](https://codesandbox.io/s/dazzling-pasteur-1czf7?file=/src/App.js). thank you!!!

**Comment by dkoes** [comment]
You are creating alpha carbon (CA) atoms that are calcium (Ca) not carbon, which is why a trace isn't being displayed.

![Screenshot from 2021-01-14 11-26-30](https://user-images.githubusercontent.com/2342142/104619187-95ca2e00-565b-11eb-81c9-181ce1c9b72d.png)

**Comment by lidaof** [comment]
Thank you @dkoes.
I actually almost know nothing about this...can you please shared the forked codesandbox? thank you much again!

**Comment by dkoes** [comment]
I didn't save it - set elem to 'C', not 'Ca' in your parser.

**Comment by lidaof** [comment]
oh my god, that's a 'easy' fix :)
thank you so much @dkoes!

**Comment by lidaof** [comment]
Hi @dkoes really sorry to bother you again...I have another file with same format, but the x, y, z's are quite different in scale..
using the same code as before only line style can show the data, neither cross, sphere, or cartoon~trace show anything.
would you mind take a look [the demo](https://codesandbox.io/s/dazzling-pasteur-1czf7?file=/src/App.js) again? thank you so much in advance!

**Comment by dkoes** [comment]
The trace isn't displaying because the distance between residues is much longer that is expected between protein/nucleic residues.  The spheres are there, but you can't see them because the default radius is too small.  I question whether 3Dmol.js is the right choice for you since it assumes you are providing molecular data (i.e., with typical bond lengths and scales).
