### ISSUE TITLE
add isosurface with colorful style

### ISSUE THREAD

**Issue by sk-wang** [3dmol/3Dmol.js#495]
<img width="382" alt="56e653d189e850c1ed935f4d9f3297c" src="https://user-images.githubusercontent.com/14271914/105014209-1d100b00-5a7b-11eb-90e3-1edb883afc0d.png">
Hi 3dmol! May I add the iso Surface just like the picture above, currently I could just apply solid color like the image below by using the code

 `this.viewer.addIsosurface(voldata, {isoval: 0.01, color: "blue", alpha: 0.8, smoothness: 10})`

![image](https://user-images.githubusercontent.com/14271914/105014460-6e1fff00-5a7b-11eb-9997-c98c99ebd9d6.png)

cheer!

**Comment by dkoes** [comment]
An isosurface by definition is the surface with all the same value.  I think what you want to do is color the molecular surface by the grid value at the surface location.  You do this by providing a volume data object and coloring scheme when creating the surface.
http://3dmol.csb.pitt.edu/doc/types.html#SurfaceStyleSpec

Example:
http://3dmol.org/tests/auto/generate_test.cgi?test=testSurfaceVolData

**Comment by sk-wang** [comment]
> An isosurface by definition is the surface with all the same value. I think what you want to do is color the molecular surface by the grid value at the surface location. You do this by providing a volume data object and coloring scheme when creating the surface.
> http://3dmol.csb.pitt.edu/doc/types.html#SurfaceStyleSpec
> 
> Example:
> http://3dmol.org/tests/auto/generate_test.cgi?test=testSurfaceVolData

Sorry about my bad description coz my poor chemistry knowledge . Actually I want to do is to create an isosurface that has same value (e.g. 0.001)  from the file "density.cub" which is the electron density of a molecule, and to color pixel on the isosurface with corrensponding value from the file "esp.cub" which is the spatial distribution of electrostatic potential, These file is all output by Multiwfn. I try to providing the file "density.cub" to the method "addSurface" but failed. Maybe I should do some others :(.

Here is the link of the files [https://drive.google.com/drive/folders/1W5uw6dwxJy0E11K4W_KLyLNHqXS4Va31?usp=sharing](url)

**Comment by TsingXu430** [comment]
I still have this question

**Comment by dkoes** [comment]
How did you provide the density information to addSurface?  You should be able to use the example I provided as a template.

Coloring an isosurface using different volume data than was used to create the isosurface wasn't supported, but I've added this feature:
http://3dmol.org/tests/auto/generate_test.cgi?test=testIsoColorbyDensity

**Comment by sk-wang** [comment]
> How did you provide the density information to addSurface? You should be able to use the example I provided as a template.
> 
> Coloring an isosurface using different volume data than was used to create the isosurface wasn't supported, but I've added this feature:
> http://3dmol.org/tests/auto/generate_test.cgi?test=testIsoColorbyDensity

This commit real helps me a lot! I'm grateful and give thanks to you!!! I would add your link on my site
![image](https://user-images.githubusercontent.com/14271914/105334975-78283600-5c12-11eb-9956-4783e66a41a0.png)
