### ISSUE TITLE
How to color by residue ID

### ISSUE THREAD

**Issue by pschmidtke** [3dmol/3Dmol.js#497]
Hi, 

do you have any example on how to color a chain of a protein by a colorscheme on the residue id? 

Thanks
Peter

**Comment by dkoes** [comment]
There are a number of ways to specify a colorscheme.  The most flexible is to provide a colorfun function as shown in the documentation:
https://3dmol.csb.pitt.edu/doc/types.html#ColorschemeSpec

If you want a numerical mapping you would specify a gradient for your desired (numerical) property.

If you want a discrete mapping you provide a map (a dictionary from property value to color).

**Comment by pschmidtke** [comment]
Sorry can't figure that out, I'm trying this for py3Dmol I have to admit; 

basically I want to color all residues (from 1 to 20) with a different color of chain C from a structure. 
Currently I have something like that: 

viewer.setStyle({'chain':'C'},{'line':{'color':{'prop': {'resi',d}}}})
where d is a dictionary of values and colors (1:"red"). Does it eat #FF0000 or no dictionaries are admitted? 

thanks for the help!

**Comment by dkoes** [comment]
Here are some examples:
https://colab.research.google.com/drive/1GY3e3ExY-8kFtSGglgI4vfMWtavTuNya?usp=sharing

**Comment by pschmidtke** [comment]
Ahhh thanks you made my day.

**Comment by pschmidtke** [comment]
finally a colored bubbly look ;)

![image](https://user-images.githubusercontent.com/15227239/106808719-09fc5e00-666b-11eb-9382-86086df4a7e8.png)
