### ISSUE TITLE
Use 3Dmol.js in R language

### ISSUE THREAD

**Issue by swsoyee** [3dmol/3Dmol.js#499]
Hello, thank you for the awesome library you have developed!

I find it slightly complicated for the R user to use the JavaScript library in an R environment. So in order to facilitate users who have the need to visualize molecular data in R, I developed an R package based on `3Dmol.js` named `{r3dmol}`.
(see: https://github.com/swsoyee/r3dmol)

I don't have an academic background in molecular structure myself, so I'm not quite sure if it's useful.

**Comment by dkoes** [comment]
This looks great!  I'm not an R person - does this need to run inside a specific environment (e.g. Jupyter/Rstudio)?

**Comment by swsoyee** [comment]
@dkoes Thank you for your reply!
> Does this need to run inside a specific environment (e.g. Jupyter/Rstudio)?

You could use it in any situation, including the pure R environment (you still need a browser to view the output but that would not be a problem), RStudio, `{rmarkdown}` (something like Jupyter Notebook in Python) and `{shiny}` (dash in Python?)
In addition, embedding the structure into a html document or a blog could be very easy (https://swsoyee.github.io/r3dmol/articles/r3dmol.html)
