### ISSUE TITLE
Integrate with JSmol for file parsing

### ISSUE THREAD

**Issue by dkoes** [3dmol/3Dmol.js#5]
Use JSmol as a subcomponent to translate different file types.

**Comment by ghutchis** [comment]
I could probably help set up an Open Babel web service as an alternative.

**Comment by dkoes** [comment]
Changing tactics to openbabel.js so this is a much lower priority issue.

**Comment by ghutchis** [comment]
Is there an easy way to factor into openbabel.js + xyzformat.js or something like this?

**Comment by dkoes** [comment]
Not sure what you are asking.  Justin has a javascript built version of openbabel that will convert to json.  The plan is to fallback to this if we encounter a format we don't understand and if it has been loaded.
