### ISSUE TITLE
Expose absolute radii (in pixels) of displayed atom spheres

### ISSUE THREAD

**Issue by andfaulkner** [3dmol/3Dmol.js#501]
### Summary
To allow selection of atoms with a bounding box that overlaps only the edge of a displayed atom (and not the centre), the displayed atom spheres' absolute radii (in pixels) need to be exposed (alongside the coordinates of the centre point of the atom, as already implemented here: #482)

### Underlying problem
The atoms in my 3DMol-derived application are currently highlightable via click-and-drag, such atoms are selected if the bounding box overlaps the centre of the atom. However, click-and-drag is now required to select atoms if any portion of the atom at all is overlapped by the bounding box, but because the atom radii (measured in pixels) aren't exposed, so it's near-impossible (or at least very difficult) to determine where the edge of the atom is.

### Desired solution
If the (camera state-dependent) absolute atom radii in pixels (i.e. not the current configurable atom radii values) were exposed alongside the absolute atom coordinates (See #482), it would be easy to determine if the bounding box overlapped any piece of the displayed atom.

### Alternatives
I've tried looking for other ways to get the radii or to infer them from existing exposed data, I couldn't find anything feasible.

### Screenshots of current and required selection conditions
Current selection condition - notice bounding box overlaps the centre of the atom:
![current_selection_condition](https://user-images.githubusercontent.com/7527436/107479164-bac19c00-6b48-11eb-8d96-5ec897a1a82e.png)

Required selection condition - notice bounding box only intersects a small portion of the edge of the atom:
![required_selection_condition](https://user-images.githubusercontent.com/7527436/107479209-cc0aa880-6b48-11eb-8674-dab220e5c9ff.png)

To implement the latter, the absolute displayed atom radii (in pixels) are required.

### Additional context
As mentioned above, closely related to #482.

**Comment by dkoes** [comment]
I've made the helper function screenOffsetToModel public and given it an option to take a model z-coordinate.  This takes an XY screen _displacement_ and returns the analogous displacement in model space. This should let you implement the desired behavior. Pseudocode:

```
C = atom center
S = viewer.modelToScreen(C)
if S in box:
 atom is selected
else
 pt = closest point on box to S
 xyz = viewer.screenOffsetToModel(pt.x-S.x,pt.y-S.y,atom.z)
if length(xyz) < radius of atom:
  atom is selected
```

This function wasn't originally written for this use case so it's possible I've missed something in my reasoning.  Let me know how it works (be sure to test at different zoom levels).

e611be47

**Comment by andfaulkner** [comment]
Thanks! I'll get back to you in a few days once I have the chance to test it out.

(Apologies for the latency, I was recently derailed by a semi-emergency security-related problem)

**Comment by andfaulkner** [comment]
`screenOffsetToModel` seems to return values that don't adjust for the zoom level and all of the camera characteristics. They're consistently closer values to what I'm looking for than the actual screen coordinates (generally much smaller values), but still not quite right: generally too large by a factor of 1.1-6 (depending on the zoom level), then too small if zoomed out really, really far. It's the same general pattern as if I were compared the defined atomic radius value against the distance in screen coordinates, but with a much smaller gap.

Here's my implementation code:

```
type Coord2D = {x: number; y: number};

/**
 * Return list of atoms that the bounding box should select (returns indexes).
 */
const getSelectedAtomIdxes = (
    allAtoms: AtomSpec[],
    atomCoords: Coord2D[], // S[]
    box: {start: Coord2D; end: Coord2D}
): number[] => {
    const selAtomIdxs = [] as number[];

    /**
     * atomC = S; atomC.x = S.x; atomC.y = S.y
     */
    atomCoords.forEach((atomC, idx) => {
        // If box covers centre of atom, highlight it and return.
        if (isAtomInSelBox(atomC, box)) {
            return selAtomIdxs.push(idx);
        }

        //
        // Detect if box intersects atom sphere but not centre.
        //

        const closestX = clampNum(atomC.x, box.start.x, box.end.x); // pt.x
        const closestY = clampNum(atomC.y, box.start.y, box.end.y); // pt.y

        const atom = allAtoms[idx];
        const xyz = viewer.screenOffsetToModel(closestX - atomC.x, closestY - atomC.y, atom.z);

        const atomToBoxPtDist = xyz.length();
        
        // Note: I use custom atomic radii, maybe that's the issue?
        const atomRadius = config.atomRadiuses[atom.atom];

        if (atomToBoxPtDist < atomRadius) selAtomIdxs.push(idx);
    });

    return selAtomIdxs;
};
```

And as referenced above, here's clampNum (it's a fairly standard `clamp`) and atomRadiuses:

```
/**
 * Limit [val] to a number between given values [min] and [max].
 * Technically allows reversing min and max.
 *
 * Example:
 *     clampNum(1, 5, 10); // => 5
 *     clampNum(7, 5, 10); // => 7
 *     clampNum(12, 5, 10); // => 10
 *     clampNum(-7, 5, -3); // => -3
 */
const clampNum = (value: number, min: number, max: number) => {
    const cleanMin = min < max ? min : max;
    const cleanMax = max > min ? max : min;
    if (value <= cleanMin) return cleanMin;
    if (value >= cleanMax) return cleanMax;
    return value;
};

const atomRadiuses = {
    H:  0.25,
    He: 0.275,
    Li: 0.3,
    // ...etc - continues for all atoms we'd ever conceivably use... //
};
```

I'm not sure if I'm missing something obvious in there, or if `screenOffsetToModel` is just returning values that don't match exactly what I need

**Comment by andfaulkner** [comment]
@dkoes FYI I updated the example to include a fair bit of missing info. It's still somewhat pseudocode, since I use a much larger structure in my actual application, but I've made it clearer where certain values come from.

They've also been mapped to the letters you used in your pseudocode for clarity.

**Comment by dkoes** [comment]
Well, so much for re-using an existing function.  I've added screenToModelDistance which takes a screen coordinate and model coordinate (e.g. an atom) and returns the distance between them assuming the screen coordinate is projected to the same depth as as the model coordinate.  This works correctly at different zoom levels and rotations.

**Comment by andfaulkner** [comment]
@dkoes Great, I'll give this a try. Seems promising.

**Comment by andfaulkner** [comment]
@dkoes Do you have an example of how to use it? The result values I'm getting are definitely incorrect (they're way, way too large), but I'm not sure I'm feeding the right data in - I was calling it like:
`screenToModelDistance(coordinates of position on screen in pixels, coordinates of atom in angstroms);`

For example:
`screenToModelDistance({x: 800, y: 375}, {x: 1.2, y: 1.5, z: 2.3});`

Also, what do you mean by this:
>assuming screen point  is projected to the same depth as model coordinate

**Comment by dkoes** [comment]
The result are correct.  This test does modelToScreen and then screenToModelDistance and turns the molecule green if the distance is zero:
http://3dmol.org/tests/auto/generate_test.cgi?test=testcoordconvert

The origin for screen coordinates is the top left. Perhaps the problem?

You want a distance between a 2D point and a 3D point.  This is underdetermined as the 2D point can be projected along the z-axis of the screen to form a ray.  We need to pick a point along this ray to compute a distance to, so I pick the point that is in the same z-plane (relative to the screen, not model z) as the model coordinate.

**Comment by dkoes** [comment]
Can I close this issue?

**Comment by andfaulkner** [comment]
@dkoes I was actually never able to translate usage of the screenToModelDistance function into the ability to detect whether a selection area's bounding box defined in screen pixels overlaps any part of an atom sphere.

I'll take another crack at it now and get back to you.

**"The origin for screen coordinates is the top left. Perhaps the problem?"**
Top-left of the screen, or of the canvas?
