### ISSUE TITLE
the positions of top left or bottom left corner of the canvas

### ISSUE THREAD

**Issue by lidaof** [3dmol/3Dmol.js#505]
Hi,

Is there a way to get the positions of top left or bottom left corner of the canvas?
I am trying to put a label there regardless of zooming..also seems set `fixed` doesn't make any difference?
Thanks in advance.
code:
```js
viewer.addLabel("Aromatic", {
                        position: { x: 0, y: 0, z: 0 },
                        backgroundColor: 0x800080,
                        backgroundOpacity: 0.8,
                        inFront: true,
                        fixed: true,
                    });
```

**Comment by dkoes** [comment]
The useScreen option was missing from the documentation (which I've fixed).  If set to true it will treat position as screen coordinates:
https://3dmol.csb.pitt.edu/tests/auto/generate_test.cgi?test=testlabelscreen

**Comment by lidaof** [comment]
very helpful! thank you @dkoes
