### ISSUE TITLE
[BUG]embedded data-backgroundcolor property not allowing transparency.

### ISSUE THREAD

**Issue by LucioAmely** [3dmol/3Dmol.js#506]
**Describe the bug**
While using embedded 3Dmol.js, I have tried to get a transparent background as described in your docs by using these methods:

`data-backgroundcolor='000000ee'`
`data-backgroundcolor='000000,0.5'`
`data-backgroundtransparency='0.5'`
`data-showbackground='false'`

but none of them worked.

**To Reproduce**
Try using the codes written above and getting background transparency.

**Expected behavior**
Background should have transparency.

**Comment by dkoes** [comment]
This is because the alpha background property wasn't exposed to the embeddable API.  I have added it.  You can set it with data-backgroundalpha
https://3dmol.csb.pitt.edu/tests/auto/generate_test.cgi?test=testbackalpha
