### ISSUE TITLE
[BUG] Antialiasing seems broken on linux

### ISSUE THREAD

**Issue by Luthaf** [3dmol/3Dmol.js#512]
**Describe the bug**

The same code creates the following images, respectively on macOS (top) and linux (botom)

<img width="302" alt="macos" src="https://user-images.githubusercontent.com/6141587/115250007-77c40c00-a129-11eb-8f88-aa3c71c341ef.png">
<img width="302" alt="linux" src="https://user-images.githubusercontent.com/6141587/115250003-7692df00-a129-11eb-85fd-9bde2e274f66.png">

While the antialiasing is good on macOS, it does not seems to work on the linux machine. This issue is particularly visible for small canvas.

I've tried this on both Firefox and Chrome on both OS, and they all use the same hardware (native macOS, VM for linux). 

One possible difference is that the linux VM is using WebGL 1 rendering, while the macOS version uses WebGL 2. Another possibility is that both OS are rendering a high-DPI/retina screen, but only macOS knows about it. I'm doubting that these are the core issues since @ceriottm is also seeing the same bad antialiasing running ubuntu natively, with WebGL2 enabled.

Finally saving the content of the canvas to a png, it looks like 3Dmol itself is producing the exact same image, and most of the difference comes from how the browser then downsample and render this image.

**To Reproduce**

Load the HTML below

<details>

```

<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Antialias test</title>

    <script src="https://3Dmol.org/build/3Dmol-min.js"></script>
  </head>
  <body>
    <div
      id="viewer"
      style="
        width: 300px;
        height: 300px;
        margin: auto;
        position: relative;
        border: solid thin black;
      "
    ></div>
  </body>
  <script>
    const atoms = [
      {
        serial: 0,
        elem: "C",
        x: 0.2,
        y: 1.2,
        z: 0.7,
        bonds: [1, 5, 4, 3],
        bondOrder: [1, 1, 1, 1],
      },
      {
        serial: 1,
        elem: "C",
        x: 0.3,
        y: 0.4,
        z: 1.9,
        bonds: [0, 2, 6],
        bondOrder: [1, 1, 1],
      },
      {
        serial: 2,
        elem: "O",
        x: 1.3,
        y: 0.3,
        z: 2.6,
        bonds: [1],
        bondOrder: [1],
      },
      {
        serial: 3,
        elem: "H",
        x: -0.7,
        y: 1.9,
        z: 0.7,
        bonds: [0],
        bondOrder: [1],
      },
      {
        serial: 4,
        elem: "H",
        x: 0.1,
        y: 0.5,
        z: -0.2,
        bonds: [0],
        bondOrder: [1],
      },
      {
        serial: 5,
        elem: "H",
        x: 1.1,
        y: 1.8,
        z: 0.6,
        bonds: [0],
        bondOrder: [1],
      },
      {
        serial: 6,
        elem: "N",
        x: -0.8,
        y: -0.4,
        z: 2.3,
        bonds: [7, 10, 1],
        bondOrder: [1, 1, 1],

        color: 3166456,
      },
      {
        serial: 7,
        elem: "C",
        x: -2.1,
        y: -0.6,
        z: 1.5,
        bonds: [6, 11, 12, 8],
        bondOrder: [1, 1, 1, 1],
      },
      {
        serial: 8,
        elem: "C",
        x: -3.1,
        y: 0.6,
        z: 1.7,
        bonds: [9, 29, 7],
        bondOrder: [1, 1, 1],
      },
      {
        serial: 9,
        elem: "O",
        x: -4.1,
        y: 0.6,
        z: 1,
        bonds: [8],
        bondOrder: [1],
      },
      {
        serial: 10,
        elem: "H",
        x: -0.7,
        y: -1,
        z: 3.1,
        bonds: [6],
        bondOrder: [1],
      },
      {
        serial: 11,
        elem: "H",
        x: -1.9,
        y: -0.5,
        z: 0.4,
        bonds: [7],
        bondOrder: [1],
      },
      {
        serial: 12,
        elem: "C",
        x: -2.7,
        y: -1.9,
        z: 1.8,
        bonds: [7, 13, 19, 20],
        bondOrder: [1, 1, 1, 1],
      },
      {
        serial: 13,
        elem: "C",
        x: -3.1,
        y: -2.2,
        z: 3.2,
        bonds: [12, 14, 21, 22],
        bondOrder: [1, 1, 1, 1],
      },
      {
        serial: 14,
        elem: "C",
        x: -4.5,
        y: -1.7,
        z: 3.7,
        bonds: [13, 23, 24, 15],
        bondOrder: [1, 1, 1, 1],
      },
      {
        serial: 15,
        elem: "N",
        x: -5.6,
        y: -2.2,
        z: 2.9,
        bonds: [16, 25, 14],
        bondOrder: [1, 1, 1],

        color: 3166456,
      },
      {
        serial: 16,
        elem: "C",
        x: -6.8,
        y: -1.5,
        z: 2.6,
        bonds: [15, 17, 18],
        bondOrder: [1, 1, 1],
      },
      {
        serial: 17,
        elem: "N",
        x: -6.6,
        y: -0.2,
        z: 2.4,
        bonds: [16, 26, 27],
        bondOrder: [1, 1, 1],

        color: 3166456,
      },
      {
        serial: 18,
        elem: "N",
        x: -7.9,
        y: -2.2,
        z: 2.7,
        bonds: [16, 28],
        bondOrder: [1, 1],

        color: 3166456,
      },
      {
        serial: 19,
        elem: "H",
        x: -2,
        y: -2.7,
        z: 1.5,
        bonds: [12],
        bondOrder: [1],
      },
      {
        serial: 20,
        elem: "H",
        x: -3.6,
        y: -2.1,
        z: 1.1,
        bonds: [12],
        bondOrder: [1],
      },
      {
        serial: 21,
        elem: "H",
        x: -2.4,
        y: -1.9,
        z: 4,
        bonds: [13],
        bondOrder: [1],
      },
      {
        serial: 22,
        elem: "H",
        x: -3.1,
        y: -3.3,
        z: 3.4,
        bonds: [13],
        bondOrder: [1],
      },
      {
        serial: 23,
        elem: "H",
        x: -4.5,
        y: -0.6,
        z: 3.6,
        bonds: [14],
        bondOrder: [1],
      },
      {
        serial: 24,
        elem: "H",
        x: -4.6,
        y: -1.9,
        z: 4.8,
        bonds: [14],
        bondOrder: [1],
      },
      {
        serial: 25,
        elem: "H",
        x: -5.8,
        y: -3.2,
        z: 3.1,
        bonds: [15],
        bondOrder: [1],
      },
      {
        serial: 26,
        elem: "H",
        x: -5.8,
        y: 0.1,
        z: 1.8,
        bonds: [17],
        bondOrder: [1],
      },
      {
        serial: 27,
        elem: "H",
        x: -7.5,
        y: 0.3,
        z: 2.1,
        bonds: [17],
        bondOrder: [1],
      },
      {
        serial: 28,
        elem: "H",
        x: -8.7,
        y: -1.6,
        z: 2.3,
        bonds: [18],
        bondOrder: [1],
      },
      {
        serial: 29,
        elem: "N",
        x: -2.9,
        y: 1.4,
        z: 2.7,
        bonds: [8, 30, 31],
        bondOrder: [1, 1, 1],

        color: 3166456,
      },
      {
        serial: 30,
        elem: "C",
        x: -3.8,
        y: 2.5,
        z: 3.1,
        bonds: [29, 32, 33, 34],
        bondOrder: [1, 1, 1, 1],
      },
      {
        serial: 31,
        elem: "H",
        x: -2.1,
        y: 1.3,
        z: 3.3,
        bonds: [29],
        bondOrder: [1],
      },
      {
        serial: 32,
        elem: "H",
        x: -4.3,
        y: 2.9,
        z: 2.1,
        bonds: [30],
        bondOrder: [1],
      },
      {
        serial: 33,
        elem: "H",
        x: -3.3,
        y: 3.3,
        z: 3.5,
        bonds: [30],
        bondOrder: [1],
      },
      {
        serial: 34,
        elem: "H",
        x: -4.6,
        y: 2.1,
        z: 3.7,
        bonds: [30],
        bondOrder: [1],
      },
    ];

    window.addEventListener("DOMContentLoaded", (event) => {
      const viewer = $3Dmol.createViewer("viewer", {
        antialias: true,
        defaultcolors: $3Dmol.elementColors.Jmol,
        disableFog: true,
        orthographic: false,
      });

      const model = viewer.addModel();
      model.addAtoms(atoms);
      model.setStyle(
        {},
        {
          sphere: {
            scale: 0.22,
          },
          stick: {
            radius: 0.15,
          },
        }
      );

      viewer.zoomTo();
      viewer.zoom(0.8, 0);
      viewer.render();
    });
  </script>
</html>
```

</details>

**Expected behavior**

Both OS should have the same anti-aliasing behavior. I'm not sure how much control we have on this though =|. I would appreciate any pointer/idea you have to improve the final rendering!

**Desktop (please complete the following information):**

- macOS 10.14.6, Firefox 87 & Chrome 92
- Ubuntu 18.04, Firefox 87 & Chrome 89

**Comment by dkoes** [comment]
I'm always running linux and I don't see this.  If you go to https://webglreport.com/ does anything suspicious pop up (e.g. software rendering or lack of antialiasing support)?  Here's my output:
```


Platform:	Linux x86_64
Browser User Agent:	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.72 Safari/537.36
Context Name:	webgl2
GL Version:	WebGL 2.0 (OpenGL ES 3.0 Chromium)
Shading Language Version:	WebGL GLSL ES 3.00 (OpenGL ES GLSL ES 3.0 Chromium)
Vendor:	WebKit
Renderer:	WebKit WebGL
Unmasked Vendor:	Google Inc. (NVIDIA Corporation)
Unmasked Renderer:	ANGLE (NVIDIA Corporation, GeForce GTX 750 Ti/PCIe/SSE2, OpenGL 4.5.0 NVIDIA 460.32.03)
Antialiasing:	Available
ANGLE:	No
Major Performance Caveat:	No

```

**Comment by Luthaf** [comment]
Looks like I have Antialiasing disabled =/ I'll check how I can workaround this.

```
Platform: 	Linux x86_64
Browser User Agent: 	Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:87.0) Gecko/20100101 Firefox/87.0
Context Name: 	webgl
GL Version: 	WebGL 1.0
Shading Language Version: 	WebGL GLSL ES 1.0
Vendor: 	Mozilla
Renderer: 	Mozilla
Unmasked Vendor: 	VMware, Inc.
Unmasked Renderer: 	SVGA3D; build: RELEASE; LLVM;
Antialiasing: 	Not available
ANGLE: 	No
Major Performance Caveat: 	No
```

**Comment by Luthaf** [comment]
But on @ceriottim machine antialising is enabled ... This is really strange!

```
Platform:	Linux x86_64
Browser User Agent:	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.72 Safari/537.36
Context Name:	webgl2
GL Version:	WebGL 2.0 (OpenGL ES 3.0 Chromium)
Shading Language Version:	WebGL GLSL ES 3.00 (OpenGL ES GLSL ES 3.0 Chromium)
Vendor:	WebKit
Renderer:	WebKit WebGL
Unmasked Vendor:	Google Inc. (Intel)
Unmasked Renderer:	ANGLE (Intel, Mesa Intel(R) UHD Graphics 620 (KBL GT2), OpenGL 4.6 (Core Profile) Mesa 20.2.6)
Antialiasing:	Available
ANGLE:	No
Major Performance Caveat:	No
```

**Comment by ceriottm** [comment]
I suspect the issue here might be that antialiasing is enabled but "weak" so the structure looks "jagged" as if antialiasing were off
![image](https://user-images.githubusercontent.com/1118823/115270863-0beb9e80-a13d-11eb-885f-44ff4ce3f7b8.png)

**Comment by dkoes** [comment]
Is this only on high def resolution monitors?  Do you see the same problems on 3dmol.org (i.e., is this unique to your setup)?

**Comment by ceriottm** [comment]
I think you may be honing in on the problem. It is definitely more evident on a retina display.
This is from a hi-def display
![image](https://user-images.githubusercontent.com/1118823/115271962-2bcf9200-a13e-11eb-9cea-75fdc0176181.png)

**Comment by ceriottm** [comment]
and this a normal monitor
![image](https://user-images.githubusercontent.com/1118823/115272035-3db13500-a13e-11eb-9f9e-291b8094cd0b.png)

**Comment by dkoes** [comment]
This is most likely my fault, based on this comment (that I wrote) in renderer.js:
```
        //with antialiasing on (which doesn't seem to do much), render at double rsolution to eliminate jaggies
	//my iphone crashes if we do though, so as a hacky workaround, don't do it with retina displays
        if(_antialias && this.devicePixelRatio < 2.0) this.devicePixelRatio *= 2.0;
```
I'm guessing your `window.devicePixelRatio` is >= 2.0.

**Comment by ceriottm** [comment]
So, indeed window.devicePixelRatio is 2.0, and if I reduce it to 1.0 (and get blind in the process of writing this comment), situation gets way better!
![image](https://user-images.githubusercontent.com/1118823/115282437-853dbe00-a14a-11eb-9b57-f0f1d20dcf73.png)

**Comment by Luthaf** [comment]
> my iphone crashes if we do though, so as a hacky workaround, don't do it with retina displays

I guess this crash comes from requiring too much processing power? Is this still the case nowadays? I have an old-ish iphone (5s from 2013) on which I can run some tests if that helps. 

Alternatively, we could change the test to check for phones with high-DPI screens directly (using something like the screen size or user agent to know if the browser is running in a phone). If you have a preferred resolution, I can send a PR!

**Comment by ceriottm** [comment]
> Alternatively, we could change the test to check for phones with high-DPI screens directly (using something like the screen size or user agent to know if the browser is running in a phone). If you have a preferred resolution, I can send a PR!

Checking whether this is being used on a mobile device seems the most sensible heuristics to me. A modern desktop can handle the oversampling.

**Comment by dkoes** [comment]
It may not even be an issue anymore.  I'm preoccupied with putting together a lecture on 3D Steerable CNNs right now, but will look at this in depth in a couple days.

**Comment by dkoes** [comment]
FYI, I have confirmed this is still a problem on iOS with Safari (webpage crashes).  Interestingly, Chrome on iOS works fine.  It looks like if I set the antialias property of the GL context to false, the problem goes away and I don't see a visual difference.  I need to rustle up a few more different machines/browsers/display types and test this before committing though (specifically my macbook needs to get back from repair and there's a hidef screen at work I want to test on).

**Comment by dkoes** [comment]
Fix: 788bc6
Please verify this works.

**Comment by ceriottm** [comment]
I confirm 3dmol.js now antialiases properly also on a HiRes display.
![Untitled](https://user-images.githubusercontent.com/1118823/116917781-66155500-ac4f-11eb-9cb8-b216938b170a.png)
This is now almost identical to the rendering on a normal pixel density display. 
Thanks a lot!
