### ISSUE TITLE
Support `position` in `addResLabels`

### ISSUE THREAD

**Issue by swsoyee** [3dmol/3Dmol.js#518]
Hi, I would like to know if it is possible to provide the `position` option in `addResLabels` so that the Label can be further away from the atoms.

In the documentation of [`LabelSpec`](https://3dmol.csb.pitt.edu/doc/types.html#LabelSpec), the `position` option is supported.

But in [`addResLabels`](https://3dmol.csb.pitt.edu/doc/$3Dmol.GLViewer.html#addResLabels), the `position` seems to be re-assign in the function: https://github.com/3dmol/3Dmol.js/blob/bb653fa0cc9d940b78d5c61d7a7390ff3dab471c/3Dmol/glmodel.js#L2742-L2750

Please let me know if I have misunderstood the source code of `3Dmol.js`. Also I would like to know if this feature can be implemented.

Related issue: https://github.com/swsoyee/r3dmol/issues/36

**Comment by lidaof** [comment]
Hi @dkoes recently found the warning message `$3Dmol.Material: 'screenOffset' parameter is undefined.` probably due to this change? didn't see this before..

**Comment by dkoes** [comment]
I think `screenOffset` resolves this issue so am closing.
