### ISSUE TITLE
Preserve viewpoint and zoom when updating view / changing frames in ipywidgets interact?

### ISSUE THREAD

**Issue by cvjjm** [3dmol/3Dmol.js#519]
I am interested in using 3DMol's  python interface in conjunction with ipywidgets' `interact`. 

The following minimal example creates a working interactive view in a jupyter notebook of two geometries and the slider allows to switch between those geometries. Unfortunately the viewpoint always resets when changing the frame with the slider.
```
import py3Dmol
from ipywidgets import interact

xyzs = '''3

    O 0.0 0.0 0.0
    H 1.0 0.0 0.0
    H 0.0 1.0 0.0
    3

    O 0.0 0.0 0.0
    H 1.2 0.0 0.0
    H 0.0 0.8 0.0
    '''

xyzview = py3Dmol.view()
xyzview.addModelsAsFrames(xyzs,'xyz')
xyzview.setStyle({'sphere':{'radius':0.5}})
xyzview.setBackgroundColor('0xeeeeee')
#xyzview.zoomTo()
#xyzview.setFrame(0)

def drawit(idx=0):
    xyzview.setFrame(idx)
    return xyzview.show()

interact(drawit, idx=(0, 1))
```
It would be great if there was a way to change the displayed geometry and update what  is shown by interact without changing the point of view and zoom level chosen by the user with their mouse.

Is there a way to achieve this with 3dmol?

**Comment by cvjjm** [comment]
I mised .update()!

This does the trick:
```
import py3Dmol
from ipywidgets import interact

xyzs = '''3

    O 0.0 0.0 0.0
    H 1.0 0.0 0.0
    H 0.0 1.0 0.0
    3

    O 0.0 0.0 0.0
    H 1.2 0.0 0.0
    H 0.0 0.8 0.0
    '''

xyzview = py3Dmol.view()
xyzview.addModelsAsFrames(xyzs,'xyz')
xyzview.setStyle({'sphere':{'radius':0.5}})
xyzview.setBackgroundColor('0xeeeeee')
xyzview.zoomTo()
xyzview.setFrame(0)
xyzview.show()

def drawit(idx=0):
    xyzview.setFrame(idx)
    return xyzview.update()

interact(drawit, idx=(0, 1))
```
Maybe worth adding this to the documentation?

**Comment by dkoes** [comment]
Glad you figured it out.  I've added `update` to the example colab notebook, but unfortunately it doesn't work because colab appears to sandbox the JavaScript environments of individual cells.  It works for your application though since it is still all in one cell.
