### ISSUE TITLE
like addShape, is it possible to add a 2D canvas (addCanvas)

### ISSUE THREAD

**Issue by lidaof** [3dmol/3Dmol.js#521]
Like adding any shape, is it possible to add 2D canvas as well? so in the 2d canvas can draw anything, lines,  images etc.
Thanks for consideration.

**Comment by dkoes** [comment]
Do you want the canvas to be attached in someway like a label?  You can set the background image of a label in this case to have a picture.  Otherwise, if you want something floating in a position fixed relative to the viewer you can do this yourself in HTML/CSS.

**Comment by lidaof** [comment]
Nice, thank you @dkoes. I missed the background image setting in the labelSpec. I will try this approach.

**Comment by lidaof** [comment]
Hi @dkoes, do you happen to have an example of this? I tried search the codebase but didn't find any.
I am trying to do something like click a button and load a remote image, pseudo code:

```js
const img = new Image();
img.alt = alt;
img.width = 100;
img.height = 100;
// console.log(img);
img.addEventListener("load", () => {
    atoms.forEach((atom) => {
            this.viewer.addLabel("", {
                position: { x: atom.x, y: atom.y, z: atom.z },
                backgroundImage: img,
            })
    });
});
document.body.appendChild(img);
img.src = imageInfo.thumbnail;
```
error:

![image](https://user-images.githubusercontent.com/102806/120273893-b8f52300-c274-11eb-874d-2305ad67c7f9.png)


I guess I didn't handle image load event correctly...but not sure how to fix it...if I didn't call the addLabel on the event callback, there is no error but image is not loaded, just black box there.

thanks in advance.
