### ISSUE TITLE
Rotate the shape object

### ISSUE THREAD

**Issue by qzhu2017** [3dmol/3Dmol.js#525]
**Is your feature request related to a problem? Please describe.**
I am wondering if there is a way to rotate the shape objects like `cylinder` and `box`. Currently, it looks like these objects will be aligned with a principle axes that are parallel to x, y, z. However, sometimes we want to rotate it. For instance, in the following figure I created a magenta box via `pymol3d`. But what I really want is to have a box that can bind the inner molecule.

<img width="266" alt="image" src="https://user-images.githubusercontent.com/29445366/124299873-c5d69200-db12-11eb-8cab-df0244b6d201.png">

**Describe the solution you'd like**
To do so, we just need to supply a 3*3 rotation matrix, which should be defined by the user. By defult, it can be the identity (i.e. [[1,0,0], [0,1,0], [0,0,1]])

```python
view.addBox({'center':{'x':xyz[0],'y':xyz[1],'z':xyz[2]},
             'dimensions': {'w':7.08, 'h': 7.18, 'd': 3.40},
             'rotation': np.eye(3), #here we define the rotation matrix
             'color':'magenta',
             'alpha': 0.5,
            })
```

**Comment by dkoes** [comment]
As it says in the documentation (https://3dmol.org/doc/types.html#BoxSpec), the dimensions can be vector quantities if you want a non-axis aligned box. Apply your rotation matrix to your dimensions and you should get the desired effect.

**Comment by qzhu2017** [comment]
Thanks. What is the right format to pass the vector? I tried the following, but it does not work

```python
import py3Dmol
import numpy as np

view = py3Dmol.view(500, 400)
view.addBox({'center':{'x':0,'y':0,'z':0},
             #'dimensions': {'w':1, 'h': 1, 'd': 1}, #scalars
             'dimensions': {'w': [1, 1, 0], #np.array([1,1,0]), 
                            'h': [1, -1, 0], #np.array([1,-1,0]), 
                            'd': [0, 0, 1], #np.array([0,0,1]),
                           },
             'color':'magenta',
             'alpha': 0.5,
            })
view.zoomTo()
```

**Comment by qzhu2017** [comment]
Okay, I think I figured out how to do it. I am putting some sample script here, in case someone else may be interested.

```python
import py3Dmol

view = py3Dmol.view(500, 400)
view.addBox({'center':{'x':0,'y':0,'z':0},
             #'dimensions': {'w':1, 'h': 1, 'd': 1}, #scalars
             'dimensions': {'w': {'x':1, 'y':1, 'z':0}, #[1, 1, 0], #np.array([1,1,0]), 
                            'h': {'x':1, 'y':-1, 'z':0}, #[1, -1, 0], #np.array([1,-1,0]), 
                            'd': {'x':0, 'y':0, 'z':1}, #[0, 0, 1], #np.array([0,0,1]),
                           },
             'color':'magenta',
             'alpha': 0.5,
            })
view.zoomTo()
```
<img width="277" alt="image" src="https://user-images.githubusercontent.com/29445366/124341437-39a78780-db71-11eb-8b3f-d51ccbb7eeaf.png">
