### ISSUE TITLE
py3dmol - missing (?) metadata element in IPython.display.publish_display_data() call

### ISSUE THREAD

**Issue by psychemedia** [3dmol/3Dmol.js#526]
In trying to get `py3dmol` running in [JupyterLite](https://jupyterlite.readthedocs.io/en/latest/) (JupyerLab in the browser using WASM) [[issue](https://github.com/jupyterlite/jupyterlite/issues/264) and [resolution](https://github.com/jupyterlite/jupyterlite/pull/269)], the way the *3dmol.js* widget is rendered using the `IPython.display.publish_display_data()` function (eg https://github.com/3dmol/3Dmol.js/blob/bb653fa0cc9d940b78d5c61d7a7390ff3dab471c/py3Dmol/py3Dmol/__init__.py#L145 ) caused a rendering issue due to the payload metadata element not being set. This may ultimately be an issue with how `IPython.display.publish_display_data()` is handled (the [docs](https://ipython.readthedocs.io/en/stable/api/generated/IPython.display.html#IPython.display.publish_display_data) don't seem to *require* that the `metadata` attribute is set) but I mention it in case it's an issue for anyone else working with `py3dmol` in other Jupyter environments. And maybe as something that could be added to the `publish_display_data()` call if other higher level display options of the form `display(obj, raw=True)` are not appropriate for rendering the widget.

**Comment by dkoes** [comment]
Fixed in 0.9.2.
