### ISSUE TITLE
extract an isosurface for an `isoval` value

### ISSUE THREAD

**Issue by giammi56** [3dmol/3Dmol.js#532]
Dear all,

I am using `py3Dmol` based on `3Dmol.js` to read and plot a `.cube` file. When I plot an isosurface with `addVolumetricData`, I'd like to export the filtered values according to a specific `isoval` as a list/array for further processing.

A very basic code example is the following:

```
import py3Dmol as p3d
v_lumo = p3d.view(width=600, height=600)
v_lumo.addVolumetricData(cube_homo, "cube", {"isoval": -0.03, "color": "red", "opacity": 0.75})
```

How con I access the isosurfarce?

**Comment by dkoes** [comment]
This is not possible.  There is no communication from the javascript side back to the python side.  This is an intentional design choice to ensure saved notebooks (or notebooks converted to slides) have the exact same functionality even if there is no active kernel.

**Comment by giammi56** [comment]
Thanks. How would you extract these data? Would be possible to export them perhaps?

**Comment by dkoes** [comment]
It is not possible in python.  Within javascript you could extract the vertices and faces from within the geo object with the shape, but there is no public API for getting this information.
