### ISSUE TITLE
parameters to make sphere smooth

### ISSUE THREAD

**Issue by lidaof** [3dmol/3Dmol.js#535]
Hi,

I am wondering is it possible to make the sphere (out circle) more smooth? (which parameters etc.)
Thank you!
![image](https://user-images.githubusercontent.com/102806/131385634-1543778d-424b-434b-a5be-dd29dfb7ee4a.png)

**Comment by dkoes** [comment]
Unfortunately this isn't user configurable.  If you are using your own checkout of the code you can change the value of sphereQuality in gldraw.js.  Alternatively, you can draw sphere's using atoms styled as spheres.

**Comment by lidaof** [comment]
Hi @dkoes, thank you for the reply. Seems using atom then style as sphere works much better! Thanks again!
