### ISSUE TITLE
no release the workers, the browser memory group up too much

### ISSUE THREAD

**Issue by dumplings** [3dmol/3Dmol.js#540]
https://github.com/3dmol/3Dmol.js/blob/f57a8a14a39d8c463804d839fa3e3bb2808bc46b/3Dmol/glviewer.js#L4262

i have a pull request, how could i merge this. https://github.com/3dmol/3Dmol.js/pull/539

**Comment by dkoes** [comment]
You wait for me to wake up so I can review the pull request.
