### ISSUE TITLE
PDB load without figures

### ISSUE THREAD

**Issue by skytguuu** [3dmol/3Dmol.js#543]
Hi,

I tried to use my downloaded PDF file to view the figure, however, it failed without nothing showed. The followed is my code:

#######################################
<!DOCTYPE html>
<html>
<head>

<script src="https://3Dmol.csb.pitt.edu/build/3Dmol-min.js"></script>
</head>
<body>
<div id="container-01" class="mol-container"></div>
<style>
.mol-container {
  width:    75%;
  height:   400px;
  position: relative;
}
</style>
<script>
   	let element = $("#container-01");
    let config = { backgroundColor: "white"};
    let viewer = $3Dmol.createViewer(element, config);
  	let pdbfile = 'HMDB0000001_3D.pdb';
    jQuery.ajax( pdbfile, { 
      success: function(data) {
        let v = viewer;
        v.addModel( data, "pdb" );                       /* load data */
        v.zoomTo();                                      /* set camera */
        v.render();                                      /* render scene */
      },
      error: function(hdr, status, err) {
        console.error( "Failed to load PDB " + pdbfile + ": " + err );
      },
    });
})
</script>
</body>
</html>
################################

Could you give me a hand?

Thanks,
Best

**Comment by skytguuu** [comment]
The PDB file is as followed:

COMPND    HMDB0000001
HETATM    1  C1  UNL     1      -3.796   0.445   0.629  1.00  0.00           C  
HETATM    2  N1  UNL     1      -2.514   0.203  -0.021  1.00  0.00           N  
HETATM    3  C2  UNL     1      -2.183   0.573  -1.270  1.00  0.00           C  
HETATM    4  N2  UNL     1      -0.908   0.172  -1.517  1.00  0.00           N  
HETATM    5  C3  UNL     1      -0.423  -0.452  -0.432  1.00  0.00           C  
HETATM    6  C4  UNL     1       0.936  -1.064  -0.234  1.00  0.00           C  
HETATM    7  C5  UNL     1       1.869   0.008   0.337  1.00  0.00           C  
HETATM    8  N3  UNL     1       1.918   1.071  -0.610  1.00  0.00           N  
HETATM    9  C6  UNL     1       3.175  -0.636   0.568  1.00  0.00           C  
HETATM   10  O1  UNL     1       3.318  -1.590   1.369  1.00  0.00           O  
HETATM   11  O2  UNL     1       4.284  -0.181  -0.116  1.00  0.00           O  
HETATM   12  C7  UNL     1      -1.445  -0.425   0.502  1.00  0.00           C  
HETATM   13  H1  UNL     1      -3.871   1.544   0.770  1.00  0.00           H  
HETATM   14  H2  UNL     1      -4.572   0.061  -0.061  1.00  0.00           H  
HETATM   15  H3  UNL     1      -3.836  -0.097   1.584  1.00  0.00           H  
HETATM   16  H4  UNL     1      -2.812   1.101  -1.972  1.00  0.00           H  
HETATM   17  H5  UNL     1       1.366  -1.374  -1.195  1.00  0.00           H  
HETATM   18  H6  UNL     1       0.830  -1.920   0.436  1.00  0.00           H  
HETATM   19  H7  UNL     1       1.452   0.383   1.293  1.00  0.00           H  
HETATM   20  H8  UNL     1       1.997   0.794  -1.591  1.00  0.00           H  
HETATM   21  H9  UNL     1       2.420   1.913  -0.321  1.00  0.00           H  
HETATM   22  H10 UNL     1       4.174   0.322  -0.970  1.00  0.00           H  
HETATM   23  H11 UNL     1      -1.382  -0.852   1.506  1.00  0.00           H  
CONECT    1    2   13   14   15
CONECT    2    3   12
CONECT    3    4    4   16
CONECT    4    5
CONECT    5    6   12   12
CONECT    6    7   17   18
CONECT    7    8    9   19
CONECT    8   20   21
CONECT    9   10   10   11
CONECT   11   22
CONECT   12   23
END

########################
And there is my code:

![image](https://user-images.githubusercontent.com/25957174/144748757-47a3e850-4318-46f1-9196-e6e7afb417a3.png)

Thanks!

**Comment by dkoes** [comment]
The cartoon visualization style won't show anything if the molecule isn't protein/DNA.  Use stick or sphere.

**Comment by skytguuu** [comment]
Thanks for your promptly response. However, when I tried to load the protein one pdb file. It showed nothing again. The followed is the part of pdf file:

![image](https://user-images.githubusercontent.com/25957174/144751013-519098d0-df09-4e14-9fe2-41ef51f1c63e.png)

Another question is, how can I change to stick or sphere? Is a example of script I can followed?

I am appreciated for your help.
Thanks!

**Comment by dkoes** [comment]
Please stop posting images instead of useful text/data files.  Documentation is here:
https://3dmol.org/doc/tutorial-code.html

**Comment by skytguuu** [comment]
Sorry for posting, I have tried the original code from "https://3dmol.org/doc/tutorial-code.html". I used "1ycr.pdb" file to run the example's code. However, it failed again with nothing showed. Is there another problem in my code? Another question is, can I use viewer.addSphere( data, "pdb" ) to run the pdb file?

Thank you so much!
Best

**Comment by dkoes** [comment]
What errors are being reported in the console? What is your code? addSphere does not take molecular data - it creates a sphere.

**Comment by dkoes** [comment]
https://3dmol.org/doc/$3Dmol.GLViewer.html#setStyle

**Comment by skytguuu** [comment]
It did not report error, but the chrome showed nothing. My code is:

<!DOCTYPE html>
<html>
<head>

<script src="https://3Dmol.csb.pitt.edu/build/3Dmol-min.js"></script>
</head>
<body>
<div id="container-01" class="mol-container"></div>
<style>
.mol-container {
  width:    75%;
  height:   400px;
  position: relative;
}
</style>
<script>
$(function() {
  let viewer = $3Dmol.createViewer( element, config );
  let pdbUri = '1ycr.pdb';
  jQuery.ajax( pdbUri, { 
    success: function(data) {
      let v = viewer;
      v.addModel( data, "pdb" );                       /* load data */
      v.setStyle({}, {cartoon: {color: 'spectrum'}});  /* style all atoms */
      v.zoomTo();                                      /* set camera */
      v.render();                                      /* render scene */
      v.zoom(1.2, 1000);                               /* slight zoom */
    },
    error: function(hdr, status, err) {
      console.error( "Failed to load PDB " + pdbUri + ": " + err );
    },
  });
});
</script>
</body>
</html>

**Comment by dkoes** [comment]
When I look at the console I get a `Uncaught ReferenceError: element is not defined` error, which makes sense because you are using an undefined element variable.  If you lack experience with web programming, perhaps the div embedding API would be more appropriate for your needs:
https://3dmol.org/doc/tutorial-embeddable.html

**Comment by skytguuu** [comment]
Hi,

Thanks for your help. It worked when I set the element and config. But it still failed in the molecule which isn't protein/DNA. I tried to use "viewer.addSphere" and it worked when the information is based on "xyz", but it failed in other formats like PDB. I am wondering that is the function "viewer.addSphere" only support "xyz" format? 

Thanks so much!
Best

**Comment by dkoes** [comment]
`addSphere` doesn't take molecular data.  It creates a sphere.  You use `setStyle` to apply styles such as sphere, line, stick, cartoon to molecular data.
https://3dmol.org/doc/$3Dmol.GLViewer.html#setStyle
https://3dmol.org/doc/types.html#AtomStyleSpec

**Comment by skytguuu** [comment]
Hi, 

I am appreciated for your help. Finally, it worked. 

Thanks!
