### ISSUE TITLE
Add ability to start animation from a provided frame number

### ISSUE THREAD

**Issue by andfaulkner** [3dmol/3Dmol.js#545]
**Problem**
We deal with a lot of xyz files with a large number of frames, and our users would like to be able to pause them at a specific frame. Currently this doesn't seem to be possible, because the `viewer.animate` function doesn't accept a start frame number to run from, and appears to always set the frame to the first when started, regardless of what frame a model is set to before the animation is started.

**Desired solution**
Add the ability to start `viewer.animate` from a given frame number. Alternatively, add option to start `animate` from the current frame number.

**Alternate approaches**
I've tried 3 other approaches to this:

1. Setting the current frame to the frame it was "paused" on, directly _before_ running the animation. This seems to always get reset to the first frame once the animation is started again.
2. Setting the current frame to the frame it was "paused" on, directly _after_ running the animation. This seems to still run the animation from the start frame, if just creates a "flash" display of the model at the prior frame.
3. Eschewing animate altogether and just forcibly incrementing the frame and rerendering using setInterval. This sort of works, but it's brittle for a variety of reasons (mainly that it skips frames with larger molecules and/or on slower machines if the interval isn't long enough; and it's slower than `viewer.animate`).

**Comment by andfaulkner** [comment]
Rough solution that works locally: https://github.com/3dmol/3Dmol.js/pull/546

**Comment by dkoes** [comment]
startFrame is is 2.0
