### ISSUE TITLE
Models get clipped on the sides/distorted when FOV is set to 60 (or higher values)

### ISSUE THREAD

**Issue by SrinivasPrabhu794** [3dmol/3Dmol.js#548]
Loading an SDF, in 3dmol.js with default viewer settings work fine. But, if we change the FOV settings, using `viewer.setCameraParameters()` to lets say {fov: 60} then the model is clipped on the sides and appear extremely distorted/broken when zoomed into. I have observed this not only in my example but also in official examples as well. Why does this happen?

I am attaching a few screenshots below:

My example (Fov 20): Everything looks fine
![image](https://user-images.githubusercontent.com/817112/148539627-d479fdbe-67ba-4172-b892-9eb91da88599.png)

My example (Fov 60):  Observe the red circles where the model is clipped 
![image](https://user-images.githubusercontent.com/817112/148539749-59285272-b851-4790-b595-215537e99ace.png)

Also, distortion is observed when the model is zoomed upon
![image](https://user-images.githubusercontent.com/817112/148539875-9f2daff9-bb46-4cd7-9c69-61f33f976edb.png)

You can see the live example here: (Fov 60)
https://rift-peppermint-catfish.glitch.me/

Tested on:
 - OS: Windows
 - Browser: Chrome/Firefox

If you could let me know if there is any other setting that I am missing please let me know.
Regards,
Srinivas

**Comment by SrinivasPrabhu794** [comment]
Hi @dkoes, it seems like you are the main contributor to this project. If you have any insights about the issue I mentioned above it will be great!

Thanks!

**Comment by dkoes** [comment]
Hopefully the above fix resolves the issue, although you are going to see weirdness, especially with large FOV, when zoomed in a lot.

**Comment by dkoes** [comment]
I'm going to assume this is fixed and close.
