### ISSUE TITLE
Creating models with specific identifiers

### ISSUE THREAD

**Issue by akampen** [3dmol/3Dmol.js#553]
**Problem**
I'm finding it difficult to keep track of the ID of each model (so that I can remove/edit them). In my application, I have 10+ molecules that each have a unique identifier (ex. `"c-232"`). When I'm creating models for each of these molecules, it seems like I have 2 options:
(1) create them on the viewer using `addModel`, in which case I am stuck with the ascending model ids 0,1,2,... that do not correlate to my identifiers. Seems like there's no setter for `id` and it's a private var.
(2) create models unattached from the viewer using `new $3Dmol.GLModel`, but then I can't add them to the viewer because `viewer.models` is private

**Proposed Solution**
I think a solution to this could take one of two forms:
(1) a `viewer.addModel` method that also accepts `id` as an input parameter
(2) a `viewer.addModel` method that accepts an already created model object (I could create this object with my desired ID)

**Alternatives**
The alternative I considered is keeping a dictionary mapping my identifiers to their 3Dmol model identifiers, but this seems like it could be better fixed by being able to control the model identifiers directly.

Is there a better way to handle this issue or is this feature currently missing?

**Comment by dkoes** [comment]
The intention is not to use numerical ids to reference models, but the model object itself.  The support for a number is only there as a hack to let py3Dmol reference model objects (python doesn't "see" javascript objects).  If you want to refer to models by strings, I would maintain a mapping from the string to the model object itself (not a number).

**Comment by akampen** [comment]
Ah okay, thanks for the information on this! I've started maintaining the map from the string to the model object and it's working well. Closing this issue
