### ISSUE TITLE
Add a requestAnimationFrame callback to the GLViewer.animate function

### ISSUE THREAD

**Issue by RyanGuild** [3dmol/3Dmol.js#558]
Must be implemented after #557 

*as:* a develper
*while:* animating an element
*desire:* pass a function as an argument to [GLViewer.animate](https://github.com/3dmol/3Dmol.js/blob/master/3Dmol/glviewer.js#L3258) be called each frame

# Description
Testing animations stably requires that we can count the number of animation frames accurately this can only be achieved in the same micro-task is to call a cb from inside the requestAnimationFrame call. 

## old system
![animatelabels](https://user-images.githubusercontent.com/27573422/153951846-106cdf40-749d-4805-b3af-5b9ad9f01e5e.png)
## new system
![glcheck-tests-render-tests-animatelabels html](https://user-images.githubusercontent.com/27573422/153951892-a5a6d3b5-d542-4ed0-876c-8a8fdeb684ee.png)

# Potential solution
add `{ animationFrameCallback: () => void }` to the GLViewer.animate function options

**Comment by dkoes** [comment]
This was not needed to test and the test images are always for the end of the animation.  Can the issue be closed?

**Comment by dkoes** [comment]
Can use state and/or view change callbacks if you really want detailed inspection.
