### ISSUE TITLE
Adding an externally supplied mesh [py3dmol]

### ISSUE THREAD

**Issue by ljmartin** [3dmol/3Dmol.js#573]
Hi all, 
Just a question on usage (with py3dmol specifically) - how does one add a pre-calculated triangular mesh, given vertices and face indices? 

I got as far as finding the `addMesh` method, which appears to take a `$3Dmol.Mesh` object - but I can't figure out how to create such an object. I have vertices (shape `(npts, 3)`) and faces (shape `(ntriangles, 3)`) as numpy arrays. A trivial example might be a spherical mesh:

```
import numpy as np
from skimage.measure import marching_cubes
from scipy.spatial.distance import cdist

pt = np.array([[2.5,2.5,2.5]])
a,b,c = np.meshgrid( np.linspace(0,5),
                   np.linspace(0,5),
                   np.linspace(0,5))
grid_pts = np.vstack([a.flatten(), b.flatten(), c.flatten()]).T
scalar_grid = cdist(pt, grid_pts)[0].reshape(a.shape)

vertices, faces, _,_ = marching_cubes(scalar_grid, 1)

import py3Dmol
view = py3Dmol.view()

#view.addMesh ???

view
```

An alternative might be to provide the scalar grid via a `.dx` or `.cube` file, which I think could be done via [mdanalysis gridData ](https://www.mdanalysis.org/GridDataFormats/gridData/overview.html), and let 3dmol.js run marching cubes.

Thank you very much!

**Comment by dkoes** [comment]
`addMesh` isn't really for public consumption and probably shouldn't have even documented.  Use `addCustom`, and example of which can be found here:
https://3dmol.org/tests/auto/generate_test.cgi?test=test40

**Comment by ljmartin** [comment]
Great, thanks @dkoes. This works nicely:
```python
import numpy as np
from skimage.measure import marching_cubes
from scipy.spatial.distance import cdist

pt = np.array([[2.5,2.5,2.5]])
a,b,c = np.meshgrid( np.linspace(0,5),
                   np.linspace(0,5),
                   np.linspace(0,5))
grid_pts = np.vstack([a.flatten(), b.flatten(), c.flatten()]).T
scalar_grid = cdist(pt, grid_pts)[0].reshape(a.shape)

vertices, faces, normals,_ = marching_cubes(scalar_grid, 1)
vertices -=vertices.mean(0)

import py3Dmol
view = py3Dmol.view()


def vec_to_dict(a, labels="xyz"):
    return dict(zip(labels,a))

view.addCustom({"vertexArr": [vec_to_dict(v) for v in vertices.astype(float)],
                    "faceArr": [int(x) for f in faces for x in f],
                "normalArr": [vec_to_dict(v) for v in -1*normals.astype(float)],
                    "color": "blue",
                    }) 
```
