### ISSUE TITLE
how can I select the box and move, rotate, zoom in by dragging with the mouse? Thanks

### ISSUE THREAD

**Issue by shubihu** [3dmol/3Dmol.js#576]
![image](https://user-images.githubusercontent.com/36021958/159407576-625c3d63-a8f7-4354-a4ee-e08e32d09bff.png)

**Comment by shubihu** [comment]
Thank you very much for your reply! I have another question.
when I use 3dmol.js ,I can get every atom's information(x、y、z coordinate etc) like this
```
let element = $('#container-01');
let config = { backgroundColor : 'white' };
let pdbUri = '1xdn.pdbqt';
let viewer = $3Dmol.createViewer( element, config );
let v = viewer;
v.addModel( pdbUri , "pdb" );                       /* load data */     
v.setStyle({}, {cartoon: {color: 'spectrum'}});  /* style all atoms */
var atoms = v.selectedAtoms({});
let len = atoms.length;
for (var i = 0; i < len; i++) {
        let atom = atoms[i];
        let x = atom.x;
        let y = atom.y;
        let z = atom.z;
```
but when I use py3Dmol , I get nothing 
```
view = py3Dmol.view(width=800,height=800)
view.addModel(pdb,'pdb', {'keepH':True})
# view.addAsOneMolecule(pdb,'pdb', {'keepH':True})

view.selectedAtoms({})   ## return a view object not aotms info
view.getModel().selectedAtoms() ## not atoms info
```
So, how can I get atoms info in py3Dmol . Thanks

**Comment by dkoes** [comment]
You can't.  All information is one-way form python to javascript.  This is by design as there is no requirement that there be an active python kernel for py3Dmol to work (e.g., exported html/slides will work just fine).

**Comment by shubihu** [comment]
OK, how about the center of protein , can I get the center coordinate in py3Dmol?

**Comment by dkoes** [comment]
No.  You can get absolute zero information from JavaScript into Python.  Use prody or other python package if you want to analyze proteins in python (showProtein in prody will use py3Dmol to visualize proteins if it is imported).

**Comment by shubihu** [comment]
OK, Thank you very much .
