### ISSUE TITLE
falling back to pdb format 3Dmol-nojquery.js?2573:11429 Uncaught DOMException: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.     at Object.$3Dmol.base64ToArray

### ISSUE THREAD

**Issue by ouyang-lang** [3dmol/3Dmol.js#583]
my code
 import('jquery').then(($) => {
    console.log("jquery",$("#container").val());
    import("3dmol/build/3Dmol-nojquery.js").then(($3Dmol) => {
      console.log("$3Dmol",$3Dmol);
      var viewer = $3Dmol.createViewer($("#container"));
      $3Dmol.download("pdb:4DM7",viewer,{},function(){
        viewer.setBackgroundColor(0xffffffff);
        viewer.addArrow({
          start: {x:-10.0, y:0.0, z:0.0},
          end: {x:0.0, y:-10.0, z:0.0},
          radius: 1.0,
          radiusRadio:1.0,
          mid:1.0,
          clickable:true,
          callback:function(){
            this.color.setHex(0xFF0000FF);
            viewer.render( );
          }
        });
        viewer.render();
      });
    })
  });

After I write the code according to the official website, it shows atOB coding error, I don't know how to solve it, why?

**Comment by dkoes** [comment]
What is an "atOB" coding error?  Do you have jquery and 3dmol is appropriate places so that import can find them?

**Comment by ouyang-lang** [comment]
import('jquery').then(($) => {
    console.log("jquery",$("#container").val());
    import("../../3dmol.js/build/3Dmol-nojquery.js").then(($3Dmol) => {
      console.log("$3Dmol",$3Dmol);
      let viewer = $3Dmol.createViewer('container');
      console.log('$3Dmol.download',$3Dmol.download)
      $3Dmol.download('pdb:2nbd',viewer,{onemol: true,multimodel: true},function(m) {
          m.setStyle({'cartoon':{colorscheme:{prop:'ss',map:$3Dmol.ssColors.Jmol}}});
         viewer.zoomTo();
         viewer.render(callback);
        });
      })
    })

This is my code, is it wrong to say d3.download after import? Sorry, I am new, the error is “Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded”

**Comment by ouyang-lang** [comment]
Hello, can't, and open the link to show 404, error:
DevTools failed to load SourceMap: Could not load content for https://3dmol.csb.pitt.edu/build/netcdfjs.js.map:  HTTP error: status code 404,

**Comment by dkoes** [comment]
can't what?  What link? source maps aren't required - that message can be ignored.

**Comment by neuro3d** [comment]
To doubly clarify, I wondered if it was related to this issue, which I suspect given the timing?

**Comment by neuro3d** [comment]
Oh actually, doesn't work on iOS either now.

**Comment by dkoes** [comment]
I'd moved autoload earlier in the page render process, but with async set, this meant that it was waiting for an event that had already happened.  It should be fixed now. The inconsistent results you saw earlier were likely due to caching.  Be sure to clear caches before testing.

**Comment by neuro3d** [comment]
Thank you! Everything works now!
