### ISSUE TITLE
Rotate box around an axis

### ISSUE THREAD

**Issue by shubihu** [3dmol/3Dmol.js#585]
Hi, when I create the axis and a box, how can I rotate the cube box around an axis like X? Thanks.
```
viewer.addLine({color:'red',start:{x:0,y:0,z:0},end:{x:5,y:0,z:0}});
viewer.addLine({color:'blue',start:{x:0,y:0,z:0},end:{x:0,y:5,z:0}});
viewer.addLine({color:'green',start:{x:0,y:0,z:0},end:{x:0,y:0,z:5}});

viewer.addBox({center:{x:0,y:0,z:0},
                         dimensions:  {'w': {'x':1, 'y':0, 'z':0}, 
                                       'h': {'x':0, 'y':1, 'z':0},  
                                       'd': {'x':0, 'y':0, 'z':1}},
                         color:'magenta'});
viewer.zoomTo();
viewer.render();
```

**Comment by dkoes** [comment]
https://3dmol.org/doc/$3Dmol.GLViewer.html#rotate

**Comment by shubihu** [comment]
I have try this. It does Rotate scene, but I don't want to rotate the scene or the aris. Just rotate the box by an axis.

**Comment by dkoes** [comment]
You would need to recreate the box with updated coordinates in that case.

**Comment by dkoes** [comment]
https://en.wikipedia.org/wiki/Rotation_around_a_fixed_axis

**Comment by shubihu** [comment]
Thank you very much! I will try.

**Comment by dkoes** [comment]
If you provide a reproducible test case that illustrates a problem with 3Dmol.js, I will look into it, but debugging your code for you is beyond the scope of this forum.

I will point out that you can simplify your code by using the undocumented math library within 3Dmol.js:
```
vec = new $3Dmol.Vector3(x,y,z)
axis = new $3Dmol.Vector3(0,0,1)
vec.rotateAboutVector(axis,3.1459)
```

**Comment by shubihu** [comment]
Thanks for you advise! I have a another question. How to convert from the coordinates of the box to the size of the box, or from the size of the box to coordinates. As the following example, Convert the size of the first box to coordinates like the second box.
```
var shape = viewer.addShape({color:'red'});
shape.addBox({corner: {x:1,y:2,z:0}, dimensions: {w: 4, h: 2, d: 6}});
shape.addBox({corner: {x:-5,y:-3,z:0},
             dimensions: { w: {x:1,y:1,z:0},
                           h: {x:-1,y:1,z:0},
                           d: {x:0,y:0,z:1} }});
viewer.zoomTo();
viewer.rotate(30);
viewer.render();
```

**Comment by dkoes** [comment]
If you don't provide full vectors for the dimensions, they are assumed to be axis aligned, so  ` {w: 4, h: 2, d: 6}` becomes ` {w: {x:4,y:0,z:0}, h: {x:0,y:2,z:0}, d: {x:0,y:0,z:6}}`

**Comment by shubihu** [comment]
Thanks . I soved my question! Thanks again!!!
```
sizeWx = sizeW * Math.cos((Math.PI * sumY) / 180);         // sumY :  rotate angle Y-axis
sizeWy = sizeW * Math.sin((Math.PI * sumZ) / 180);         // sumZ :  rotate angle Z-axis
sizeWz = -sizeW * Math.sin((Math.PI * sumY) / 180);
```
