### ISSUE TITLE
Ligand Style

### ISSUE THREAD

**Issue by shubihu** [3dmol/3Dmol.js#598]
I added a ligand, but the style is not what I expected！Here is my code.
```
data = 'ligand.pdbqt'
viewer.addModel( data, "pdb" );                       
viewer.setStyle({}, {"stick": { "radius": 0.4 }});
```
**My code result as follow:**
![image](https://user-images.githubusercontent.com/36021958/167057635-5830360e-9b43-4461-bcd5-0cee8d6ba0c1.png)

**Expect:**
![image](https://user-images.githubusercontent.com/36021958/167057718-a3d4f8bb-6261-4151-b44d-d113220f1c84.png)

**Comment by dkoes** [comment]
It is unclear to me how you can see anything considering you are providing a file name as the contents of your pdb file.

**Comment by shubihu** [comment]
Sorry for that. I had figure it out! Now I have a another question. 
When I add a surface, the surface will cover the box(figure2), how can I see complete box when there is a surface like figure1.
figure1
![image](https://user-images.githubusercontent.com/36021958/167242923-ab84d19d-e542-48bc-9d52-8c9e164c5359.png)
figure2
![image](https://user-images.githubusercontent.com/36021958/167242947-cdffb863-ebcf-4597-b34c-aad1a5c4c94f.png)

**Comment by dkoes** [comment]
Yes, we don't support overlapping transparency (unilayer mode only in pymol terms).
