### ISSUE TITLE
Add GLViewer.addLine()

### ISSUE THREAD

**Issue by RacingTadpole** [3dmol/3Dmol.js#61]
I'd like to draw a line between two atoms.  

I'm currently using `viewer.addCylinder`, with a radius of 0.05. 

I'd like to have a command like addLine (perhaps even allowing dotted lines...?).

**Comment by dkoes** [comment]
Done. efe943f

Dashed lines are more problematic. I'd prefer to implement these at the shader level, but that's not going to happen right now.  You could write a little function to make your own dashed line shape (consisting of many disconnected lines - look at the updated testshape.html to see what I mean).

**Comment by RacingTadpole** [comment]
Brilliant, thanks!

**Comment by dkoes** [comment]
Keep this open for dashed lines.

**Comment by helblazer811** [comment]
I believe these are completed so I am closing this issue.
