### ISSUE TITLE
How to host js code locally when using the py3Dmol library in jupyter notebook

### ISSUE THREAD

**Issue by phiweger** [3dmol/3Dmol.js#619]
Thank you for this beautiful library.

How can I host a local copy of the js code, instead of using the default CDN?

`py3Dmol.view()` has a `js` argument that defaults to https://3dmol.org/build/3Dmol.js -- setting it to the path to a local copy of 3Dmol.js did not work.

I suspect that is the preferred method to use the learning server as documented here: https://3dmol.csb.pitt.edu/doc/tutorial-learning_environment.html -- However, I don't know where to specify this in the `py3Dmol` code.

Best and thank you!

**Comment by dkoes** [comment]
It's possible you needed to clear your cache, but if the URL was correct, it would have used it.
