### ISSUE TITLE
Types not automatically found when importing in Typescript

### ISSUE THREAD

**Issue by choephix** [3dmol/3Dmol.js#638]
### Describe the bug

When trying to import "3dmol" in our Typescript project, the typing files that the installed library comes with are not automatically found, and I get this error:

### Screenshots
![image](https://user-images.githubusercontent.com/962412/214294161-c312aa25-58a4-4f92-86d0-24f8d5e21e10.png)

### **Proposed solution**

**Simply adding this line to `package.json` resolves the error.** 

```json
  "types": "build/types/index.d.ts",
```

I have opened a [pull request with this change](https://github.com/3dmol/3Dmol.js/pull/637).

### Environment
```
  System:
    OS: Linux 5.19 Ubuntu 22.10 22.10 (Kinetic Kudu)
    CPU: (4) x64 AMD EPYC 7601 32-Core Processor
    Memory: 3.50 GB / 7.76 GB
    Container: Yes
    Shell: 5.2.2 - /bin/bash
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.12.1/bin/yarn
    npm: 9.3.1 - /workspace/diffusebio/node_modules/.bin/npm
  npmPackages:
    3dmol: ^2.0.0 => 2.0.0     
```

**Comment by dkoes** [comment]
Pull request was merged - can this issue by closed?

**Comment by dkoes** [comment]
Going to assume it can be closed.
