### ISSUE TITLE
[BUG] Isolated salts (e.g., HBr) do not render

### ISSUE THREAD

**Issue by dxdc** [3dmol/3Dmol.js#640]
**Describe the bug**

In the case of an HBr salt, the Br molecule is shown in ball and stick view, but not in the stick view.

**To Reproduce**
Steps to reproduce the behavior. Self-contained code examples are greatly appreciated.

```
Molecule002
  Mrv1903 01162316393D

  6  4  0  0  0  0            999 V2000
    0.4785    0.1547   -0.9430 H   0  0  0  0  0  0  0  0  0  0  0  0
    0.2171   -0.3394    0.0103 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.8330   -0.6810    0.0486 H   0  0  0  0  0  0  0  0  0  0  0  0
    0.5161    0.2460    0.8986 H   0  0  0  0  0  0  0  0  0  0  0  0
    1.2619   -1.9142    0.0667 Cl  0  0  0  0  0  0  0  0  0  0  0  0
   -1.6406    2.5338   -0.0811 Br  0  0  0  0  0  0  0  0  0  0  0  0
  1  2  8  0  0  0  0
  2  5  8  0  0  0  0
  2  4  8  0  0  0  0
  2  3  8  0  0  0  0
M  END
>  <anyBondsFromCoords>
true

$$$$
```

**Expected behavior**
<img width="969" alt="Screen Shot 2023-01-29 at 11 18 07 PM" src="https://user-images.githubusercontent.com/7200365/215393776-84af0025-64ff-4324-aac7-9c4663bf5169.png">

**Screenshots**
Bromine molecule is not shown:

<img width="842" alt="Screen Shot 2023-01-29 at 11 18 52 PM" src="https://user-images.githubusercontent.com/7200365/215393784-77994aa2-4788-4262-90d3-c7fbfb9526c2.png">

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] macOS
 - Browser [e.g. chrome, safari] Chrome

**Comment by dxdc** [comment]
Ball and stick view looks correct.

<img width="416" alt="Screen Shot 2023-01-29 at 11 22 45 PM" src="https://user-images.githubusercontent.com/7200365/215393979-be43831b-a098-4d25-a1f1-aa2cc14e70da.png">

**Comment by dkoes** [comment]
This isn't a bug - sticks visualize bonds, not individual atoms.  If you try the same thing in pymol, for example, you'll get the same vanishing nonbonded atom.

**Comment by dxdc** [comment]
@dkoes thanks for the clarification! I wasn't aware of that. Are there any custom settings that would enable rendering the individual atom in stick view?

**Comment by dkoes** [comment]
Adding an option makes a lot of sense.  I've added a boolean `showNonBonded` to the stick style specification.

**Comment by dxdc** [comment]
Thanks, looks perfect!
