### ISSUE TITLE
Crystal supercell bonds after calling `replicateUnitCell`

### ISSUE THREAD

**Issue by eimrek** [3dmol/3Dmol.js#642]
**Is your feature request related to a problem? Please describe.**

Hi! I'm trying to visualize a crystal supercell with `3dmol` by using `replicateUnitCell`. The problem is that I don't see a way to add bonds between the replicated unit cells.

**Describe the solution you'd like**

Would be nice if I could call `assignBonds` (https://github.com/3dmol/3Dmol.js/blob/master/src/parsers/utils/assignBonds.ts#L6) on a `GLModel` instance. Something like this:

```javascript
import * as $3Dmol from "3dmol";

async function loadStructure() {
    const response = await fetch("./18552.cif", { method: "get" });
    const text = await response.text();
    let config = { backgroundColor: 'mintcream', orthographic: true};
    let viewer = $3Dmol.createViewer( "gldiv", config );
    let m = viewer.addModel(text, "cif");
    viewer.addUnitCell(m);
    viewer.replicateUnitCell(2,2,2,m);
    m.assignBonds(); # <---------------------------------------------- proposed function
    viewer.setStyle({}, {sphere: {scale: 0.3}, stick: {scale: 0.3}});
    viewer.zoomTo();
    viewer.render();
}
```

Currently, I already do something similar, but i needed to implement the `assignBonds` function myself. Would be nice to use already the existing one.

**Comment by dkoes** [comment]
This is easy enough to add. Can you provide an example test file?

**Comment by eimrek** [comment]
Thanks @dkoes. You mean a crystal cif file? Here for example: [58093.zip](https://github.com/3dmol/3Dmol.js/files/10663708/58093.zip)

**Comment by dkoes** [comment]
How's this:
https://3dmol.org/tests/auto/generate_test.cgi?test=testreplicateUnitCellbonds

I've added the assignBonds method to GLModel as well as an additional optional argument to replicateUnitCell to assignBonds.

**Comment by eimrek** [comment]
Perfect! Thanks a lot!
