### ISSUE TITLE
No rendering in jupyter notebook

### ISSUE THREAD

**Issue by phiweger** [3dmol/3Dmol.js#643]
Tryin to run the example code in a new jupyter installation fails:

```
import py3Dmol

view = py3Dmol.view(query='pdb:1ubq')
view.setStyle({'cartoon':{'color':'spectrum'}})
view

# looking into the chrom console log:
Uncaught (in promise) ReferenceError: $3Dmol is not defined
    at <anonymous>:27:1
```

 - MacOS
 - Chrome
 
Thanks for looking into this!

**Comment by dkoes** [comment]
Make sure you are using the latest version (2.0.0.post2). After upgrading, clear all outputs, save, refresh the page, and restart the kernel before testing.

**Comment by edgar0011** [comment]
I would suggest, take care of the import and window global manually, as it worked fine in webpacl/babel environment.

`  import('3dmol/build/3Dmol-nojquery.js').then(($3Dmol) => {
    console.log('$3Dmol')
    console.log($3Dmol)
    window.$3Dmol = $3Dmol
  })`

**Comment by dkoes** [comment]
You should not have to do that if you have the latest version.  If you are running the latest version, I need to understand what the problem is so I can fix it (can't replicate here).

**Comment by phiweger** [comment]
> 

Updating py3Dmol solved the problem, thank you @dkoes for the fast help!
