### ISSUE TITLE
WebGL appears to be disabled.

### ISSUE THREAD

**Issue by QuantitativeVirology** [3dmol/3Dmol.js#644]
We are using 3Dmol viewer to embed/visualize AlphaFold predictions on websites generated from our database of viral proteins on https://www.bosse-lab.org/herpesfolds/.
Since last month, the embedding does not work anymore on Mac/PC/iPhone and the error message "WebGL appears to be disabled." appears.
Thanks for your help!

**Comment by dkoes** [comment]
With 2.0 the ui component was factored out into a separate file that you need to load if you are using the UI. See https://3dmol.org/doc/tutorial-embeddable.html

**Comment by QuantitativeVirology** [comment]
Thanks David!
———————————————————————————————
Prof. Dr. Jens B. Bosse 
Assistant Professor
Hannover Medical School
RESIST group Quantitative Virology
CSSB Center for Structural Systems Biology
c/o DESY, Building 15
Notkestr. 85
22607 Hamburg
Germany

 
RESIST associated group Quantitative Virology
Leibniz Institute of Virology (LIV)
Martinistr. 52
20251 Hamburg
Germany

***@***.***
+49-40-8998-87645

https://www.bosse-lab.org
Twitter: @bosse_lab
