### ISSUE TITLE
Creating a standard orientation using setView() in py3Dmol

### ISSUE THREAD

**Issue by Psirving** [3dmol/3Dmol.js#645]
**Is your feature request related to a problem? Please describe.**

I'm using py3Dmol to render an RNA molecule many times. I would like to create a standard orientation to apply to each instance using viewer.setView(), but viewer.getView(), returns a new view instead of the desired array. My understanding is that this is the intended behavior in py3Dmol in order to avoid 2-way communication.

**Describe the solution you'd like**

Is it possible to set up the viewer to display and update this array based on its own orientation? Then I could just manually type this view array into viewer.setView()

**Comment by dkoes** [comment]
I think you are asking how to figure out an appropriate value to provide setView given that you have positioned the viewer in the desired orientation.  Open up the JavaScript devtools and call getView on your viewer instance.  This will be named something like `viewer_16760482253661613` (some random number).  If you start typing `viewer_`, Chrome should autocomplete for you. E.g.:
```
viewer_16760482253661613.getView()
 [9.462861159062857, 5.483530949445132, -22.1806034525277, -116.3257449396616, 0, 0, 0, 1]
```
You can also just fiddle around with calling rotate/zoom/translate to find a desirable orientation through trial and error.

**Comment by Psirving** [comment]
Thanks! These both work for me.

For context, this is a common task in my work. I've made a python visualization module for RNA experimental data that uses py3Dmol and I'm looking for a way to streamline this process of setting the orientation for myself and other users. I'm also trying to remove as many technical barriers for a non-computational audience as possible. Trial and error might be a good approach. I've also worked out a version of my proposed solution using a clickable callback. I might implement something like this.

```python
import py3Dmol
p = py3Dmol.view(query='mmtf:4tzx')
p.setStyle({'cartoon': {'color': 'spectrum'}})
p.setClickable({}, 'true',
    '''function(atom,viewer,event,container) {
        viewer.addLabel(
            viewer.getView().map(function(each_element){return each_element.toFixed(2)}),
            {
                position: {x:0,y:0,z:0},
                useScreen: true,
                backgroundColor: 'black'
            });
        }''')
p
```

**Comment by dkoes** [comment]
I've implemented `print_to_console_{FUNC}` which will print the result of a viewer command to the javascript console.  For example:
```
v.print_to_console_getView()
```
