### ISSUE TITLE
`assignBonds` basic control over bond cutoffs

### ISSUE THREAD

**Issue by eimrek** [3dmol/3Dmol.js#647]
**Is your feature request related to a problem? Please describe.**
I'm using the `assignBonds` function to determine the bonds of crystals. In many cases, this function, however, creates bonds that I wouldn't want. See for example this cif file

[bao3ti.cif.zip](https://github.com/3dmol/3Dmol.js/files/10735274/bao3ti.cif.zip)

![image](https://user-images.githubusercontent.com/8721264/218814610-d6aa13be-c8c3-4e65-bebc-4ef538c58679.png)

I would want the Ba atom (green) to not be bonded to Ti and O. The distances are

d(Ba-Ti) = 3.48 ang
d(Ba-O) =  2.85 ang

**Describe the solution you'd like**

Would be good to have an optional argument to `assignBonds` to scale the bond cutoff and/or modify the "fudge factor" defined in https://github.com/3dmol/3Dmol.js/blob/master/src/parsers/utils/areConnected.ts.

The scale factor could work similar to

`bonded if r_atom1_atom2  < scale_factor * (r_cov_atom1 + r_cov_atom2 + fudge_factor)`

For my application, I would want to set the `fudge_factor` to 0 and `scale_factor` to something like `0.95`.

**Comment by dkoes** [comment]
We could make the fudge factor user controllable.  Alternatively, I could export the bondTable of covalent bond lengths so you could make per-element modifications.
Ba-Ti: 1.98+1.56 = 3.54 < 3.45 + 0.25
Ba-O: 1.98+0.73 = 2.71 < 2.85 + 0.25  (fudge factor zero isn't enough)

**Comment by eimrek** [comment]
Thanks @dkoes.

Yes, fudge-factor zero isn't enough, but an additional `scale_factor` should fix this. Exposing the whole table is could also be useful, but I think for my application, I would probably keep using the covalent bond radiuses you have defined.

**Comment by dkoes** [comment]
I think the per element modification makes more sense.  Using a globally adjusted scale/fudge factor might not always be able to generate the bonding patterns you want.  I've implemented `setBondLength`, which must be called before parsing molecular data:
https://3dmol.org/tests/auto/generate_test.cgi?test=custombondlengths

**Comment by eimrek** [comment]
yes, this actually works very well for me. Thanks!
