### ISSUE TITLE
[BUG] Apparently valid XYZ file doesn't display anything in 3dMol

### ISSUE THREAD

**Issue by dflock** [3dmol/3Dmol.js#648]
**Describe the bug**
The following apparently valid XYZ file doesn't display anything in 3dMol:

```
4
sto-3g
H      0.000      0.000      1.000
H      0.000      0.000      1.500
H      0.000      0.000     -1.500
H      0.000      0.000     -1.000
```

**To Reproduce**

Go here and upload the file to the embedded viewer: https://3dmol.org/doc/index.html
The viewer loads and parses the file fine, it just doesn't display anything.

**Expected behavior**
When I [go here and upload the file to the embedded JMol viewer](https://chemapps.stolaf.edu/jmol/jsmol/jsmol.htm), I get this:

![image](https://user-images.githubusercontent.com/47756/219101978-999226bb-9ba0-468f-bd5a-70fb2995e67e.png)

I would expect 3DMol to either do that, or throw an error or something, if I doesn't support this molecule.

**Comment by dkoes** [comment]
You have to apply the sphere style to see the atoms.  Bonds are not inferred because the atoms are either too close or to far.  If you change the coordinates like this, you will see bonds:
```
4
sto-3g
H      0.000      0.000      1.000
H      0.000      0.000      1.500
H      0.000      0.000     -1.500
H      0.000      0.000     -1.000
```

**Comment by dflock** [comment]
Sorry, that looks like the same coordinates?

**Comment by dkoes** [comment]
Whoops, copy and pasted the wrong file.  Change 1.5 to 1.9 (or 1.74 if you want to be more chemically accurate).

**Comment by dflock** [comment]
Great, that displays something now!

Is there some way to configure the distance for bond inference?

**Comment by dflock** [comment]
Also, do you have, or are you planning to support, a "ball & stick" style?

**Comment by dkoes** [comment]
Ball and stick is just stick+sphere:
https://3dmol.org/tests/auto/generate_test.cgi?test=testBallAndStick

If you want fine-grained control of where bonds are, use a file format with explicit bonds (e.g. sdf).

**Comment by dflock** [comment]
Perfect - thank you very much for your excellent & extremely speedy help!
