### ISSUE TITLE
[BUG] ReferenceError: ProteinSurface is not defined

### ISSUE THREAD

**Issue by duerrsimon** [3dmol/3Dmol.js#651]
**Describe the bug**
I use 3Dmol.js in a Svelte App. Everything except adding surfaces works. 
If I try to add a surface I get "ReferenceError: ProteinSurface is not defined". 
This might be related to they way how the surfaceworker is set up but I am not 100% sure about the mechanics of this "hack"
https://github.com/3dmol/3Dmol.js/blob/317f8a50af6d789f2ddbc44fd79459d6018fa926/src/SurfaceWorker.js 

**To Reproduce**
https://stackblitz.com/github/duerrsimon/3dmol_svelte_surface/?file=src%2Froutes%2F%2Bpage.svelte

**Expected behavior**
Surface representation added.

**Comment by dkoes** [comment]
I don't know anything about svelte - is this optimizing the code?  Some code minimizers remove the surfaceworker code.  What happens if you import the 3dmol typescript code instead of the built js artifact?
If your build system is optimizing the code, is there a way to turn it off for 3dmol, just to verify that's the problem?

**Comment by dkoes** [comment]
Specifically, `./node_modules/.vite/deps/3dmol_build_3Dmol__js.js` has the `ProteinSurface` class renamed as `ProteinSurface2`.  Hence the `Uncaught ReferenceError: ProteinSurface is not defined` error when trying to add a surface.  Can you figure out where this renaming is happening and why?

**Comment by duerrsimon** [comment]
Good detective work! This issue should not be specific to svelte and seems related to `vite/esbuild`. I found a similar issue (https://github.com/vitejs/vite/issues/7916) but the suggested options in `vite.config.ts` do not seem to work (neither does disabling minification). I assume this is what you mean with code optimization? 

As suggested by the creator of esbuild this renaming of ProteinSurface is happening because esbuild thinks there is a name collision and thats why `ProteinSurface` becomes `ProteinSurface2` https://github.com/evanw/esbuild/issues/1027#issuecomment-803509189

**Comment by dkoes** [comment]
It looks like esbuild has a --keep-names option:
https://github.com/evanw/esbuild/issues/510
although it is not clear it will fix the problem.

**Comment by dkoes** [comment]
I've committed a fix that works around the class renaming:
a1c2932d0ff17da4e921f62fd75a328369f1bc40
It works, but you also have to fix your code to call addSurface correctly. The style and selection order are swapped.  It should be:
`        view.addSurface("MS", { opacity: 0.8 }, { model: 0 });`
(also using string descriptor for surface type to be more readable).

**Comment by dkoes** [comment]
Incidentally, if you want an immediate workaround, you can put
`        mol.setSyncSurface(true);`
before your call to addSurface.  This will render surfaces in the main thread, which will be slightly faster for small surfaces but may cause responsiveness problems for larger.

**Comment by duerrsimon** [comment]
Thanks for the proposed fix! It works for me too ! Closing this now. 
(and sorry for switching the two objects when creating a minimal reproduction of the problem).
