### ISSUE TITLE
Viewer doesn't appear in NextJS project

### ISSUE THREAD

**Issue by elliothershberg** [3dmol/3Dmol.js#652]
**Description**

Hello, thanks for the wonderful tool! I'm looking to add a viewer to a [NextJS](https://nextjs.org/) application. I've successfully loaded the 3Dmol.js scripts, and can see the $3Dmol module loaded in the console of my web page. I've added the example div from the embedding docs, and for some reason, it doesn't display the viewer. I can see the div on the page, I can see that it has the right class, and can see the module, but the viewer can't be seen.

I don't see any errors in my console. Are there any common failure modes that I'm missing to get the viewer to show up? I've added a width and height already.

I've created a[ public repository](https://github.com/elliothershberg/nextjs-3dmol) with a minimal reproducible example of trying to use the viewer in a barebones NextJS app.

As a side note, it seems like there have been a number of issues opened related to React/NextJS. Is there any interest in working to create a React component built on top of this library? It seems like it has the potential to be widely useful. cc @cmdcolin @manzt

<img width="346" alt="image" src="https://user-images.githubusercontent.com/19295181/223881588-2d4321a2-2101-433a-84d6-23843ad6d7a0.png">

<img width="1025" alt="image" src="https://user-images.githubusercontent.com/19295181/223881678-3f8fa831-8b5c-4edf-99ca-74cb9f6ea46d.png">

![image](https://user-images.githubusercontent.com/19295181/223881849-46991a24-c8a6-42ef-89b2-bcc79387a847.png)

**Comment by manzt** [comment]
Could be missing css? Are styles exported separately?

**Comment by manzt** [comment]
hmm noticing the docs don't mention any css so that's probably not it. have you tried to make sure the CDN import works?

**Comment by dkoes** [comment]
Are you dynamically adding the div?  If so, the `$3Dmol.autoload()` function, which processes the divs and instantiates the viewer, won't be run (it is only run when the page is loaded).  You can call it manually.

**Comment by elliothershberg** [comment]
Yeah the div is added dynamically once the script tags have been loaded. I can try running the load process manually.

**Comment by elliothershberg** [comment]
We're in business!

<img width="862" alt="image" src="https://user-images.githubusercontent.com/19295181/223899962-079606cf-2c37-406c-82a4-7f7ecef94fdc.png">

I added the following side effect:

```
useEffect(() => {
    if (viewerLoaded && uiLoaded) {
      // @ts-ignore
      globalThis.$3Dmol.autoload();
    }
  }, [viewerLoaded, uiLoaded]);
```

It waits until the scripts have loaded, and then calls the `autoload` function.

More generally, what is your level of interest for a 3Dmol.js React component? I'd be open to helping out on it. Happy to close this issue and open another for that—or move the conversation out of the issues for this repo.

**Comment by dkoes** [comment]
I don't use React so it is unlikely something I will work on, but I'd happily take pull requests if needed.
