### ISSUE TITLE
About tracking users

### ISSUE THREAD

**Issue by NicolasCARPi** [3dmol/3Dmol.js#664]
Hello,

I see that you disabled tracking in https://github.com/3dmol/3Dmol.js/commit/ab055355fd3191c75f3993d30f66d4dbb35a8433.

Which is a **very good thing** from my point of view :+1: , as it created a big privacy problem, given that you are collecting data of users without their informed consent (in Europe we have the GDPR regulation that is very strict about that sort of things). BTW, you might want to delete this data that you accumulated, just to be on the safe side. I know it could be disabled, but it was opt-out by default (and in my case I needed a complicated workaround to make that option work in my context). I hope it doesn't come back ;)

I believe an alternative approach would be to have a Discussions topic listing users. And users could simply leave a comment "hey we're using it at ...". You would need to activate Discussions in GitHub. It might not be precise, but at least it's something.

Finally, I hope that you're funded, and if needed I would be happy to write a support letter letting the funding bodies know that 3dmol.js is used in [elabftw](https://github.com/elabftw/elabftw/), which is deployed in countless research institutions worldwide.

Best,
~Nico

------

related: #337

**Comment by dkoes** [comment]
The tracking data is deleted. 
A generic letter of support would be appreciated, although I'm not up for a renewal for a couple years.

**Comment by NicolasCARPi** [comment]
Ok great, just let me know when you need it!

Best,
~Nico
