### ISSUE TITLE
Color cartoon by secondary structure

### ISSUE THREAD

**Issue by data2code** [3dmol/3Dmol.js#668]
**Is your feature request related to a problem? Please describe.**
Would like to find a way to color cartoon by secondary structure.
I found somewhere it mentions the following might work:
setStyle({"cartoon": {"sscolors": $3Dmol.ssColors.proteopedia}});
But it does not. I also played with the demo at
https://3dmol.org/viewer.html?pdb=1crn&select=all&style=cartoon
Could not figure out a way to color by ss.

**Describe the solution you'd like**
Could you provide an example or a URL showing how color by ss can be done?
Thanks.

**Comment by dkoes** [comment]
Here is an example:
https://3dmol.org/tests/auto/generate_test.cgi?test=test48

`        m.setStyle({'cartoon':{colorscheme:{prop:'ss',map:$3Dmol.ssColors.Jmol}}});`

**Comment by dkoes** [comment]
We don't have any protopedia colorscheme, but if tell me what it is I can add it.

**Comment by data2code** [comment]
Thank you so much! It works. Don't need to add protopedia, I found it via a Google search, it's probably obsolete or wrong in the first place.
