### ISSUE TITLE
call customized sphere

### ISSUE THREAD

**Issue by Frankie123421** [3dmol/3Dmol.js#673]
Hi, thanks for your great contributions to visualizing 3d molecules. I am new to this framework and have some questions on how to call the customized sphere which I add into an existing viewer. For example,

I create a viewer with 'sdf' format as input, and I want to additionally visualize some special dummy "atoms" which only have coordinates but do not have conventional atom types. I use 'addSphere' here.
```
viewer = py3Dmol.view()
viewer.addModel(xyz, 'sdf')
viewer.setStyle({'stick': {'radius': 0.15}, 'sphere': {'scale': 0.3}})
viewer.addSphere({'center': {'x':0.34, 'y':2.45, 'z':1.11}, 'radius': 0.6, 'color':'yellow', 'opacity':0.5})
viewer.setBackgroundColor('white')
viewer.zoomTo()
```
I wonder how to label or tag the sphere so I can call it when using the setHoverable function as the following given example. Specifically, I would like when my mouse pointer moves on the hovered dummy sphere, it shows its positions and its label information "dummy" (just like a special atom type)
```
v = py3Dmol.view(query="pdb:1ubq",style={'cartoon':{},'stick':{}})
v.setHoverable({},True,'''function(atom,viewer,event,container) {
                   if(!atom.label) {
                    atom.label = viewer.addLabel(atom.resn+":"+atom.atom+' ('+atom.x+','+atom.y+','+atom.z+')',{position: atom, backgroundColor: 'mintcream', fontColor:'black'});
                   }}''',
               '''function(atom,viewer) { 
                   if(atom.label) {
                    viewer.removeLabel(atom.label);
                    delete atom.label;
                   }
                }''')
```

**Comment by dkoes** [comment]
You can set click and hover handlers as part of the shape style, as in this example:
https://3dmol.org/tests/auto/generate_test.cgi?test=test13

**Comment by Frankie123421** [comment]
Thanks for your quick reply. I read the js code, but how can I transform it into py version?
```
xyzview.addSphere({'center':{'x':0,'y':0,'z':0},'radius':0.6,'color':'red','hoverable':True,'clickable':True, 'callback':'''function(){ this.color.setHex(0x00FFFF00);xyzview.render();}''',
                                  'hover_callback': '''function(){ xyzview.render();}''',
                                  'unhover_callback': '''function(){ this.color.setHex(0xFF0000);xyzview.render();}'''
                                 })
```
It seems that I should replace 'this' with the callable object about sphere?
