### ISSUE TITLE
Color by model‘s residue for multiple models

### ISSUE THREAD

**Issue by jiaweiguan** [3dmol/3Dmol.js#696]
Problems during use

**Description**
I want to load multiple PDBs, and then assign different colors to the amino acids in each PDB. But the output result is blank. I suspect there may be a problem with the method of specifying the nth protein, but I don't know how to modify it.

**Relevant Context**
code：
```
import py3Dmol
view = py3Dmol.view(width=400, height=300)

molecules = []
for i in range(25):
    with open(f"./traj/25_0/{i}.pdb", 'r+') as ifile:
        molecules.append(Molecule(ifile))
        
models = ""
for idx, mol in enumerate(molecules):
    models += f"MODEL {idx}\n"
    models += str(mol)
    models += "ENDMDL\n"
view.addModelsAsFrames(models, index=True)

# views = []
for n in range(25):
    for _, at in enumerate(molecules[n]):
        default = {"cartoon": {'color': 'black'}}
        view.setStyle({'model': n, 'resi': at['resid']}, at.get("coloraf", default))

view.zoomTo()
view.animate({'loop': "forward", 'reps': 25, 'interval': 1000})
view.show()
```

**Comment by dkoes** [comment]
You have added models as frames, so there is only one model. Trying to style anything other than model 0 will be an error.  Currently, unique styles for individual frames of the same model isn't supported.

What does `at.get("coloraf", default)` return? Are you sure it is a valid StyleSpec object?

**Comment by jiaweiguan** [comment]
> You have added models as frames, so there is only one model. Trying to style anything other than model 0 will be an error. Currently, unique styles for individual frames of the same model isn't supported.
> 
> What does `at.get("coloraf", default)` return? Are you sure it is a valid StyleSpec object?

at.get("coloraf", default)：at is ditc, coloraf is key.

  def coloraf(self, bfactor):
      if bfactor >= 90:
          return {"cartoon": {'color': "blue"}}
      elif bfactor < 90 and bfactor >= 80:
          return {"cartoon": {'color': "cyan"}}
      elif bfactor < 80 and bfactor >= 70:
          return {"cartoon": {'color': "green"}}
      elif bfactor < 70 and bfactor >= 50:
          return {"cartoon": {'color': "yellow"}}
      elif bfactor < 50:
          return {"cartoon": {'color': "orange"}}

**Comment by jiaweiguan** [comment]
`import py3Dmol
import numpy as np

view = py3Dmol.view(width=400, height=300)

molecules = []
for i in range(25):
    with open(f"./traj/25_0/denoised_{i}.pdb") as ifile:
        molecules.append(Molecule(ifile))

mols = []
for n, mol in enumerate(molecules):
    view.addModel(str(mol))

# views = []
for k in range(25):
    for _, at in enumerate(molecules[k]):
        default = {"cartoon": {'color': 'black'}}
        view.setStyle({'model':k, 'resi': at['resid']}, at.get("coloraf", default))

view.zoomTo()
view.animate({'loop': 'forward', 'reps': 1, 'step': 100})
view.show()
`

**Comment by dkoes** [comment]
How important is it to have discrete colors instead of apply a gradient color scheme using the b factor property?
https://3dmol.org/tests/auto/generate_test.cgi?test=Gradient_ts_CustomLinear

**Comment by jiaweiguan** [comment]
I replaced B-factor with plddt from af2

> How important is it to have discrete colors instead of apply a gradient color scheme using the b factor property? https://3dmol.org/tests/auto/generate_test.cgi?test=Gradient_ts_CustomLinear

I replaced B-factor with plddt from af2. Animating Multiple Proteins

**Comment by dkoes** [comment]
That really didn't answer the question.  Is it important to you that you have this small collection of discrete colors, or is a gradient, as shown in the linked example (which is also displaying plddt in a b factor) sufficient for your purposes?  If so, just use the code from the example, it should work across frames.

**Comment by jiaweiguan** [comment]
In fact, I want to create an animation process for denoising and restoring proteins, with each amino acid position having a confidence level. If all PDBs are loaded in frames, they can form animations, but the color of each frame does not change. If loaded according to multiple models, it is static graphs, and all models are together.

**Comment by dkoes** [comment]
Okay, but you still aren't answering the question.  Do you really need discrete jumps in colors, or is a gradient okay?  Actually, it doesn't really matter - you can implement discrete color mapping using the a CustomLinear gradient (https://3dmol.org/doc/CustomLinear.html) with (many) repeated color points.

**Comment by jiaweiguan** [comment]
Okay. I understand this method. What I want to solve is not the coloring problem. In fact, what I want to solve is to turn multiple different colored PDBs into animations.

**Comment by dkoes** [comment]
Yes, and if you apply a gradient colorscheme to model with multiple frames, each frame should be appropriately colored.

**Comment by jiaweiguan** [comment]
Yes, but how to create an animation?

**Comment by dkoes** [comment]
If they are loaded as frames, call animate like you do at the beginning of this issue. Frames cannot have unique styles, but by applying a gradient they all have the same style which happens to result in different colors on different frames.

**Comment by jiaweiguan** [comment]
How to save a gif format？

**Comment by dkoes** [comment]
You can't, only png is supported. https://3dmol.org/doc/GLViewer.html#apngURI
