### ISSUE TITLE
[BUG] Dev dependency `clean-jsdoc-them` wrongly marked as dependency

### ISSUE THREAD

**Issue by NicolasCARPi** [3dmol/3Dmol.js#724]
Hello :wave: 

**Describe the bug**

When updating 3Dmol.js from 2.0.3 to 2.0.5 I saw this warning:

![2023-10-01-212708_733x48_scrot](https://github.com/3dmol/3Dmol.js/assets/3043706/b108494b-dddc-4368-9626-57c23db45fec)

and wondered why 3dmol.js would need jsdoc. It seems this commit: https://github.com/3dmol/3Dmol.js/commit/df952ebed432aafe3840a111399f34a4ae5ec9f0 by @adithyaakrishna introduced the theme as a dependency instead of a **dev** dependency, with its friend `jsdoc` which is adequately listed in devDependencies.

As you know, this is a major issue for downstream projects depending on the 3dmol.js package, which then inherit a bunch of dependencies for the wrong reasons (17 new npm packages in my case).

Of course, when I say *major* issue, I mean it's a blocker for us but there are worse things in life, and this is definitely not a "drop everything and fix it" situation, but surely something that needs to be patched.

**To Reproduce**
Upgrade 3dmol.js to its latest version.

**Expected behavior**
All dev dependencies are declared as such.

**Screenshots**
![2023-10-01-214015_722x134_scrot](https://github.com/3dmol/3Dmol.js/assets/3043706/114bcc3b-9bcf-4735-93cf-ade01303f5ea)

**Additional context**
October's debut,
Paris basks in fiery heat,
Sunday's warmth, a treat.

![mochi-peach](https://github.com/3dmol/3Dmol.js/assets/3043706/8da8ea46-3727-457c-b1bd-228d1e65a0ac)

**Comment by adithyaakrishna** [comment]
@NicolasCARPi Will send a fix for it, thanks for pointing it out :)

**Comment by adithyaakrishna** [comment]
Ooos! I missed, I guess @dkoes already sent one 😅
