### ISSUE TITLE
[BUG] Colorfunc is documented on colorscheme but taken on style

### ISSUE THREAD

**Issue by Luthaf** [3dmol/3Dmol.js#726]
**Describe the bug**

The documentation of [`ColorSchemeSpec`](https://3dmol.csb.pitt.edu/doc/global.html#ColorschemeSpec) mention `colorfunc` as a possible field, but the code seems to look for `colorfunc` on the `style` (not `style.colorspec`!):

https://github.com/3dmol/3Dmol.js/blob/79ccc580ab90fe9012e1c1cbc78229753314d102/src/utilities.ts#L599-L602

**Expected behavior**

Documentation and code should agree!

I can send a PR modifying either the documentation (adding `colorfunc` to all the `***StyleSpec`), or modifying the code above, as you prefer.

cc @MaximeScope

**Comment by dkoes** [comment]
Thanks for pointing this out.  I've moved the documentation to the right spot.
