### ISSUE TITLE
set bonds to have identical radii regardless of bond order

### ISSUE THREAD

**Issue by dxdc** [3dmol/3Dmol.js#732]
At least in the `stick` drawing style, a double-bond is approximately half the radius of a single bond. This allows the overall "bond" to occupy roughly the same overall cylindrical dimensions.

However, for my use case, I'm trying to set all bond radii to be identical.

The code below is actually working (to some degree), however, it also sets neighboring bonds to have much larger radii. For example, consider the neighboring single C-C or C-H bonds being thicker.

Is there a better way of doing this?

### Standard styling:
<img width="588" alt="image" src="https://github.com/3dmol/3Dmol.js/assets/7200365/268c92ff-348c-465a-87f2-02378bff9be7">

### After applying below JS (closer, but scales all bonds):
<img width="590" alt="image" src="https://github.com/3dmol/3Dmol.js/assets/7200365/cbcc3653-3819-4071-b86f-f497054760a7">

#### Select and alter styles:

```js
const hasDoubleBond = (atom) => atom.bondOrder.some((order) => order === 2);
let atoms = viewer.selectedAtoms({ predicate: hasDoubleBond });

// Create a set to store processed bonds
let processedBonds = new Set();

// Loop through atoms to set styles for double bonds
atoms.forEach((atom) => {
	atom.bonds.forEach((bondedAtom, idx) => {
		// Skip if not a double bond
		const bondOrder = atom.bondOrder[idx];
		if (bondOrder !== 2) return;

		// Skip if already processed
		const bondId = [atom.index, bondedAtom].sort().join('-');
		if (processedBonds.has(bondId)) return;

		// Mark as processed
		processedBonds.add(bondId);

		// Apply style
		viewer.addStyle({ serial: [atom.index, bondedAtom] }, { stick: { radius: 0.2 } });
	});
});
```

**Comment by dkoes** [comment]
The scaling factor for double/triple bonds was a fixed number, but I've made it configurable with doubleBondScaling and tripleBondScaling style options:
https://3dmol.org/doc/StickStyleSpec.html#doubleBondScaling

https://3dmol.org/tests/auto/generate_test.cgi?test=bondscaling

**Comment by dkoes** [comment]
Done! Version 2.0.6.
