### ISSUE TITLE
Export visualisation to PyMol/Chimera session, PDB, CIF format

### ISSUE THREAD

**Issue by JavierSanchez-Utges** [3dmol/3Dmol.js#733]
I was wondering if it is possible to export the visualisation on the viewer to a file compatible with PyMol/Chimera. Or simply save save the structure visualised to a PDB/CIF format.

I have seen the methods exportJSON and exportVRML, but I am not sure how these could be used to visualise the structure by other software.

Many thanks.

**Comment by dkoes** [comment]
We generally stay away from analysis/cheminformatics (which file conversion would include), but `exportJSON` is ChemDoodle JSON format which you can convert with openbabel:
```
obabel -xc1 -icdjson ex.json -Oex.sdf
```

**Comment by JavierSanchez-Utges** [comment]
OK. That makes sense. Thanks, I will try that Openbabel command!
