### ISSUE TITLE
addResLabels with custom text/remove labels from atom selection

### ISSUE THREAD

**Issue by JavierSanchez-Utges** [3dmol/3Dmol.js#734]
I have been playing with residue labels and using the `GLViewer.addResLabels()` method, which is great. However, I would like to show a different residue number, i.e., UniProt ResNum, instead of PDB ResNum. Is there a way to edit the `GLViewer.addResLabels()` method to incorporate this, if I had a dictionary {PDBResNum: UniProtResNum}? If this is not possible, I guess I would have to use the `GLViewer.addLabel()` and call it once for each residue in my selection?

Is there a way to remove the labels of a selection of residues in one command? I am currently using `GLViewer.removeAllLabels()`. It would be something like `GLViewer.removeLabels(sel)`. Otherwise, I was thinking of looping through residues in `sel` and using the `GLViewer.removeLabel()`.

Thanks!

**Comment by dkoes** [comment]
addResLabels is just a convenience function - if you want custom labels you'll need to use the regular addLabel.  removeLabel takes a label object, not a selection.  You'll need to manually manage   your labels.

**Comment by JavierSanchez-Utges** [comment]
I thought so. Many thanks!
