### ISSUE TITLE
[Question] how to use the clickable interaction

### ISSUE THREAD

**Issue by Kvieta1990** [3dmol/3Dmol.js#737]
I am trying to learn how to enable the clickable interactivity to get the molecular information. For example, if I click on an atom, I want to show the label. Also, if I click on a bond, I want to show the bond length. I suppose we do have such capabilities but it seems that I could not find a good starting point to learn how-to. Could you please help provide a minimal example about this? Thank you!

BTW, I was using Python flask together with the 3Dmol.js for the implementation, i.e., I pass the pdb information from Python flask to 3dmol for visualization.

**Comment by dkoes** [comment]
There is an example of drawing a label in the documentation for setClickable:
https://3dmol.org/doc/GLViewer.html#setClickable
Bonds aren't click targets, just atoms, but example code for measuring and displaying distances can be found here:
https://github.com/3dmol/3Dmol.js/issues/707

**Comment by Kvieta1990** [comment]
that is really helpful! thank you!
