### ISSUE TITLE
Link to API documentation for $3Dmol.GLViewer is broken

### ISSUE THREAD

**Issue by sdr0598** [3dmol/3Dmol.js#742]
The links to the API docs for $3Dmol.GLViewer are broken in the 'Using 3Dmol within your code' tutorial.
<img width="389" alt="image" src="https://github.com/3dmol/3Dmol.js/assets/132721649/e2e3e3f3-a5bb-4d78-a348-d622b4e00f83">

**Comment by dkoes** [comment]
Thanks! Fixed.
