### ISSUE TITLE
3Dmol.js Error: 'Cannot read properties of undefined (reading 'atom')'

### ISSUE THREAD

**Issue by zongyangdu** [3dmol/3Dmol.js#743]
I encountered an error while trying to render a molecule using 3Dmol.js. The console reports the following error:

Uncaught TypeError: Cannot read properties of undefined (reading 'atom')
    at drawCartoon (3Dmol.js:28726:50)
    at Object.defaultDrawCartoon [as drawCartoon] (3Dmol.js:28916:9)
    at createMolObj (3Dmol.js:31086:24)
    at GLModel.globj (3Dmol.js:32219:26)
    at GLViewer.render (3Dmol.js:34892:31)
    at Object.success (RTH000035/:182:18)
    at fire (3Dmol.js:3317:31)
    at Object.fireWith [as resolveWith] (3Dmol.js:3447:7)
    at done (3Dmol.js:9272:14)
    at XMLHttpRequest.<anonymous> (3Dmol.js:9514:9)

And the pdb file is as follows:
[model5.txt](https://github.com/3dmol/3Dmol.js/files/13825182/model5.txt)

**Comment by zongyangdu** [comment]
Here is my code:

  <script src="/style/jquery-3.2.1.js"></script>
  <script type="text/javascript" src="/style/3Dmol.js"></script>
    <div style="position:relative;left:30px;">
	<table>

	<tr><td align="middle">  
<div id ="pdb_div" style="float: left; height:300px; width: 500px; position: relative;">   
          <script>
		  
	  glviewer = $3Dmol.createViewer("pdb_div", {});
          $(document).ready(function(){
             $(function(){
                $.ajax(
		{
		  url: "model.pdb",
		  dataType: "text",
		  success: function(data)
		  {
		      glviewer.setBackgroundColor(0xf8f8f8);
		      glviewer.addModel(data, "pdb");
		      glviewer.setStyle({cartoon:{color:"spectrum"}})
		       glviewer.zoomTo();
		      glviewer.render();
		  }
		});
          });
       });
     </script><br>
	 </div>
	
	 </td>

**Comment by dkoes** [comment]
Thank you for the bug report.  The above commit fixes the issue.  The code was making assumptions about atom ordering. A regression test has been added:
https://3dmol.org/tests/auto/generate_test.cgi?test=testdnacartoon
