### ISSUE TITLE
Export the 3D model in the view as an .STL or .OBJ file

### ISSUE THREAD

**Issue by sinemete** [3dmol/3Dmol.js#746]
Hello,

Is it possible to export the 3D model in the view as an .STL or .OBJ file?

Best,

**Comment by dkoes** [comment]
No, but [`exportVRML`](https://3dmol.org/doc/GLViewer.html#exportVRML) will produce a vrml file that can be converted to those formats.

**Comment by sinemete** [comment]
Thank you.
