### ISSUE TITLE
Atom's coordinate movement

### ISSUE THREAD

**Issue by heoSuKyeong** [3dmol/3Dmol.js#747]
I want to select an atom and rotate it.
Is there a function that can move the atom's coordinates?

**Comment by dkoes** [comment]
You can multiply the coordinates by a rotation matrix.  The math module isn't really documented, but there is a `setRotationFromEuler` function if you need assistance creating a rotation matrix.

**Comment by heoSuKyeong** [comment]
The rotation matrix was obtained through another method.
But I'm not sure how to move the coordinates using that value.
atom.x = 10
atom.y = 20
atom.z = 30
Even if I enter arbitrary values, the atom does not move. Isn't this the way to approach it?

**Comment by dkoes** [comment]
Did you render the scene after changing the coordinates?

**Comment by heoSuKyeong** [comment]
I definitely did.
I checked the coordinates before and after moving to the console.
But it didn't move.

![image](https://github.com/3dmol/3Dmol.js/assets/103197446/f91fb0c9-57a0-4d2e-bc78-1478c9e94be8)

**Comment by dkoes** [comment]
When calling render call it with the regen option set to true to force a rebuild of the geometry (the first argument is a callback function):
`viewer.render(null, {regen: true});`

**Comment by dkoes** [comment]
Alternatively, if you have multiple models and only want to force a rebuilt on the model you are change, you can call `removegl` on only that model.

**Comment by heoSuKyeong** [comment]
Wow, it was solved in the same way as above.
Thank you so much.
