### ISSUE TITLE
Remove redundant argument from package.json scripts

### ISSUE THREAD

**Issue by prajwalkulkarni** [3dmol/3Dmol.js#748]
**Description**
Currently, there are different webpack config files for different modes (dev/prod) with the base config file being `webpack.common.js`. The modes are mentioned in the corresponding config files (`development`/`production`). However, the modes are again explicitly passed when running scripts like `build:dev`,`build:prod`. I think this is not necessary and adds to redundancy. We can simply remove the `--mode` argument from `build:dev` and `build:prod` command.
Reference: [Webpack mode](https://webpack.js.org/configuration/mode/)

**Comment by dkoes** [comment]
Please provide a pull request with your suggested changes.

**Comment by prajwalkulkarni** [comment]
@dkoes PR #749 addresses this issue. Kindly check.
