### ISSUE TITLE
Visualizing multiple protein structures in the same viewer

### ISSUE THREAD

**Issue by OreFoX18** [3dmol/3Dmol.js#755]
Hello everyone!

I've been working on a project where it would be very cool to have more protein structures rendered in the same viewer simultaneously but as individual objects. I would also like to be able to set up coordinates of those structures to be able to position them in the viewer. I was trying to find solution and a way to do it in this library but so far came short handed. I'm wondering if that is possible and how?

Kind regards,
Haris

**Comment by dkoes** [comment]
Can you elaborate on what you mean by “individual objects”? You can add each structure to a different model object. Are you asking for the ability to have mouse controls only effect a subset of models?

**Comment by OreFoX18** [comment]
Thank you, dkoes, for your prompt response.

I'm exploring the possibility of loading multiple protein structures into the viewer simultaneously while having individual control over their positioning, translation, rotation, and zooming. The goal is to display several structures side by side in the viewer, and I attempted to add more protein models to the same viewer object. However, they seem to overlap.

Any insights or suggestions on how to achieve separate control for each structure within the same viewer would be greatly appreciated. Thank you!

**Comment by dkoes** [comment]
Based on your comment about wanting to avoid overlap, I think what you want is a viewer grid:
https://3dmol.org/doc/global.html#createViewerGrid
https://3dmol.org/tests/auto/generate_test.cgi?test=testAllenes

If you actually want a single viewer where you can manipulate the position of models within it, that is something you would have implement yourself by manipulating the model's rotation matrices (which isn't something that is cleanly exposed in the API).

**Comment by dionjwa** [comment]
I would love the ability to rotate the molecule myself (programatically) and to get the rotation matrices out also. Is there a way to do this, even if it isn't clean?

**Comment by dkoes** [comment]
Yes, `getView` and `setView` let you adjust the view at a low level.  `rotate`, `translate` and `zoom` at a higher level.

https://3dmol.org/doc/GLViewer.html#getView
https://3dmol.org/doc/GLViewer.html#setView
https://3dmol.org/doc/GLViewer.html#rotate
https://3dmol.org/doc/GLViewer.html#translate
https://3dmol.org/doc/GLViewer.html#zoom

**Comment by dionjwa** [comment]
Thank you @dkoes ! Are there event hooks or listeners where I could listen to these changes?

**Comment by dkoes** [comment]
`setStateChangeCallback` let's you register a callback for whenever there is a change to the scene, however it is up to you to determine what the change was.
https://3dmol.org/doc/GLViewer.html#setStateChangeCallback

**Comment by dionjwa** [comment]
Awesome. Appreciate your help.
