### ISSUE TITLE
Is it possible to have post-translational modifications (PTMs) features in 3Dmol?

### ISSUE THREAD

**Issue by huajianmao** [3dmol/3Dmol.js#758]
3Dmol is awesome for visualizing protein.

Is it possible to have post-translational modifications (PTMs) features in 3Dmol?
Just like the [PyTMs](https://pymolwiki.org/index.php/Pytms) for PyMOL.

**Comment by dkoes** [comment]
If you are asking for the ability to edit/mutate structures, I prefer to keep the focus on visualization (but am very willing to accept pull requests from contributors - this is just a line I draw on how I will spend my very limited development time).  If there is a specific way you want to visualize these modified residues, that is something I could look into.
