### ISSUE TITLE
Discrepancy in Atom Rendering Between 3Dmol.js and VESTA for Al1Cd2_H.cif File

### ISSUE THREAD

**Issue by yliu7949** [3dmol/3Dmol.js#759]
[Question]

Hello, I am currently working with the [Al1Cd2_H.cif file](https://github.com/3dmol/3Dmol.js/files/14046105/Al1Cd2_H.cif.txt), which contains 6 atoms, and I've encountered an issue regarding the rendering of atoms using 3Dmol.js compared to the [VESTA software](https://jp-minerals.org/vesta/en/).

**Description**
When rendering the Al1Cd2_H.cif file, I observed that VESTA and 3Dmol.js produce different results. In VESTA, the software automatically replicates aluminum atoms that are located at x coordinates of 0 and 1 (and similarly for all atoms exactly positioned on the faces of the lattice) to the corresponding opposite face. This process results in VESTA rendering a total of 8 atoms.

![VESTA](https://github.com/3dmol/3Dmol.js/assets/54410385/f8a1f6b6-73d0-41f6-aa49-5c769fae2995)

However, when using 3Dmol.js with the following code snippet, the rendered output includes only the original 6 atoms, without the periodic replication observed in VESTA.

```javascript
let element = document.querySelector('#container-01');
let config = { backgroundColor: 'white' };
let viewer = $3Dmol.createViewer(element, config);
let m = viewer.addModel(text, "cif", {'doAssembly': true, 'duplicateAssemblyAtoms': true, 'normalizeAssembly': true});
viewer.addUnitCell(m);
viewer.setStyle({'sphere':{'colorscheme':'Jmol','scale':.3},'stick':{'colorscheme':'Jmol', 'radius': 0.2}})
viewer.zoomTo();
viewer.render();
viewer.zoom(1.5, 1500);
```

<img width="872" alt="3Dmol.js" src="https://github.com/3dmol/3Dmol.js/assets/54410385/8c0ff1ba-cc2e-4fd9-84f5-c7d5300bec3b">

Is there a way to achieve the same periodic replication effect in 3Dmol.js as observed in VESTA? Any guidance on how to modify the code or use specific functions in 3Dmol.js to replicate this behavior would be greatly appreciated.

**Comment by dkoes** [comment]
You can replicate the unit cell:
http://localhost/3Dmol/tests/auto/generate_test.cgi?test=testreplicateUnitCell

but this seems to be a selective replication that only happens when atoms are on a boundary.

**Comment by yliu7949** [comment]
Thank you for your reply. 
Similar rendering outcomes, displaying eight atoms, are observed in other lattice visualization software like 3DStructGen and Materials Studio. This approach appears to be a standard in the field of computational chemistry. Considering this, would it be feasible to consider the possibility of adding a feature in 3Dmol.js to enable a similar rendering method?

**Comment by dkoes** [comment]
I am philosophically opposed to showing 8 atoms by default when the file only has 6 atoms in it, but I have added a feature in the above commit where you can call `replicateUnitCell(1)` and it will replicate the unit cell keeping only those atoms that remain within it (e.g., are on the boundary):
https://3dmol.org/tests/auto/generate_test.cgi?test=replicateprune

**Comment by yliu7949** [comment]
Thank you very much for your solution, I will try the new `replicateUnitCell(1)` feature.
