### ISSUE TITLE
.render() is not showing updated representation of models

### ISSUE THREAD

**Issue by sdr0598** [3dmol/3Dmol.js#763]
Hi all,
I am trying to show & hide stick representation of a model currently in cartoon representation.
The problem is that when I hide the stick representation, the .render() method is not updating the visualizer to show the model only in cartoon representation (both stick and cartoon representations are still shown.)
Here is my code for turning on the stick representation:
```
var viewer = $3Dmol.viewers["viewer"];
$3Dmol.download("pdb:5wty", viewer, {}, function () {
    viewer.setStyle({}, { cartoon: {} });
    viewer.render();
});
viewer.addStyle({}, { stick: {} });
viewer.render(); 
```

Next, here is my code for turning off the stick representation:
```
function remove_atom_style(atom_arr, style) {
  atom_arr.forEach(function (element) {
      if (element.style.hasOwnProperty(style)) {
        delete element.style[style];
      }
   });
}
viewer.models.forEach(function (model) {
   remove_atom_style(model.atoms, "stick");
})
viewer.render()
```
When I do console.log(viewer.models), I can see that 'stick' got removed from the style dictionary for the atoms but that representation is still being shown in the visualizer. I do not want to use .setStyle() method to remove the 'stick' representation because I want to return to the original representation prior to adding the stick representation [unless there is a workaround I am unaware of].

**Comment by dkoes** [comment]
For the first case you are adding nothing and so nothing changes.  In the second you are modifying the style outside of the standard routines so render doesn't know the scene has changed.

What you want to do is `viewer.addStyle({stick:{hidden:true}});`

**Comment by sdr0598** [comment]
Thank you for the input. This fixed my issue.
