### ISSUE TITLE
[BUG] defaultcolors not applied when using addModelsAsFrames

### ISSUE THREAD

**Issue by dsvatunek** [3dmol/3Dmol.js#764]
**Describe the bug**

When using

`viewer = $3Dmol.createViewer("Model", {defaultcolors: $3Dmol.elementColors.Jmol});`

the color scheme gets applied to models added using 

`viewer.addModel(xyz_data, "xyz");`

but not when using 

`viewer.addModelsAsFrames(xyz_data, "xyz");`

**To Reproduce**

This code gives the default color for the nitrogen atom 
<img width="59" alt="default" src="https://github.com/3dmol/3Dmol.js/assets/39262379/873e59a8-4aca-4735-95d4-89800873610e">

```<script src="https://3Dmol.org/build/3Dmol-min.js"></script>

<div style="text-align: center;">
        <div id="Model" style="width: 500px; height: 500px;"></div>
</div>

<script>
  $(document).ready(function() {
    var viewer = $3Dmol.createViewer("Model", {defaultcolors: $3Dmol.elementColors.Jmol});
    var xyz_data = `1
test
N 0.0 0.0 0.0
1
test
N 0.0 0.0 0.0`;
    viewer.addModelsAsFrames(xyz_data, "xyz");
    viewer.setStyle({}, {stick: {radius: 0.15},sphere: {scale: 0.25}});
    viewer.zoomTo();
    viewer.setViewStyle({style: 'outline', color: 'black', width: 0.02});
    viewer.render();
});	
</script>
```

While using `addModel` gives the correct jmol color: 
<img width="54" alt="jmol" src="https://github.com/3dmol/3Dmol.js/assets/39262379/b09a1150-52e7-4c3a-a768-90fbb060e400">

```<script src="https://3Dmol.org/build/3Dmol-min.js"></script>

<div style="text-align: center;">
        <div id="Model" style="width: 500px; height: 500px;"></div>
</div>

<script>
  $(document).ready(function() {
    var viewer = $3Dmol.createViewer("Model", {defaultcolors: $3Dmol.elementColors.Jmol});
    var xyz_data = `1
test
N 0.0 0.0 0.0`;
    viewer.addModel(xyz_data, "xyz");
    viewer.setStyle({}, {stick: {radius: 0.15},sphere: {scale: 0.25}});
    viewer.zoomTo();
    viewer.setViewStyle({style: 'outline', color: 'black', width: 0.02});
    viewer.render();
});	
</script>
```

**Expected behavior**

defaultcolors should be applied to models added using `addModelsAsFrames`

**Comment by dkoes** [comment]
Thanks for the complete bug report!  Fixed in the above commit:
https://3dmol.org/tests/auto/generate_test.cgi?test=defaultcolors
