### ISSUE TITLE
[BUG] Double bonds rendered out of plane (CID: 243, 2244)

### ISSUE THREAD

**Issue by dxdc** [3dmol/3Dmol.js#767]
**Describe the bug**
In some cases, the double bond for a carbonyl is being drawn out of plane. I'm wondering if -- inadvertently -- this is related to the `getGoodCross` function we've been discussing in #455.

**To Reproduce**
View the carbonyl rendered with the CID examples below (243, 2244). In the case of 2244, one of the carbonyls is correct and the other is not. I'm not sure if there are other examples, but these are at least two.

**Screenshots**

#### CID: 243 (Benzoic Acid)

<img width="617" alt="image" src="https://github.com/3dmol/3Dmol.js/assets/7200365/d849d76d-9d0e-4e3e-9400-73ca06427357">

#### CID: 2244 (Aspirin)

<img width="556" alt="image" src="https://github.com/3dmol/3Dmol.js/assets/7200365/bc74b19c-142a-41f7-a1ed-2a5a9ba0412b">

**Comment by dkoes** [comment]
Yup, an updated getGoodCross would change this behavior.

**Comment by dkoes** [comment]
Sorry for the radio silence - been swamped.  The above push should standardize these bonds (was actually unrelated to getGoodCross).
https://3dmol.org/tests/auto/generate_test.cgi?test=testdoubles
