### ISSUE TITLE
Support wireframe and opacity for addIsoSurface in VRML Export

### ISSUE THREAD

**Issue by dxdc** [3dmol/3Dmol.js#768]
**Is your feature request related to a problem? Please describe.**

When exporting molecular visualizations to VRML format using `viewer.exportVRML()` involving `addIsoSurface`, it has been observed that specific properties, namely wireframe and opacity, do not render in the exported result. This limitation restricts the ability to create more visually detailed and nuanced representations of isosurfaces in VRML format, particularly for purposes where transparency and wireframe visuals provide critical information.

```js
    var voldata = new $3Dmol.VolumeData(data, "cube");
    viewer.addIsosurface(voldata, {isoval: 0.01, color: "blue", alpha: 0.95, smoothness: 10});
    viewer.addIsosurface(voldata, {isoval: -0.01, color: "red", alpha: 0.95, smoothness: 10});
```

**Describe the solution you'd like**

The wireframe property should enable the visualization of the isosurface in a wireframe mode when exported to VRML, allowing for a skeletal representation of molecular surfaces. The alpha property should control the transparency of the isosurface in the exported VRML file, allowing for the creation of semi-transparent surfaces that can visually indicate density, concentration, or overlap with other molecular structures.

**Describe alternatives you've considered(Optional)**

- The alpha transparency for VRML is defined here, but it does not appear to render properly? I also found out I needed to use `opacity` instead of `alpha` (deprecated) to get the transparency line to show up in VRML. That being said, there is no change once it's exported, so maybe there is something more nuanced.

https://github.com/3dmol/3Dmol.js/blob/dec52bcb76eaf3e084230c9cb9f1af15d14903d0/src/WebGL/core/Geometry.ts#L181-L183

- The material does seem to have the `wireframe` property, but there is no change when exporting to VRML whether or not wireframe is used.

### in webGL

<img width="351" alt="image" src="https://github.com/3dmol/3Dmol.js/assets/7200365/7bb92057-136c-42d8-9eb1-4f4c1b0f0f49">

### after VRML export

(I can obviously turn on wireframe mode, but that makes the atoms wireframes also)

<img width="351" alt="image" src="https://github.com/3dmol/3Dmol.js/assets/7200365/c76d3cc1-c8af-49cc-bbd2-1400b7ef17bb">

**Comment by dkoes** [comment]
Are you sure your VRML viewer supports transparency?  When I look at the export with FreeWRL the surfaces show as transparent.  I've added improved support for wireframes: 11bb7c68c0ccbcd9eabd9816da223b5e5fef075a

**Comment by dxdc** [comment]
Thanks!! It's looking good now.

> Are you sure your VRML viewer supports transparency

You're right... that was it!

Btw, in the raw VRML I see a lot of empty nodes like this. I imagine it's no impact to the ultimate display, but probably a function of how the VRML code is generated since it appears to recursively iterate through its geometry / children. Not sure if there is a way to check and ignore empty nodes like that or flatten the structure first to remove groups with a single child.

```
 Transform {
  center 0 0 0
  rotation 0 0 0 0
  children [
  Transform {
   center 0 0 0
   rotation 0 0 0 0
   children [
   Transform {
    center 0 0 0
    rotation 0 0 0 0
    children [
 ```
