### ISSUE TITLE
[BUG] Crystal supercell displays in a very weird way

### ISSUE THREAD

**Issue by fxcoudert** [3dmol/3Dmol.js#770]
**Describe the bug**
Loading a CIF file with symmetry and duplicating the unit cell gives this:

<img width="568" alt="Capture d’écran 2024-02-23 à 18 48 06" src="https://github.com/3dmol/3Dmol.js/assets/1980544/f48b75d6-df17-4240-8a10-7ed9390863c9">

**To Reproduce**
I've put an example online at https://www.nanoporous.net/MOF_viewer/
1. Select HKUST-1 P1
2. Then select HKUST-1 with symmetry
3. See the difference

Both files represent exactly the same structure, one has symmetry information.

**Expected behavior**
The full code is in the webpage source. The loading code is this:

```        let v = viewer;
        v.clear();
        let m = v.addModel(data, 'cif', {doAssembly: true, duplicateAssemblyAtoms: true, normalizeAssembly: true});
        v.addUnitCell(m, {box: {color: 'purple'}, alabel: 'a', blabel: 'b', clabel: 'c'});
        v.setStyle({stick: {colorscheme: 'Jmol'}});
        v.replicateUnitCell(2, 2, 2, m, true);
        v.setProjection('orthographic');
        v.zoomTo();                          /* set camera */
        v.render();                          /* render scene */
        v.zoom(1.8, 1000);                   /* slight zoom */
```

and the two relevant lines are:

```
        let m = v.addModel(data, 'cif', {doAssembly: true, duplicateAssemblyAtoms: true, normalizeAssembly: true});
        v.replicateUnitCell(2, 2, 2, m, true);
```

I must confess from the documentation that the "assembly" process and related options are not very clear.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: observed on multiple browsers, Safari and Firefox

**Comment by dkoes** [comment]
Are you sure the issue isn't with the data (ie, this is the right answer)?   PyMol produces something similar.
![image](https://github.com/3dmol/3Dmol.js/assets/2342142/006e837f-de82-44ed-af75-8c80f91488a9)

**Comment by fxcoudert** [comment]
Yes I am sure :)

This is what reference software for CIF files show. CrystalMaker:

<img width="495" alt="Capture d’écran 2024-02-24 à 09 01 10" src="https://github.com/3dmol/3Dmol.js/assets/1980544/685c2e6b-128b-4773-a4ac-4a378b884066">

Mercury:

<img width="539" alt="Capture d’écran 2024-02-24 à 09 01 20" src="https://github.com/3dmol/3Dmol.js/assets/1980544/3a00a26c-373b-4c2a-bae8-4d46d80457ea">

When loading a CIF file, all atoms should be inside the unit cell.

**Comment by dkoes** [comment]
This is exactly Issue #759.  You need to pass an additional boolean argument to replicateUnitCell (prune) so atoms outside the unit cell aren't shown.  I apologize for not updating the documentation (it is updated now).

**Comment by fxcoudert** [comment]
@dkoes I apologise if I am being slow or dense, but I am not sure I understand the link with that issue. #759 is about atoms exactly at the boundary of the unit cell (if I read that correctly), which is not my case.

I tested the `prune` parameter. With `replicateUnitCell(2, 2, 2, model, true, false)` I still have the old behaviour:

<img width="571" alt="Capture d’écran 2024-02-25 à 00 44 39" src="https://github.com/3dmol/3Dmol.js/assets/1980544/ce0c1b19-43d2-42b5-9071-3d64c79f4513">

With `replicateUnitCell(2, 2, 2, model, true, true)` I have something even weirder:

<img width="615" alt="Capture d’écran 2024-02-25 à 00 45 10" src="https://github.com/3dmol/3Dmol.js/assets/1980544/e5029367-133c-4700-8603-a4c68516e4d3">

where the unit cell is not replicated, and still there are atoms outside the unit cell.

**Comment by fxcoudert** [comment]
OK, I just understood that the issue is not with `replicateUnitCell`. Even if I don't replicate the unit cell, this line:

```
        let m = v.addModel(data, 'cif', {doAssembly: true, duplicateAssemblyAtoms: true, normalizeAssembly: true});
```

will give the rendering below:

<img width="508" alt="Capture d’écran 2024-02-25 à 00 55 03" src="https://github.com/3dmol/3Dmol.js/assets/1980544/3c4381ab-3c81-4825-afe4-25b829f15e01">

From the documentation, I believe `normalizeAssembly` should not let it do that?

**Comment by dkoes** [comment]
I see what is going on here.  `normalizeAssembly` will adjust all the symmetry operations so that the center of the reference molecule remains in the unit cell after transformation. That is, it wraps the whole molecule as a unit.  To get what I presume is your desired behavior it is necessary to wrap individual atoms.  I've added this option (`wrapAtoms`) which must be specified with `duplicateAssemblyAtoms` since it wouldn't be possible to wrap atoms of the same image differently otherwise.  I think this does what you want:
https://3dmol.org/tests/auto/generate_test.cgi?test=wrapatoms

**Comment by fxcoudert** [comment]
Yeah, that works perfectly. Thanks!

**Comment by fxcoudert** [comment]
Oh, I'm seeing what I think is a regression on another structure with symmetry. 

Going to https://www.nanoporous.net/MOF_viewer/ and selecting MIL-101 in the dropbox:

<img width="545" alt="Capture d’écran 2024-03-10 à 12 34 47" src="https://github.com/3dmol/3Dmol.js/assets/1980544/2d206db6-16af-4bfb-8f6c-210160c3fb2e">

The CIF file is: https://www.nanoporous.net/MOF_viewer/MIL-101.cif
Two things are weird:
- some atoms are outside the cell, despite `wrapAtoms: true`
- there are many bonds from one side to another

**Comment by dkoes** [comment]
The issue with that file is the reference coordinates are outside the box to start with.  I've modified wrapAtoms to also wrap the reference coordinates (identity matrix symmetry).  I've also changed the bond detection behavior to not determine bonds before wrapping.

**Comment by dkoes** [comment]
https://3dmol.org/tests/auto/generate_test.cgi?test=anotherwrap
