### ISSUE TITLE
Can't select properly, nor generate cartoon & multiple structures

### ISSUE THREAD

**Issue by JavierSanchez-Utges** [3dmol/3Dmol.js#772]
Hi, I am having issues showing the cartoon for the protein atoms in one of my files. Here I attach it (had to change extension to .txt to attach it here, but it is .cif. What I want to do is format ligands in sticks and protein in cartoon, something I have used on other occasions. This is the code I was using:
```
viewer.addStyle({hetflag: true},{stick:{colorscheme:"greenCarbon"}});
viewer.addStyle({hetflag: true, invert: true}, {cartoon: {style: 'oval', color: 'white', arrows: true,}});
```
First line works and displays all HETATMS as sticks and greenCarbon colour scheme, but second does not work. The selection does work and selects all PROTEIN atoms, as sticks works, but nor cartoon.

1. Any idea why this might be?

2. Is this the best way to select HETATM and ATOM, using the `hetflag`?

3. I am working with multiple structures, or models, opened at the same time. How can I select by model? I saw there is the `model` argument. Is this it? Are models numbered in the order they are loaded,

 So if I loaded these 3 files, model 2 is the second one I loaded?

For example, I want to select residue number 807, of chain A of model 3 (6ej1_A_trans.cif). Would it be something like: `{resi: 807, chain: 'A', model: 3}`?

I actually can't make this command work here: `viewer.addStyle({resn: 'EDO'},{stick:{color: "blue"}});`.

Thanks so much!

[5fpu_A_trans.txt](https://github.com/3dmol/3Dmol.js/files/14494945/5fpu_A_trans.txt)
[5fz1_A_trans.txt](https://github.com/3dmol/3Dmol.js/files/14494913/5fz1_A_trans.txt)
[6ej1_A_trans.txt](https://github.com/3dmol/3Dmol.js/files/14494650/6ej1_A_trans.txt)

**Comment by JavierSanchez-Utges** [comment]
I have now realised that there must be some parsing issue. Whilst I have processed these files, and they are not the same as downloaded from PDB, they work fine with Chimera, ChimeraX and PyMol. I am assuming there must be some field missing from them that 3DMol.js uses. I replaced the files by raw ones and the commands work fine.

Complex selections also work fine, like so: `{hetflag: true, model: 10, resn: 'EDO', chain: 'A', resi:1771,}`, selecting the ResNum `1771` from Chain `A` of model `10`, which is an `HETATM` with resName `EDO`.

I have also noticed that the models are identified with the method `$model.getID()`, and that the order  is determined by the order they are loaded into the viewer, which might be different to the order they are passed to it. 

It would be great to find out what is the parsing issue and if it can be fixed, as I have thousands of these processed files that I want to visualise using 3DMol.js !

Thanks!

**Comment by JavierSanchez-Utges** [comment]
I have realised my files are missing two fields from the `_atom_site` category: these are `auth_comp_id` and `auth_atom_id`, which seem to be used in the parsing of the CIF file: https://3dmol.csb.pitt.edu/doc/parsers_CIF.ts.html.

Perhaps what happens is these are left `undefined` and therefore selections don't work. However, other visualisation software work well with these files. Maybe when they realise `auth_comp_id` and `auth_atom_id`, they use `label_comp_id` and `label_atom_id`.

I could try to edit the parser in `.ts` to accommodate for this and see what happens...

**Comment by JavierSanchez-Utges** [comment]
Do you think editing lines 245-250 of the CIF parser (https://3dmol.csb.pitt.edu/doc/parsers_CIF.ts.html) like so would work?

```
atom.resn = mmCIF._atom_site_auth_comp_id
    ? mmCIF._atom_site_auth_comp_id[i].trim()
    : (mmCIF._atom_site_label_comp_id
        ? mmCIF._atom_site_label_comp_id[i].trim()
        : undefined);
atom.atom = mmCIF._atom_site_auth_atom_id
    ? mmCIF._atom_site_auth_atom_id[i].replace(/"/gm, "")
    : (mmCIF._atom_site_label_atom_id
        ? mmCIF._atom_site_label_atom_id[i].replace(/"/gm, "")
        : undefined); // "primed" names are in quotes
```

With this code, I intent that if `_atom_site.auth_atom_id` is missing, the `label_atom_id` is used, and the same for `_atom_id`.

I am currently using the latest version minified files, I guess if I want to try to edit the source code, I have to git clone the repository and install the library with npm?

Thanks!

**Comment by dkoes** [comment]
I really think replacing the double quotes with single quotes when the string contains a single quote is simply wrong of biopython as the string is no longer well formed.

**Comment by dkoes** [comment]
I've committed a workaround for biopython's broken cif files:
https://3dmol.org/tests/auto/generate_test.cgi?test=cifprime

**Comment by JavierSanchez-Utges** [comment]
I do agree BioPython is making a mistake with the double quotes. Thanks so much for the workaround. I really appreciate it. All my example files are working fine now!

<img width="450" alt="Screenshot 2024-03-07 at 09 57 52" src="https://github.com/3dmol/3Dmol.js/assets/47176177/600804b0-b5e1-466e-a598-8fc3bc90a0d7">
