### ISSUE TITLE
Stick representation for IONS

### ISSUE THREAD

**Issue by JavierSanchez-Utges** [3dmol/3Dmol.js#775]
Is is possible to represent ions, e.g., Zn, Mg, Cd as sticks? I just realised I am not seeing any of them when showing sticks for `hetflag: true`. Sphere is too big, and cross is not exactly what I am looking for.

Same for the waters, actually, I can only display them as cross and sphere, but not as sticks either. I think it would be great to have the option to display them as sticks (even though there are no bonds, it would just be the end of the stick), but it is a smaller representation, that whilst allowing identification and location of the ions, doesn't cover large regions of the protein, as the sphere representation does.

This is currently how it is looking.

<img width="450" alt="Screenshot 2024-03-07 at 09 44 05" src="https://github.com/3dmol/3Dmol.js/assets/47176177/6f13322f-b0e6-47eb-8004-d8043930ee3e">

5FV3 also works as an example, as it presents `Zn`, `Mn` and `Cl` ions. 

[5fv3_A_trans.txt](https://github.com/3dmol/3Dmol.js/files/14522175/5fv3_A_trans.txt)

Thanks!

**Comment by dkoes** [comment]
stick is a visualization of bonds, it doesn't make sense for non-bonded atoms.  Set their style individually:
`setStyle({bonds: 0},{sphere: {radius: 0.15}})`

**Comment by JavierSanchez-Utges** [comment]
Ah, of course. Changing the radius of the sphere. Precisely what I needed. Thanks!
