### ISSUE TITLE
Highlighting specific residues

### ISSUE THREAD

**Issue by KeaunAmani** [3dmol/3Dmol.js#781]
Is there a way to select some specific residues and then highlight them but not color them differently? I want to highlight some residues that are already colored by some color scheme similar to how selecting residues in pymol doesn't color them.

**Comment by dkoes** [comment]
We don't have any built-in highlight style; you have to implement it yourself.  For example, you could add transparent spheres around the selected atoms.

**Comment by KeaunAmani** [comment]
@dkoes Ah that makes sense. By any chance would happen to have any example code for this or something similar to this?

**Comment by dkoes** [comment]
https://3dmol.org/tests/auto/generate_test.cgi?test=testclick

**Comment by KeaunAmani** [comment]
@dkoes thanks I got it work but it leaves a bit to be desired. Got any suggestions based off the below screenshot?


![image](https://github.com/3dmol/3Dmol.js/assets/108769308/d15d4084-02d7-45ea-b07d-e42a7e9cf34c)

**Comment by dkoes** [comment]
I would change the color.  Alternatively, you could use `createModelFrom` to create a copy of the selected atoms and then render that copy using a slightly larger transparent version of the current style (e.g., transparent white or yellow).  This should looks like a glow.

**Comment by KeaunAmani** [comment]
@dkoes That's a fantastic idea thank you for the suggestions!

**Comment by KeaunAmani** [comment]
@dkoes what is the optimal way to delete the copied model from `createModelFrom`?

**Comment by dkoes** [comment]
https://3dmol.org/doc/GLViewer.html#removeModel
