### ISSUE TITLE
Dinamic protein visualization 

### ISSUE THREAD

**Issue by ASGMc17** [3dmol/3Dmol.js#786]
My request is for developers to be able to work with pdb files with dynamic proteins, such as the play button option on PYmol.
This request won't help me in any way because this is for a university project that I hand in this week, but it would be a good feature to have. The pdb file is generated in a matlab program where you target torsion angles, and constrain others to create a loop movement, see paper on: The Effect of End Constraints on Protein Loop Kinematics - Loop modeling using torsion angle targeting by Hayward and Akio Kitao.

**Comment by dkoes** [comment]
Support for trajectories/multi-model files is already available (https://3dmol.org/tests/auto/generate_test.cgi?test=testframestyle).  A play button would be part of a user interface.  Unfortunately, this is not implemented in the provide UI, but pull requests are always welcome.
