### ISSUE TITLE
Color per BetaFactor ('prop':'b') with CIF as input

### ISSUE THREAD

**Issue by tubiana** [3dmol/3Dmol.js#792]
Hi all!

I cannot manage to find the right property to color per BetaFactor when the input is a CIF file (field = `_atom_site.B_iso_or_equiv`)
I use py3Dmol in a google colab, and when the input is a PDB the regular code should be  
`` view.setStyle({'cartoon': {'colorscheme': {'prop':'b','gradient': 'roygb','min':50,'max':90}}})`` 

However it's all gray. I tried to replace `b` with `B_iso_or_equiv` but it doesn't work. 

Did I miss the right property name in 3Dmol or is it not implemented ?

Thanks :)
Thibault

**Comment by dkoes** [comment]
It wasn't implemented.  It is now (in the just released version 2.2.0) along with binary CIF support.

**Comment by tubiana** [comment]
Ok great I'm lucky then :) thank you so much!

I'm new with 3Dmol, and I was wondering if there is a way to compile the 3Dmol.js located in `https://3dmol.org/build/3Dmol.js` or when this one will be updated :) ?

Best,
Thibault.

**Comment by tubiana** [comment]
EDIT : 

Nevermind, I have check the documentation, did an `npm run build:prod` and use the new 3Dmol-min.js, and it works =D 
![image](https://github.com/3dmol/3Dmol.js/assets/8037224/ffb1d234-a328-419c-a8fe-b21808a0df7e)

I have a practical to give to student on Tuesday, and you just save it =D

Best,
Thibault

**Comment by dkoes** [comment]
Should be able to simply pip update to 2.2.. but glad you figured it out.
