### ISSUE TITLE
[BUG] Dependencies creeping out again

### ISSUE THREAD

**Issue by NicolasCARPi** [3dmol/3Dmol.js#794]
**Describe the bug**
Hello,

While looking at the latest version, I realized that installing it adds  94 packages to the project (+ 24.64 MiB).

This is due to `npm` and `nvm` being listed as dependencies. Please move them to `devDependencies` or remove them completely (I'm not quite sure why they are here in the first place, maybe that's a mistake, seems weird to depend on npm).

As for nvm, pretty sure it's a mistake, given:

![2024-07-14-213634_970x232_scrot](https://github.com/user-attachments/assets/b0c67b90-e19c-4478-906e-009fded13e8b)

**To Reproduce**
Upgrade to 2.2.0.

**Expected behavior**
No new dependencies are added unless absolutely necessary and required by the project to work.

**Screenshots**
![2024-07-14-213418_1302x137_scrot](https://github.com/user-attachments/assets/fd066785-2361-463b-a981-63c080195bee)

**Additional context**
Similar issue to https://github.com/3dmol/3Dmol.js/issues/649 and https://github.com/3dmol/3Dmol.js/issues/724.

**Comment by dkoes** [comment]
Fixed.  Sorry, will try to be more careful in the future.

**Comment by NicolasCARPi** [comment]
Cheers :rocket:
