### ISSUE TITLE
Changing residue colors in real time!

### ISSUE THREAD

**Issue by louetadelie1** [3dmol/3Dmol.js#798]
Hi, 

I am trying to dynamically change the colors of my residues for each frame (I have a list of frames [0..100]), and want to show them dynamically changing properties (illustrated by change on colorspectrum) throughout the trajectory. However, I can't get it to work. 

I have a nested list with the [number,resid,color_code],[ (eg-[1, '#fff5b4']...) for each frame, and I am trying to get it to iterate over this list as well as the molecule view simulateneously so that the peptide can change colorscheme at each frame. Here is my code so far:
```

class Atom(dict):
    def __init__(self, line):
        self["type"] = line[0:6].strip()
        self["idx"] = line[6:11].strip()
        self["name"] = line[12:16].strip()
        self["resname"] = line[17:20].strip()
        self["resid"] = int(int(line[22:26]))
        self["x"] = float(line[30:38])
        self["y"] = float(line[38:46])
        self["z"] = float(line[46:54])
        self["sym"] = line[76:78].strip()

    def __str__(self):
        line = list(" " * 80)

        line[0:6] = self["type"].ljust(6)
        line[6:11] = self["idx"].ljust(5)
        line[12:16] = self["name"].ljust(4)
        line[17:20] = self["resname"].ljust(3)
        line[22:26] = str(self["resid"]).ljust(4)
        line[30:38] = str(self["x"]).rjust(8)
        line[38:46] = str(self["y"]).rjust(8)
        line[46:54] = str(self["z"]).rjust(8)
        line[76:78] = self["sym"].rjust(2)
        return "".join(line) + "\n"

class Molecule(list):
    def __init__(self, file):
        for line in file:
            if "ATOM" in line or "HETATM" in line:
                self.append(Atom(line))

    def __str__(self):
        outstr = ""
        for at in self:
            outstr += str(at)

        return outstr

view = py3Dmol.view(width=400, height=300)

molecules = []
for i in range(1, 10):
    with open(path + "pair" + str(i) + ".pdb") as ifile:
        molecules.append(ifile.read())

models = ""
for i, mol in enumerate(molecules):
    models += "MODEL " + str(i + 1) + "\n"
    models += mol
    models += "ENDMDL\n"

view.addModelsAsFrames(models)

for i, color_map in zip(molecules,enumerate(resid_hex)):
    for resi, color in color_map:
        view.setStyle({'model': i, 'resi': resi}, {"sphere": {'color': color}})

view.zoomTo()
view.animate({'loop': "forward"})
view.show(). Thanks for any advice!
```

**Comment by dkoes** [comment]
If you want to apply a style to individual frames, you need to select only the atoms from that frame by including the frame in the atom selection, like with this example:
https://3dmol.org/tests/auto/generate_test.cgi?test=testframestyle

However, if you want to color by property, since you have PDB files, I recommend setting the b factor and applying the appropriate colorscheme as here:
https://3dmol.org/tests/auto/generate_test.cgi?test=customlinear

**Comment by louetadelie1** [comment]
I followed your instructions and applied a new colorscheme for each individual frame and it worked like a charm! Thank you!

**Comment by dkoes** [comment]
You shouldn't have to apply the colorscheme per-frame - the whole point of using a colorscheme mapping property values is it is applied across frames.

**Comment by louetadelie1** [comment]
But does this work if I am using a new colorscheme for each frame?

**Comment by dkoes** [comment]
No, the idea is you change the properties that are being mapped, not the color scheme.  But whatever works best for you.
