### ISSUE TITLE
[BUG] Broken link in docs tutorial

### ISSUE THREAD

**Issue by dflock** [3dmol/3Dmol.js#799]
**Describe the bug**

This page: https://3dmol.org/doc/tutorial-code.html includes a link:

```
All these methods (and more) are covered in detail in the [API documentation for GLViewer](https://3dmol.org/doc/$3Dmol.GLViewer).
```

This link is broken.

**To Reproduce**

Go here: https://3dmol.org/doc/tutorial-code.html, scroll about halfway down, click the link.

**Expected behavior**

I _think_ this is probably the correct destination for this link: https://3dmol.org/doc/GLViewer.html

**Additional context**

This is the line of code in the doc src with the broken link:

https://github.com/3dmol/3Dmol.js/blob/master/tutorials/code.md?plain=1#L133

I would fix this, but I'm not 100% sure where this link is supposed to go, or _how_ relative links ar intended to be encoded in the docs src.

**Please close your issue when you feel it has been adequately resolved**

**Comment by dkoes** [comment]
Fixed above, thanks for the report!
