### ISSUE TITLE
[BUG] Background Alpha Non-Functional

### ISSUE THREAD

**Issue by gplewy** [3dmol/3Dmol.js#800]
The following code seems to have stopped giving a viewer with a transparent background:

let config = { backgroundAlpha: 0, nomouse: true };
let viewer = $3Dmol.createViewer( element, config );

viewer.setBackgroundColor('green', 0); also does not provide a transparent background.

Confirmed on Google Chrome 127.0.6533.72 and Safari 16.4. $3DMol is generated from <script src="https://3Dmol.org/build/3Dmol-min.js"></script> 

Any option for generating a viewer with a transparent background would be appreciated.

Thank you very much for your work on this excellent library.

**Comment by dkoes** [comment]
Could you possibly provide a self-contained example?  Most likely this is due to the better anti-aliasing in 2.3.0 (setting `antialias: false` in config would confirm).

**Comment by gplewy** [comment]
`antialias: false` successfully rendered the background transparent again.

Thank you for your swift response!

**Comment by dkoes** [comment]
This was a legitimate bug. ceda936caf78c6db46010a8b0276149259cbcb66 fixes background alpha with antialiasing on.

**Comment by gplewy** [comment]
When background alpha is set to 0, the viewer's background remains opaque on Chrome on Windows machines, but is transparent on Chrome on Mac. This is regardless of antialias settings.

Example 1:

```
<script src="https://3Dmol.org/build/3Dmol-min.js"></script> 
<div style="height: 400px; width: 400px; position: relative;" class='viewer_3Dmoljs' data-pdb='2POR' data-backgroundalpha='0' data-backgroundcolor='0xffffff' data-style='stick' data-ui='true'></div>      
``` 

Viewer config from Example 2:

`let config = { backgroundAlpha: 0, backgroundColor: 0x000000, nomouse: true, antialias: false }`

I'd be very grateful for a fix if possible.
