### ISSUE TITLE
ViewStyle outline width to self adjust

### ISSUE THREAD

**Issue by JavierSanchez-Utges** [3dmol/3Dmol.js#801]
Hi! I was wondering if it is possible for the `ViewStyle outline width` to self adjust as one zooms in and out on the viewer. Right now, it looks like the width is fixed to some reference, perhaps default zoom, so when one zooms in closer, the outline gets thicker.

I adjust 3DMol.js and ChimeraX screenshots for reference. This is my styles code for reference:

```viewer.setViewStyle({style:"outline", width:0.0625, color:"black"});```

Thanks a lot.

<img width="350" alt="Screenshot 2024-08-15 at 15 18 01" src="https://github.com/user-attachments/assets/e53634c0-8628-41b9-9c92-451e9dfb7dc6">
<img width="350" alt="Screenshot 2024-08-15 at 15 18 46" src="https://github.com/user-attachments/assets/216ddb4f-a2a3-4b73-886c-35c3e8ae2a86">
<img width="350" alt="Screenshot 2024-08-15 at 15 19 09" src="https://github.com/user-attachments/assets/ddceaf43-d3af-4838-9881-4c5ceea333c9">
<img width="350" alt="Screenshot 2024-08-15 at 15 19 27" src="https://github.com/user-attachments/assets/5f4b1e0d-4e73-4bd0-9802-2fe9dfe5b120">

My code: (.html changed to .txt to upload to GitHub issue)
[arpeggio_cons.txt](https://github.com/user-attachments/files/16626226/arpeggio_cons.txt)

My structure: (.cif changed to .txt to upload to GitHub issue)
[3e8e_bio.txt](https://github.com/user-attachments/files/16626234/3e8e_bio.txt)

**Comment by dkoes** [comment]
This is because the outline width is in model space and scales with the zoom level.  I don't think you want a fixed width in screen space outline as then when you zoom out it would become all outline.  I've added a `maxpixels` options that caps with screen space width of the outline as shown here:
`viewer.setViewStyle({style:"outline","maxpixels":5});`

https://3dmol.org/tests/auto/generate_test.cgi?test=outlinemaxpixels

**Comment by dkoes** [comment]
Released (2.4.0)

**Comment by JavierSanchez-Utges** [comment]
Thanks, @dkoes. That was a quick implementation. I think it is a nice setting to be able to change!

  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;No `maxpixels`&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`maxpixels: 2`

<img width="350" alt="Screenshot 2024-09-04 at 11 56 11" src="https://github.com/user-attachments/assets/408c07fe-f99a-4f10-969b-cca6c34414bc">

<img width="350" alt="Screenshot 2024-09-04 at 11 58 26" src="https://github.com/user-attachments/assets/f61aa23c-dcf3-4a73-998c-0261a4d78933">

I prefer it much better like this!
