### ISSUE TITLE
Create custom style

### ISSUE THREAD

**Issue by S0udy** [3dmol/3Dmol.js#802]
I want to view my molecules in this style with the Atom Symbol like this 
can anyone help how to do with _**py3dmol**_
![newview3](https://github.com/user-attachments/assets/76035f38-6eb5-4c17-9ee7-1f091aa467bf)
![Opera Snapshot_2024-08-19_040029_www talbica com](https://github.com/user-attachments/assets/36f2611f-fa81-4019-b703-e3fb368c218a)

**Comment by dkoes** [comment]
```
v = py3Dmol.view('cid:2340',style='stick')
v.addPropertyLabels('elem',{},{'backgroundOpacity':0,'fontColor':'black','alignment':'center','bold':True})
```

**Comment by S0udy** [comment]
> ```
> v = py3Dmol.view('cid:2340',style='stick')
> v.addPropertyLabels('elem',{},{'backgroundOpacity':0,'fontColor':'black','alignment':'center','bold':True})
> ```

Thsnks so much
