### ISSUE TITLE
Request for viewer.showLabel(label);

### ISSUE THREAD

**Issue by JavierSanchez-Utges** [3dmol/3Dmol.js#805]
I am playing around with labels quite a bit using `viewer.addLabel()` to show them and then `viewer.removeLabel()` to remove them.

I think it would be quite nice to implement a new method `viewer.showLabel()` to show labels, so exactly the opposite. In this way, the `addLabel` could be edited so it does not show the label, it just creates the label object. These labels could then be stored in another object like an array or a hash, and could be removed (`removeLabel`) or shown (`showLabel`) whenever.

Is there a way around this without the need of this method that isn't adding again the labels that have already been removed?

Many thanks!

**Comment by dkoes** [comment]
The label objects now have show and hide methods. For example:
https://3dmol.org/tests/auto/generate_test.cgi?test=hidelabel

**Comment by dkoes** [comment]
Released (2.4.0).

**Comment by JavierSanchez-Utges** [comment]
That is brilliant. Thanks so much!
