### ISSUE TITLE
Implementation of showing and hiding Cylinders

### ISSUE THREAD

**Issue by JavierSanchez-Utges** [3dmol/3Dmol.js#807]
Hi! I am working with quite a lot of cylinders with their callback functions (hover labels) and I think it would be great if you could also show and hide them once they’re created, just like for the labels. I currently create them with `addCylinder` and remove them with `removeShape`. I think being able to hide them and show them without having to remove and re-create them would be great.

Thanks!

**Comment by dkoes** [comment]
You should be able to call `updateStyle` with `hidden: true` (or false) to get this behavior.

**Comment by JavierSanchez-Utges** [comment]
That is right, didn’t think of it. Many thanks!
