### ISSUE TITLE
Unable to implement a XYZ file in embedded viewer through data-href [BUG]

### ISSUE THREAD

**Issue by adaudon** [3dmol/3Dmol.js#809]
**Describe the bug**
Not clear how to use a XYZ file in the viewer from the documentation. I've tried both using an external file and a string variable but the viewer remains blank. Things like data-cid and data-pdb work well however I require it to work with xyz data. I can't find any online .xyz files to link to with href either.

**To Reproduce**
```
import './App.css'
function App() {
    const xyzData = `
    3
    Water molecule
    O     0     0     0
    H     0.757 0.586 0
    H    -0.757 0.586 0`;
  return (
    <>
        <h1>3D Molecule Viewer</h1>
        <div style={{height: "400px", width: "400px", position: "relative"}}
            className='viewer_3Dmoljs'
            // data-cid="241"
            data-type="xyz"
            data-href="./water.xyz"
            data-backgroundcolor='cyan'
            data-style='stick'
            ></div>
    </>
  )
}

export default App
```

**Expected behavior**
I would expect the model matching the XYZ file to be shown in the viewer instead of a blank viewer.

**Desktop (please complete the following information):**
 - OS: Linux Fedora
 - Browser Firefox

**Comment by dkoes** [comment]
The first line of the xyz file needs to be the atom count. Above your xyzData starts with a blank new line.  It is somewhat strange to be using the embedding API when you are clearly writing a javascript app.   The following works fine for me as long as `water.xyz` is a proper xyz file (first line is a "3"):
```html
<!DOCTYPE html>
<html lang="en">
 <head>
 <script src="https://3Dmol.org/build/3Dmol.js"></script>
 </head>
 <body>
        <div style='height: 400px; width: 400px'
            class='viewer_3Dmoljs'
            data-type="xyz"
            data-href="./water.xyz"
            data-backgroundcolor='cyan'
            data-style='stick'
            ></div>
 </body>
</html>

```
