### ISSUE TITLE
Disable Zoom Functionality

### ISSUE THREAD

**Issue by YeeChuen** [3dmol/3Dmol.js#813]
Disable Zoom Functionality

**Description**
I am building a react project that utilize 3dmol to visualize protein structure, but I also want to disable Zoom functionality from mouse action. (I still want my mouse to be able to click and drag to interact with the 3dmol)

**Relevant Context**
here's the current code
```
      let config = {
        backgroundColor: "white",
        lowerZoomLimit: 200,
        upperZoomLimit: 400,
        disableFog: true,
      };
      const fullProteinViewer = ThreeDmol.createViewer(
        fullProteinRef.current,
        config
      );
      fullProteinViewer.addModel(pdbIdData, "pdb");
      fullProteinViewer.setStyle({}, { cartoon: { color: "spectrum" } });
      fullProteinViewer.setBackgroundColor("white");
      fullProteinViewer.zoomTo();
      fullProteinViewer.render();
```

**Please close your issue when you feel it has been adequately resolved**

**Comment by dkoes** [comment]
You can set the `nomouse` viewer property and then install your own mouse handlers:
https://3dmol.org/doc/ViewerSpec.html#nomouse

**Comment by YeeChuen** [comment]
I've tried that, but it completely remove the click and drag functionality

**Comment by dkoes** [comment]
You need to reinstall the default handlers, but not the scroll.  If you want to avoid zoom altogether, you will need to wrap the call to the default mouse move handler to ignore input when mouse buttom 3 or the shift key is being used.

**Comment by YeeChuen** [comment]
Thank you for advising on reinstalling the default handlers, one quick fix I am able to get to is to over the instance method as a whole, such as below: 

```
import * as ThreeDmol from "3dmol/build/3Dmol.js";
      ThreeDmol.GLViewer.prototype._handleMouseScroll = function (ev) {
        // console.log("Mouse Down event overridden for this instance!");
        // Add custom behavior here
      };
```

without using nomouse and reinstalling all default handlers, but I bet this is not the best practice as now the whole application does not have scroll functionality.

I'll investigate more on how to only override on specific instance.

Thank you dkoes!
