### ISSUE TITLE
HELP with GLModel.removeAtoms()

### ISSUE THREAD

**Issue by JavierSanchez-Utges** [3dmol/3Dmol.js#816]
Hi, I am trying to remove some atoms and I can't manage to make it work. I would like to delete Hydrogen atoms, for example. Could anyone help me with this?

I am trying to do so with the `GLModel.RemoveAtoms()` method: https://3dmol.csb.pitt.edu/doc/GLModel.html#removeAtoms. But I can't manage to make it work.

What needs to go exactly into the `badatoms`  `AtomSpec`? I have tried AtomSelectionSpec `{elem: 'H'}`, I have tried just `atom: 'H'}, `elem: 'H'` and `'H'` and even a list of atom indices from my selection: ```viewer.models[2].selectedAtoms({ elem: 'H' }).map(atom => atom.index);```.

Am I not providing the needed input for this function, am I missing something or is this a bug?

The example I am trying is PDB: 7PCS.

<img width="300" alt="Screenshot 2024-11-25 at 13 00 52" src="https://github.com/user-attachments/assets/d38e71ec-c11f-47eb-b282-8a92057e45e0">

Thanks!

**Comment by dkoes** [comment]
Yes, although you could also simply not show them when setting styles.

**Comment by JavierSanchez-Utges** [comment]
Yes, I started like that, but I have so many `addStyle()` commands that it's just easier to remove them for now.

I might try including them in my base `protAtoms` and `hetAtoms` selections too, and that should do it. Thanks, David!
