### ISSUE TITLE
[BUG] VRML exporter outputs an OBJ that can't be opened

### ISSUE THREAD

**Issue by deliciouslyevil** [3dmol/3Dmol.js#819]
**Describe the bug**
I included the exportVRML() function in my code, and when I do so, it exports a .obj file.  The file can't be opened in any software I tried, but if I rename the file extension to .wrl it works perfectly.  

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser : Chrome
 - Version: 131.0.6778.140 

**Additional context**
It just seems like the wrong file extension is being applied to the output file judging by the name of the function and the contents of the file.

**Comment by dkoes** [comment]
`exportVRML` returns a string, the contents of which are a VRML file (`.wrl`).  If you choose to save this data to a file with a `.obj` extension, which is a different file format, it will not work.

**Comment by deliciouslyevil** [comment]
So sorry, I thought this was being set by default, but it was hidden away earlier in my code where I set the extension.
