### ISSUE TITLE
pdb parser needs to be even more intelligent with guessing atom element

### ISSUE THREAD

**Issue by dkoes** [3dmol/3Dmol.js#99]
When the element record is missing we have to infer the element from the atom name.  This is a heuristic processes and we could do better.  See openbabel's [parseAtomRecord](https://github.com/openbabel/openbabel/blob/master/src/formats/pdbformat.cpp) function for a more involved heuristic.

This should be implemented as its own utility function since it is ugly.

**Comment by jus1in** [comment]
Do you have any examples of files with the element missing?

**Comment by dkoes** [comment]
I've committed tests/test_structs/mdfile.pdb which is the result of an md simulation and so has annoying atom names. We are not currently parsing the iron (FE) correctly.  I fixed the hydrogens.

It's pretty clear from the openbabel source that there are a number of ad hoc corner cases and no clear answer for the perfect way to do this.
